'use strict';
(()=>{
 const questions=[
 ['ما هو سوق داريا الإلكتروني؟','سوق داريا الإلكتروني هو دليل لأماكن مدينة داريا ومتاجرها وخدماتها، ومنصة تتيح الطلب من المتاجر التي توفر الطلب عبر الموقع.'],
 ['ماذا أجد في الموقع؟','متاجر ومطاعم ومقاهي، وأطباء وعيادات وصيدليات، ومهن وخدمات، ومدارس ومساجد ومحامين، ضمن أقسام تسهّل الوصول إلى ما تحتاجه.'],
 ['كيف أبحث عن مكان أو خدمة؟','اختر القسم المناسب، أو اكتب اسم المكان أو المنتج أو الخدمة أو الشارع في خانة البحث.'],
 ['ماذا تعرض صفحة المكان؟','تعرض المعلومات المتاحة عنه، مثل الصور والوصف والعنوان والتواصل وساعات العمل، والمنتجات أو الخدمات والأسعار عند إضافتها.'],
 ['هل جميع الأماكن تستقبل طلبات؟','لكل مكان خياراته. بعض المتاجر تستقبل الطلبات وتوفر التوصيل أو الاستلام، وأماكن أخرى لها صفحات تعريفية للاطلاع على معلوماتها والتواصل معها.'],
 ['كيف أعرف المتاجر التي توفر التوصيل؟','اضغط على «خدمة التوصيل إلى منزلك» لعرض المتاجر التي تقدم هذه الخدمة، ثم راجع رسوم التوصيل ومناطقه والحد الأدنى للطلب داخل صفحة المتجر.'],
 ['كيف أجد الأماكن على الخريطة؟','افتح «خريطة داريا» من الشريط السفلي لعرض الأماكن من جميع الأقسام، أو افتح خريطة قسم محدد لعرض أماكنه فقط. تظهر الدبابيس للأماكن التي تم تحديد موقعها، وتتحمّل الخريطة عند الضغط عليها.'],
 ['هل أحتاج إلى حساب؟','يمكنك تصفّح الأماكن ومعلوماتها دون حساب. تحتاج إلى تسجيل الدخول عند إرسال طلب، ويمكنك بعدها متابعة طلباتك من «طلباتي».'],
 ['هل يمكن لصاحب متجر أو مكان الانضمام؟','نعم، يمكنه التواصل مع إدارة المنصة لإضافة مكانه. ويحصل صاحب المتجر على لوحة خاصة لإدارة معلوماته ومنتجاته وأسعاره وخيارات الطلب والتوصيل.'],
 ['هل يمكن استخدام الموقع على الهاتف؟','نعم، الموقع مناسب للجوال والكمبيوتر، ويتوفر تطبيق أندرويد للتحميل، مع إمكانية إضافة الموقع إلى الشاشة الرئيسية على آيفون.'],
 ['ما هدف الموقع؟','أن يجمع أماكن داريا وخدماتها في مكان واحد، ويسهّل على أهل المدينة اكتشافها والتواصل معها والوصول إليها، والطلب من المتاجر التي توفر هذه الخدمة.']
 ];
 const translations={en:[
 ['What is Daraya Online Market?','It is a guide to places, shops and services in Daraya. You can also order from shops that accept online orders.'],['What can I find here?','Shops, restaurants, cafés, doctors, clinics, pharmacies, local services, schools, mosques and lawyers.'],['How do I search?','Choose a section or search for a place, product, service or street.'],['What does a place page show?','Available photos, details, address, contact information, opening hours, products, services and prices.'],['Can I order from every place?','Each place has its own options. Some shops accept orders with delivery or pickup. Other pages provide information and contact details.'],['How do I find shops with delivery?','Select “Delivery to your home”, then check the shop page for delivery areas, fees and minimum order.'],['How do I find places on the map?','Open “Daraya map” in the bottom menu, or choose a section map. Pins show places with a known location. Maps load when you open them.'],['Do I need an account?','You can browse without an account. Sign in to send an order and see it under “My orders”.'],['Can a shop or place join?','Yes. Contact the platform team to add your place. Shop owners have a panel to manage details, products, prices, orders and delivery options.'],['Can I use it on my phone?','Yes. It works on phones and computers. You can download the Android app or add the site to your iPhone home screen.'],['What is the goal?','To bring Daraya places and services together, help people find and contact them, and order from shops that offer this service.']
 ],de:[
 ['Was ist der Online-Markt von Daraya?','Ein Verzeichnis für Orte, Geschäfte und Dienstleistungen in Daraya. Bei Geschäften mit Onlinebestellung kannst du auch bestellen.'],['Was finde ich hier?','Geschäfte, Restaurants, Cafés, Ärzte, Praxen, Apotheken, Dienstleistungen, Schulen, Moscheen und Anwälte.'],['Wie suche ich?','Wähle einen Bereich oder suche nach einem Ort, Produkt, einer Dienstleistung oder Straße.'],['Was zeigt eine Ortsseite?','Verfügbare Fotos, Beschreibung, Adresse, Kontakt, Öffnungszeiten sowie Produkte, Dienstleistungen und Preise.'],['Kann ich überall bestellen?','Jeder Ort hat eigene Optionen. Manche Geschäfte bieten Bestellung, Lieferung oder Abholung. Andere Seiten dienen der Information und Kontaktaufnahme.'],['Wie finde ich Geschäfte mit Lieferung?','Wähle „Lieferung zu dir nach Hause“ und prüfe Liefergebiete, Gebühren und Mindestbestellwert auf der Geschäftsseite.'],['Wie finde ich Orte auf der Karte?','Öffne die Daraya-Karte im unteren Menü oder die Karte eines Bereichs. Markierungen zeigen Orte mit bekanntem Standort. Die Karte lädt erst beim Öffnen.'],['Brauche ich ein Konto?','Zum Stöbern nicht. Melde dich an, um zu bestellen und deine Bestellungen unter „Meine Bestellungen“ zu sehen.'],['Kann ein Geschäft oder Ort teilnehmen?','Ja. Kontaktiere die Plattform, um deinen Ort hinzuzufügen. Geschäftsinhaber verwalten Informationen, Produkte, Preise, Bestellungen und Lieferoptionen in einer eigenen Verwaltung.'],['Kann ich die Website auf dem Handy nutzen?','Ja, auf Handy und Computer. Eine Android-App ist verfügbar. Auf dem iPhone kannst du die Website zum Home-Bildschirm hinzufügen.'],['Was ist das Ziel?','Orte und Dienstleistungen in Daraya zusammenzubringen und Menschen beim Entdecken, Kontaktieren, Finden und Bestellen zu helfen.']
 ]};
 function text(ar,en,de){return ({ar,en,de})[window.ShahinI18n?.language||'ar']||ar;}
 function renderAbout(){const app=document.querySelector('#app');app.classList.remove('professional-home');app.innerHTML='<section class="panel about-site"><div class="topline"><h1>'+text('ما هو الموقع؟','What is this website?','Was ist diese Website?')+'</h1><a class="button outline" href="#home">'+text('العودة للسوق','Back to the market','Zurück zum Markt')+'</a></div><div class="about-questions">'+(translations[window.ShahinI18n?.language]||questions).map(([q,a],i)=>'<details'+(i===0?' open':'')+'><summary>'+esc(q)+'</summary><p>'+esc(a)+'</p></details>').join('')+'</div></section>';}
 const previous=render;render=function(){if(location.hash==='#about'){renderAbout();return;}return previous.apply(this,arguments);};
 const menu=document.querySelector('#site-menu');if(menu){let link=menu.querySelector('a[href="#about"]');if(!link){link=document.createElement('a');link.href='#about';menu.append(link);}link.textContent=text('ما هو الموقع؟','What is this website?','Was ist diese Website?');}
 window.addEventListener('hashchange',()=>{if(location.hash==='#about')renderAbout();});
 document.querySelector('#language')?.addEventListener('change',()=>{if(location.hash==='#about')renderAbout();});
 if(location.hash==='#about')renderAbout();
})();
