'use strict';
(() => {
 const t=(ar,en,de)=>({ar,en,de}[window.ShahinI18n?.language||'ar']||ar);
 const homeBase=renderHome;
 renderHome=function(){homeBase.apply(this,arguments);const empty=document.querySelector('#browse .grid>.empty');if(!empty)return;empty.dataset.noTranslate='';const saved=browseFavorites||location.hash==='#saved';empty.innerHTML=`<h3>${saved?t('لا توجد أماكن محفوظة بعد','No saved places yet','Noch keine gemerkten Orte'):t('لم نجد أماكن مطابقة','No matching places','Keine passenden Orte gefunden')}</h3><p>${saved?t('اضغط على رمز القلب بجانب المكان الذي يعجبك لإضافته إلى المحفوظات، وستجده هنا لاحقًا.','Tap the heart next to a place you like to save it. You will find it here later.','Tippe auf das Herz neben einem Ort, um ihn zu merken. Du findest ihn später hier.'):t('جرّب كلمة أبسط، أو غيّر القسم والحي. يمكنك العودة إلى جميع الأماكن.','Try a simpler word or change the category and area. You can also show all places.','Versuche einen einfacheren Suchbegriff oder ändere Kategorie und Viertel. Du kannst auch alle Orte anzeigen.')}</p><button type="button" data-reset-search>${saved?t('اكتشف الأماكن','Explore places','Orte entdecken'):t('عرض جميع الأماكن','Show all places','Alle Orte anzeigen')}</button>`;empty.querySelector('button').onclick=()=>{filter='all';search='';browseFavorites=false;if(typeof communityState!=='undefined'){communityState.open=false;communityState.region='';communityState.near=false;}if(location.hash!=='#home')location.hash='#home';else renderHome();};};
 const storeBase=renderStore;
 renderStore=function(id){storeBase.apply(this,arguments);const s=stores.find(x=>x.id===id&&x.active&&!x.deleted_at),banner=document.querySelector('.store-banner');if(!s||!banner)return;const box=document.createElement('div');box.className='store-customer-tools';box.dataset.noTranslate='';
 const availability=s.is_example?t('متجر تجريبي؛ لا يستقبل طلبات حقيقية.','Sample shop; no real orders.','Beispielgeschäft; keine echten Bestellungen.'):s.online_ordering===false?t('هذه صفحة للتصفح والتواصل؛ لا تستقبل طلبات عبر التطبيق.','Browse and contact this business; it does not accept orders in the app.','Hier kannst du stöbern und Kontakt aufnehmen; keine Bestellungen in der App.'):canStoreOrder(s)?t('يمكن إرسال طلب عبر التطبيق الآن.','You can place an order in the app now.','Bestellungen in der App sind jetzt möglich.'):t('استقبال الطلبات عبر التطبيق غير متاح الآن. يمكنك تصفح الصفحة والتواصل مع المتجر.','Orders in the app are unavailable now. You can browse and contact the shop.','Bestellungen in der App sind derzeit nicht möglich. Du kannst stöbern und Kontakt aufnehmen.');
 const p=document.createElement('p');p.textContent=availability;const share=document.createElement('button');share.type='button';share.className='outline';share.textContent=t('مشاركة المتجر','Share this shop','Geschäft teilen');box.append(p,share);banner.after(box);
 share.onclick=async()=>{const url=typeof placePublicUrl==='function'?placePublicUrl(s):'https://damascus-shop.com/#store/'+encodeURIComponent(s.id);try{if(navigator.share&&!/ShahinAndroid\//.test(navigator.userAgent)){await navigator.share({title:s.name,url});return;}}catch(e){if(e.name==='AbortError')return;}try{await navigator.clipboard.writeText(url);toast(t('تم نسخ رابط المتجر','Shop link copied','Geschäftslink kopiert'));}catch{modal(`<section data-no-translate><h2>${t('مشاركة المتجر','Share this shop','Geschäft teilen')}</h2><input dir="ltr" readonly value="${esc(url)}"><p>${t('اضغط مطولًا على الرابط لنسخه، أو شاركه عبر واتساب.','Copy the link, or share it with WhatsApp.','Kopiere den Link oder teile ihn über WhatsApp.')}</p><a class="button" href="https://wa.me/?text=${encodeURIComponent(s.name+'\n'+url)}">WhatsApp</a></section>`);const input=document.querySelector('#modal-body input');input.onclick=()=>input.select();}};
 };
 function accountRequests(){const form=document.querySelector('#data-request-form');if(!form||form.dataset.requestTracking)return;form.dataset.requestTracking='';const status=document.createElement('div');status.dataset.requestHistory='';status.setAttribute('role','status');form.after(status);const uid=user?.id;if(!uid||!api)return;
  const load=async()=>{try{const r=await api.from('customer_data_requests').select('id,kind,status,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(5);if(r.error)throw r.error;if(user?.id!==uid||!status.isConnected)return;status.dataset.noTranslate='';status.innerHTML=`<h3>${t('متابعة طلبات بياناتي','My data requests','Meine Datenanfragen')}</h3>`+(r.data||[]).map(row=>`<p>${row.kind==='deletion'?t('طلب حذف الحساب','Account deletion request','Kontolöschung'):t('طلب تصحيح البيانات','Data correction request','Datenkorrektur')} — ${row.status==='pending'?t('قيد المراجعة','Pending review','In Prüfung'):t('تمت مراجعته؛ لا يعني ذلك تنفيذ الحذف','Reviewed; this does not confirm deletion','Geprüft; dies bestätigt keine Löschung')}</p>`).join('');}catch{if(status.isConnected){status.dataset.noTranslate='';status.textContent=t('تعذر تحميل حالة الطلبات. يمكنك طلب المساعدة عبر info@damascus-shop.com.','Could not load request status. Contact info@damascus-shop.com for help.','Status konnte nicht geladen werden. Hilfe: info@damascus-shop.com.');}}};
  const submit=form.onsubmit;let sending=false;form.onsubmit=async e=>{e.preventDefault();if(sending)return;sending=true;try{await submit(e);await load();}finally{sending=false;}};load();
  document.querySelectorAll('.customer-account [data-delete-link]').forEach(a=>{a.onclick=e=>{e.preventDefault();form.elements.kind.value='deletion';form.scrollIntoView({block:'center',behavior:'smooth'});form.elements.note.focus();};});
 }
 let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;accountRequests();});}).observe(document.querySelector('#app'),{childList:true,subtree:true});
 accountRequests();
})();
