'use strict';
const directoryKinds=[['shop','متاجر'],['restaurant','مطاعم ومقاهٍ'],['doctor','أطباء وعيادات'],['pharmacy','صيدليات'],['services','مهن وخدمات'],['school','مدارس'],['mosque','مساجد'],['lawyer','محامون']];
function directoryKind(s){const saved=s.translations?._directory?.kind;if(saved)return saved;const t=s.name+' '+s.description;if(/صيدل/.test(t))return 'pharmacy';if(/طبيب|عيادة|دكتور/.test(t))return 'doctor';if(/محام/.test(t))return 'lawyer';if(/مدرسة|مدارس/.test(t))return 'school';if(/مسجد|جامع/.test(t))return 'mosque';return s.text_only?'services':s.category;}
function directoryIsInfo(s){return s.translations?._directory?.mode==='info';}
function directoryPagePayload(f,s){if(!f.has('page_mode'))return {};return f.get('page_mode')==='info'?{online_ordering:false,delivery_enabled:false,pickup_enabled:false,text_only:true}:{text_only:f.get('directory_kind')==='services'};}
const directoryReadTranslations=readTranslations;
readTranslations=function(f,s,fields){const result=directoryReadTranslations(f,s,fields);if(f.has('page_mode'))result._directory={...(result._directory||{}),mode:f.get('page_mode'),kind:f.get('directory_kind')||directoryKind(s)};return result;};
function directoryFields(s){return '<section class="span2 panel"><h3>نوع الصفحة وتصنيف المكان</h3><label>نوع الصفحة<select name="page_mode"><option value="info" '+(!s.id||directoryIsInfo(s)?'selected':'')+'>صفحة تعريفية — عنوان وتواصل</option><option value="business" '+(s.id&&!directoryIsInfo(s)?'selected':'')+'>صفحة تجارية أو خدمية — منتجات وخدمات</option></select></label><p class="field-hint">يمكن تطوير الصفحة نفسها لاحقاً دون تغيير رابطها أو فقد بياناتها. استقبال الطلبات خيار مستقل.</p><label>تصنيف المكان<select name="directory_kind">'+directoryKinds.map(([k,l])=>'<option value="'+k+'" '+(directoryKind(s)===k?'selected':'')+'>'+l+'</option>').join('')+'</select></label></section>';}
function directoryBindForm(form,s){
 form.insertAdjacentHTML('afterbegin',directoryFields(s));
 for(const [name,label] of [['name','اسم المكان'],['description','وصف المكان والخدمات'],['address','العنوان الوصفي'],['contact_phone','رقم التواصل']]){const el=form.elements[name];if(el){const node=el.closest('label');if(node?.firstChild?.nodeType===3)node.firstChild.textContent=label;}}
 if(form.elements.category)form.elements.category.closest('label').hidden=true;
 if(!form.elements.contact_phone)form.querySelector('.form-grid').insertAdjacentHTML('beforeend',field('رقم التواصل','contact_phone',s.contact_phone||'','tel','maxlength="30"'));
 const sync=()=>{const info=form.elements.page_mode.value==='info';if(form.elements.category)form.elements.category.value=form.elements.directory_kind.value==='restaurant'?'restaurant':'shop';
 for(const name of ['delivery_fee','minimum_order','delivery_time','areas','is_open']){const el=form.elements[name];if(el){el.closest('label').hidden=info;if(info)el.required=false;}}
 form.querySelector('.service-options')?.toggleAttribute('hidden',info);
 if(info&&form.elements.online_ordering){form.elements.online_ordering.checked=false;form.elements.delivery_enabled.checked=false;form.elements.pickup_enabled.checked=false;form.elements.online_ordering.dispatchEvent(new Event('change'));}
 };
 form.elements.page_mode.onchange=sync;form.elements.directory_kind.onchange=sync;sync();
 if(form.elements.latitude){const el=form.querySelector('.store-location-editor');el.insertAdjacentHTML('afterbegin','<label>رابط GPS بإحداثيات واضحة<input name="gps_link" type="url" placeholder="https://www.google.com/maps?q=33.458,36.236"><small>يدعم رابطاً يحتوي الإحداثيات. للرابط المختصر استخدم تحديد الموقع على الخريطة.</small></label><p data-gps-link-status role="status"></p>');
 form.elements.gps_link.onchange=e=>{const raw=e.target.value;const match=raw.match(/(?:@|[?&](?:q|query|ll)=)(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/);const status=form.querySelector('[data-gps-link-status]');if(!raw){status.textContent='';e.target.setCustomValidity('');return;}const point=match&&storeCoordinates({latitude:match[1],longitude:match[2]});if(point){form.elements.latitude.value=point[0];form.elements.longitude.value=point[1];status.textContent='تم استخراج الموقع. راجعه على الخريطة قبل الحفظ.';e.target.setCustomValidity('');}else{status.textContent='هذا الرابط لا يحتوي إحداثيات واضحة. حدد الموقع بالخريطة أو GPS.';e.target.setCustomValidity('حدد الموقع بالخريطة أو أدخل رابطاً بإحداثيات واضحة');}};}
}
const directoryEditStore=editStore;editStore=function(s={}){directoryEditStore(s);directoryBindForm($('#edit-form'),s);};
const directoryMerchantEditor=merchantEditor;merchantEditor=function(s,section){directoryMerchantEditor(s,section);if(section==='details')directoryBindForm($('#merchant-editor'),s);};
const directoryMatchesCategory=matchesCategory;matchesCategory=function(s,key=filter){if(directoryKinds.some(x=>x[0]===key))return directoryKind(s)===key;return directoryMatchesCategory(s,key);};
const directoryMatchesStore=matchesStore;matchesStore=function(s,term){return directoryMatchesStore(s,term)||((s.address||'')+' '+(directoryKinds.find(x=>x[0]===directoryKind(s))?.[1]||'')).toLowerCase().includes(term);};
const directoryRenderHome=renderHome;renderHome=function(){directoryRenderHome();const filters=$('.filters');if(!filters)return;for(const [key,label] of directoryKinds){let b=filters.querySelector('[data-filter="'+key+'"]');if(!b){b=document.createElement('button');b.dataset.filter=key;filters.insertBefore(b,filters.querySelector('.search-wrap'));b.onclick=()=>{filter=key;renderHome();};}b.textContent=label;b.classList.toggle('selected',filter===key);}
 document.querySelectorAll('.card').forEach(card=>{const id=card.querySelector('a').hash.split('/')[1],s=stores.find(x=>x.id===id);if(!s)return;const label=directoryKinds.find(x=>x[0]===directoryKind(s))?.[1]||'مكان';card.querySelector('.card-category').textContent=label+' · داريا';if(directoryIsInfo(s)){card.querySelector('.card-details').textContent=s.address||'العنوان قيد الإضافة';card.querySelector('.card-bottom').innerHTML='<span>صفحة تعريفية</span><strong>العنوان والتواصل ←</strong>';card.querySelector('[data-store-status]')?.remove();}});
};
const directoryRenderStore=renderStore;renderStore=function(id){directoryRenderStore(id);const s=stores.find(x=>x.id===id&&x.active);if(!s)return;const banner=$('.store-banner>div');if(!banner)return;
 if(directoryIsInfo(s)){document.querySelector('.store-layout')?.remove();banner.querySelector('.meta')?.remove();banner.querySelector('[data-store-status]')?.remove();banner.querySelectorAll(':scope>.tag').forEach(x=>x.remove());}
 const point=storeCoordinates(s);const directions=point?'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(point.join(',')):'';
 banner.insertAdjacentHTML('beforeend','<div class="directory-actions">'+(directions?'<a class="button" href="'+directions+'" target="_blank" rel="noopener noreferrer">الاتجاهات</a>':'')+(s.contact_phone?'<a class="button outline" href="tel:'+esc(s.contact_phone)+'">اتصال</a>':'')+'<button class="outline" data-report-place>أبلغ عن خطأ</button></div>');
 banner.querySelector('[data-report-place]').onclick=()=>{modal('<h2>الإبلاغ عن معلومات غير صحيحة</h2><p>'+esc(s.name)+'</p><form id="place-report"><label>ما المعلومات التي تحتاج تصحيحاً؟<textarea name="note" required maxlength="1000"></textarea></label><button type="submit">فتح البريد لإرسال البلاغ</button><p class="field-hint">يفتح تطبيق بريدك. راجع الرسالة واضغط إرسال لتصل إلى الإدارة.</p></form>');$('#place-report').onsubmit=e=>{e.preventDefault();const note=new FormData(e.target).get('note');location.href='mailto:info@damascus-shop.com?subject='+encodeURIComponent('تصحيح معلومات: '+s.name)+'&body='+encodeURIComponent('المكان: '+s.name+'\nالرابط: https://damascus-shop.com/#store/'+s.id+'\nالتصحيح المطلوب:\n'+note);};};
 if(user&&mine().some(x=>x.id===id)){document.querySelectorAll('[data-add]').forEach(x=>x.remove());$('#cart')?.remove();}
};
const directoryMerchantOverview=merchantOverview;merchantOverview=function(s,tasks){directoryMerchantOverview(s,tasks);if(!directoryIsInfo(s))return;$('.reception')?.remove();$('.merchant-metrics')?.remove();const welcome=$('.welcome-panel');welcome.querySelector('h2').textContent='صفحتك التعريفية';welcome.querySelector('p').textContent='حدّث الصورة والعنوان والتواصل. يمكنك تطوير هذه الصفحة نفسها إلى تجارية أو خدمية من معلومات المكان.';welcome.querySelector('.welcome-actions').innerHTML='<a class="button" href="'+merchantHref('details',s)+'">تعديل المعلومات أو تطوير الصفحة</a><a class="button merchant-preview" href="#store/'+s.id+'">معاينة الصفحة ↗</a>';};

const directoryMerchantDashboard=merchantDashboard;merchantDashboard=function(ms,s,section){directoryMerchantDashboard(ms,s,section);if(!s||!directoryIsInfo(s))return;document.querySelectorAll('.merchant-nav a').forEach(a=>{if(['products','orders','delivery'].some(key=>a.getAttribute('href')===merchantHref(key,s)))a.hidden=true;});};
