'use strict';
function isCodeDriver(){return user?.app_metadata?.driver_code_only===true;}
function normalizeDriverCode(value){const s=String(value||'').trim().replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/[\s-]/g,'');if(!/^\d{12}$/.test(s))throw Error('أدخل رمز مندوب التوصيل المكوّن من 12 رقماً');return s;}
async function driverCodeIdentity(code){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(code));return Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('')+'@driver.damascus-shop.invalid';}
async function invokeDriverCode(body){const {data,error}=await api.functions.invoke('driver-code',{body});if(error){let message='تعذر إنشاء رمز مندوب التوصيل. تحقق من اتصالك وجلسة الدخول.';try{const response=await error.context?.json();if(response?.error)message=response.error;}catch{}throw Error(message);}if(!data?.code&&!data?.deleted)throw Error('تعذر تأكيد إنشاء الرمز');return data;}
function showDriverCode(data){const grouped=data.code.match(/.{1,4}/g).join(' ');modal(`<h2>رمز دخول ${esc(data.name)}</h2><p>سلّم الرمز للمندوب بشكل خاص. يفتح الموقع ويختار «دخول مندوب التوصيل»، ثم يكتب الرمز فقط.</p><label>رمز الدخول<input id="generated-driver-code" value="${esc(grouped)}" readonly dir="ltr" class="driver-code-value"></label><p class="muted">الرمز ثابت ويعمل في الدخول القادم أيضاً. يمكن لصاحب المحل أو الإدارة عرضه لاحقاً من زر «عرض رمز الدخول». إنشاء رمز جديد يلغي القديم.</p><div class="form-actions"><button id="copy-driver-code">نسخ الرمز</button><button class="outline" id="close-driver-code">تم</button></div><p id="copy-driver-code-status" role="status"></p>`);$('#copy-driver-code').onclick=async()=>{try{await navigator.clipboard.writeText(data.code);$('#copy-driver-code-status').textContent='تم نسخ الرمز';}catch{$('#generated-driver-code').select();$('#copy-driver-code-status').textContent='حدد الرمز وانسخه يدوياً';}};$('#close-driver-code').onclick=()=>$('#modal').close();}
async function issueDriverCode(body,button,status){if(button.disabled)return;button.disabled=true;try{const data=await invokeDriverCode(body);await reload();render();showDriverCode(data);}catch(err){if(status?.isConnected)status.textContent=err.message;else toast(err.message);if(button.isConnected)button.disabled=false;}}
function confirmNewDriverCode(d){modal(`<h2>${d.user_id?'استبدال دخول':'إنشاء رمز دخول'} ${esc(d.name)}</h2><p>سيصبح دخول هذا مندوب التوصيل برمز فقط. ${d.user_id?'يتوقف وصول حسابه السابق إلى مهام هذا مندوب التوصيل فور إنشاء الرمز الجديد.':''}</p><button id="confirm-new-driver-code">إنشاء الرمز</button><p id="new-driver-code-status" role="alert"></p>`);$('#confirm-new-driver-code').onclick=e=>issueDriverCode({driver_id:d.id},e.currentTarget,$('#new-driver-code-status'));}
async function viewDeliveryDriverCode(d,button){button.disabled=true;try{showDriverCode(await invokeDriverCode({driver_id:d.id,action:'view'}));}catch(err){toast(err.message);}finally{if(button.isConnected)button.disabled=false;}}
function confirmDeleteDeliveryDriver(d){modal(`<h2>حذف مندوب التوصيل ${esc(d.name)}</h2><p>سيختفي من فريق التوصيل ويتوقف وصوله إلى المهام. يبقى سجل الطلبات السابقة، وستحتاج إعادة تعيين طلباته الجارية لمندوب توصيل آخر.</p><div class="form-actions"><button id="confirm-delete-delivery-driver">حذف مندوب التوصيل</button><button class="outline" id="cancel-delete-delivery-driver">إلغاء</button></div><p id="delete-delivery-driver-status" role="alert"></p>`);$('#cancel-delete-delivery-driver').onclick=()=>$('#modal').close();$('#confirm-delete-delivery-driver').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{await invokeDriverCode({driver_id:d.id,action:'delete'});$('#modal').close();await reload();render();toast('تم حذف مندوب التوصيل');}catch(err){$('#delete-delivery-driver-status').textContent=err.message;b.disabled=false;}};}
const codeMerchantDrivers=merchantDrivers;merchantDrivers=function(s){
 codeMerchantDrivers.apply(this,arguments);const root=$('#dashboard-content'),form=$('#add-driver');if(!root||!form)return;
 const intro=root.querySelector('.panel>p');if(intro&&!s.platform)intro.textContent='أضف اسم مندوب التوصيل ورقمه وأنشئ رمز دخوله. لا يحتاج بريداً إلكترونياً أو إنشاء حساب بنفسه.';
 const email=form.elements.email;email.closest('label').hidden=true;email.required=false;
 const button=form.querySelector('button[type="submit"]');button.textContent='إضافة مندوب التوصيل وإنشاء رمز الدخول';
 form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);const storeId=s.platform?($('#new-driver-type').value==='platform'?null:$('#new-driver-store').value):s.id;if(s.platform&&$('#new-driver-type').value==='store'&&!storeId){$('#driver-form-error').textContent='اختر المحل المرتبط بمندوب التوصيل';return;}issueDriverCode({store_id:storeId,name:f.get('name'),phone:f.get('phone')},e.submitter,$('#driver-form-error'));};
 root.querySelectorAll('.driver-card').forEach(card=>{const id=card.querySelector('[data-toggle-driver]')?.dataset.toggleDriver,d=storeDrivers.find(x=>x.id===id);if(!d)return;const isCode=d.email.endsWith('@driver.damascus-shop.invalid');if(isCode){const identity=card.querySelector('p>bdi');if(identity)identity.textContent='الدخول برمز مندوب التوصيل';}const actions=card.querySelector('.form-actions');if(isCode){const view=document.createElement('button');view.type='button';view.className='outline';view.textContent='عرض رمز الدخول';view.onclick=()=>viewDeliveryDriverCode(d,view);actions?.append(view);}const remove=document.createElement('button');remove.type='button';remove.className='outline';remove.textContent='حذف مندوب التوصيل';remove.onclick=()=>confirmDeleteDeliveryDriver(d);actions?.append(remove);if(d.active){const b=document.createElement('button');b.type='button';b.className='outline';b.textContent=isCode?'إنشاء رمز جديد':'إنشاء رمز دخول';b.onclick=()=>confirmNewDriverCode(d);card.querySelector('.form-actions')?.prepend(b);}});
 const panels=root.querySelectorAll('.panel');panels[0]?.querySelectorAll('p').forEach(p=>{if(p.textContent.includes('أضف مندوب التوصيل وأرسل له رابط الدعوة'))p.textContent='أضف مندوب التوصيل وأنشئ رمز دخوله. لا يحتاج بريداً إلكترونياً أو قبول دعوة.';});panels[1]?.querySelectorAll('p').forEach(p=>{if(p.textContent.includes('بعد قبول الدعوة'))p.textContent='بعد إنشاء رمز مندوب التوصيل يمكنك تعيين الطلبات له مباشرة. إيقاف مندوب التوصيل يمنع وصوله إلى مهامه، حتى لو كان مسجلاً للدخول.';});
};
function renderDriverCodeLogin(){
 $('#app').classList.remove('professional-home','admin-layout');$('#app').innerHTML='<section class="panel customer-auth"><span class="eyebrow">فريق التوصيل</span><h1>دخول مندوب التوصيل</h1><p>أدخل الرمز الذي أعطاك إياه صاحب المحل أو إدارة الموقع.</p><form id="driver-code-login"><label>رمز مندوب التوصيل<input name="code" type="password" inputmode="numeric" required maxlength="30" autocomplete="current-password" dir="ltr" placeholder="رمز من 12 رقماً"></label><button class="full" type="submit">فتح مهام التوصيل</button><p id="driver-code-login-status" role="alert"></p></form><div class="form-actions"><a href="#driver/email">الدخول بحساب مندوب التوصيل قديم</a><a href="#home">العودة للمتاجر</a></div></section>';
 $('#driver-code-login').onsubmit=async e=>{e.preventDefault();if(customerAuthPending)return;let code;try{code=normalizeDriverCode(new FormData(e.target).get('code'));}catch(err){$('#driver-code-login-status').textContent=err.message;return;}const b=e.submitter;b.disabled=true;customerAuthPending=true;
 try{const email=await driverCodeIdentity(code),r=await api.auth.signInWithPassword({email,password:code});if(r.error)throw r.error;if(r.data.user?.app_metadata?.driver_code_only!==true){await api.auth.signOut();throw Error('الحساب ليس حساب مندوب التوصيل');}e.target.reset();user=r.data.user;sessionStorage.removeItem('daraya-driver-invite');await reload();location.hash='driver';render();}catch(err){if($('#driver-code-login-status'))$('#driver-code-login-status').textContent=/rate|too many/i.test(err.message||'')?'محاولات كثيرة. انتظر قليلاً ثم حاول مجدداً.':'الرمز غير صحيح أو لم يعد متاحاً. اطلب الرمز الحالي من صاحب المحل.';if(b.isConnected)b.disabled=false;}finally{code='';customerAuthPending=false;}}
}
const codeDriverDashboard=renderDriverDashboard;renderDriverDashboard=async function(){if(!user){if(location.hash==='#driver/email'){renderCustomerAuth();return;}renderDriverCodeLogin();return;}const uid=user.id;await codeDriverDashboard.apply(this,arguments);if(user?.id!==uid||!isCodeDriver())return;const link=document.querySelector('.driver-dashboard>a[href="#account"]');if(link){const b=document.createElement('button');b.className='outline';b.textContent='تسجيل الخروج';b.onclick=customerSignOut;link.replaceWith(b);}};
function applyDriverWorkspace(){
 const only=isCodeDriver();document.body.classList.toggle('driver-only-workspace',only);
 let entry=$('#driver-code-entry');if(!entry){entry=document.createElement('a');entry.id='driver-code-entry';entry.href='#driver';entry.textContent='دخول مندوب التوصيل';$('#site-menu')?.append(entry);}entry.hidden=!!user;
 let logout=$('#driver-code-signout');if(!logout){logout=document.createElement('button');logout.id='driver-code-signout';logout.textContent='تسجيل الخروج';logout.onclick=customerSignOut;$('#site-menu')?.append(logout);}logout.hidden=!only;
}
const codeDriversRender=render;render=function(){applyDriverWorkspace();if(api&&isCodeDriver()&&!passwordRecovery&&!location.hash.startsWith('#driver')){history.replaceState(null,'','#driver');}if(api&&isCodeDriver()&&!passwordRecovery){$('#account').hidden=true;$('#dashboard-link').hidden=true;clearInterval(trackingTimer);renderDriverDashboard();return;}codeDriversRender();};
window.removeEventListener('hashchange',codeDriversRender);window.addEventListener('hashchange',render);
