'use strict';
function marketText(text){return window.ShahinI18n?.translate(text)||text;}
// Values submitted to SQL stay in Arabic/original form; only visible labels translate.
function normalizeMarketPhone(value,optional=false){let n=String(value||'').trim().replace(/[٠-٩۰-۹]/g,c=>String(c.charCodeAt(0)-(c>='۰'?'۰':'٠').charCodeAt(0))).replace(/[\s().-]/g,'');if(!n&&optional)return '';if(n.startsWith('00'))n='+'+n.slice(2);if(/^09\d{8}$/.test(n))n='+963'+n.slice(1);if(/^9639\d{8}$/.test(n))n='+'+n;if(!/^\+[1-9]\d{7,14}$/.test(n))throw Error('أدخل رقماً صحيحاً: 09xxxxxxxx أو رقماً دولياً يبدأ بـ +');return n;}
function marketAddressParts(f){return Object.fromEntries(['street','building','floor','landmark'].map(k=>[k,String(f.get(k)||'').trim()]));}
function joinMarketAddress(p){return [p.street,p.building,p.floor?`الطابق ${p.floor}`:'',p.landmark].filter(Boolean).join('، ');}
function marketError(err){const msg=String(err?.message||'');if(/fetch|network|timeout|load failed/i.test(msg))return 'تعذر الاتصال. بياناتك باقية؛ تحقق من سجل مشترياتك ثم أعد المحاولة بنفس البيانات.';if(err?.code==='23505')return 'لديك طلب قيد المراجعة بالفعل.';if(/JWT|session|token.*expired/i.test(msg))return 'انتهت جلسة الدخول. سجل الدخول مجدداً؛ السلة محفوظة.';return msg||'تعذر الحفظ. بياناتك باقية، حاول مجدداً.';}
function stockVariantKey(options=[]){return options.map(o=>`${o.group}:${o.id}`).sort().join('|');}
function stockCombinations(groups){let rows=[{options:[],label:'المخزون العام'}];if(groups.some(g=>!g.required||g.multiple))throw Error('لتتبع المخزون اجعل المقاس واللون خيارات إلزامية واختياراً واحداً');for(const g of groups){rows=rows.flatMap(r=>g.options.map(o=>({options:[...r.options,{group:g.id,id:o.id}],label:(r.options.length?r.label+' · ':'')+g.name+': '+o.name})));if(rows.length>150)throw Error('الحد الأقصى 150 تركيبة للمقاسات والألوان');}return rows;}
function availableMarketStock(p,options=[]){if(!p||!p.stock_tracking)return Infinity;return (p.stock_rows||[]).find(r=>r.variant_key===stockVariantKey(options))?.stock||0;}
const marketDirtyForms=new WeakSet();let marketDirtySet=new Set();
function marketCleanForm(form){if(form){marketDirtyForms.delete(form);marketDirtySet.delete(form);form.querySelector('[data-save-state]')?.remove();}}
function marketHasDirty(){return [...marketDirtySet].some(f=>f.isConnected&&marketDirtyForms.has(f));}
function marketDiscard(){for(const f of marketDirtySet)marketCleanForm(f);marketDirtySet.clear();}
function marketConfirmLeave(){if(!marketHasDirty())return true;if(busy){toast('انتظر اكتمال الحفظ');return false;}if(!confirm(marketText('لديك تغييرات غير محفوظة. هل تريد مغادرة الصفحة؟')))return false;marketDiscard();return true;}
function marketTrackChanges(e){const f=e.target.closest('form');if(!f||!['edit-form','merchant-editor','customer-profile-form','order-form'].includes(f.id))return;marketDirtyForms.add(f);marketDirtySet.add(f);if(!f.querySelector('[data-save-state]'))f.insertAdjacentHTML('beforeend','<p data-save-state role="status" class="save-state">تغييرات غير محفوظة</p>');}
document.addEventListener('input',marketTrackChanges);document.addEventListener('change',marketTrackChanges);
document.addEventListener('click',e=>{const button=e.target.closest('button');if(button&&button.id!=='close-modal'&&!button.closest('form')&&marketHasDirty()&&!marketConfirmLeave()){e.preventDefault();e.stopImmediatePropagation();return;}const a=e.target.closest('a[href]');if(a&&!a.hasAttribute('download')&&a.getAttribute('href')!==location.hash&&!marketConfirmLeave()){e.preventDefault();e.stopImmediatePropagation();}},true);
window.addEventListener('beforeunload',e=>{if(marketHasDirty()||busy){e.preventDefault();e.returnValue='';}});
const marketModal=modal;modal=function(html){marketDiscard();marketModal(html);};
$('#close-modal').onclick=()=>{if(marketConfirmLeave())$('#modal').close();};
$('#modal').addEventListener('cancel',e=>{if(!marketConfirmLeave())e.preventDefault();});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')&&!marketConfirmLeave())e.stopImmediatePropagation();},true);
// Navigation through browser back/forward also asks before discarding a form.
let marketLastHash=location.hash,marketRestoreHash=false;
window.addEventListener('hashchange',e=>{if(marketRestoreHash){marketRestoreHash=false;e.stopImmediatePropagation();return;}if(marketHasDirty()&&!marketConfirmLeave()){e.stopImmediatePropagation();marketRestoreHash=true;location.hash=marketLastHash;return;}marketLastHash=location.hash;},true);
let marketPending=null;
function marketPendingKey(){return 'daraya-order-attempt:'+user?.id;}
function marketOrderRequest(form,s){const f=new FormData(form),data={store:s.id,uid:user.id,method:orderMethod(s),name:f.get('name'),phone:normalizeMarketPhone(f.get('phone')),address:f.get('address')||'',area:f.get('area')||'',notes:f.get('notes')||'',latitude:f.get('latitude')||'',longitude:f.get('longitude')||'',items:cartItems().map(p=>({id:p.id,quantity:p.quantity,options:p.options}))},signature=JSON.stringify(data);if(marketPending?.uid!==user.id)marketPending=null;try{const saved=JSON.parse(sessionStorage.getItem(marketPendingKey())||'null');if(saved)marketPending=saved;}catch{}if(marketPending&&marketPending.signature!==signature){throw Error('قد تكون المحاولة السابقة وصلت إلى المتجر. افتح سجل مشترياتك قبل تغيير بيانات الطلب أو إرسال طلب جديد.');}if(!marketPending){marketPending={uid:user.id,signature,id:crypto.randomUUID()};try{sessionStorage.setItem(marketPendingKey(),JSON.stringify(marketPending));}catch{}}return marketPending.id;}
function marketOrderCompleted(){try{sessionStorage.removeItem(marketPendingKey());}catch{}marketPending=null;}
function marketOrderRejected(error){if(error?.code&&error.code!=='PGRST000')marketOrderCompleted();}
// Stage progress reflects actual compression/upload stages, not fabricated byte counts.
async function compressMarketImage(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>1572864)throw Error('اختر JPG أو PNG أو WebP بحجم لا يتجاوز ١٫٥ ميغابايت');let bitmap;try{bitmap=await createImageBitmap(file);}catch{const url=URL.createObjectURL(file);try{bitmap=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('تعذر قراءة الصورة'));img.src=url;});}finally{URL.revokeObjectURL(url);}}const scale=Math.min(1,400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();let blob;for(const quality of [.65,.5,.35,.2]){blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',quality));if(blob&&blob.size<=65536)break;}if(!blob||blob.size>65536)throw Error('تعذر تصغير الصورة. اختر صورة أصغر.');return blob;}
const marketUploadOriginal=uploadOrLink;
uploadOrLink=async function(f,sid){const file=f.get('photo');if(!file?.size)return marketUploadOriginal(f,sid);const host=$('#edit-form')||$('#merchant-editor');let status=host?.querySelector('.upload-state');if(!status&&host){host.insertAdjacentHTML('beforeend','<div class="upload-state" role="status"><progress max="3" value="1"></progress><span>جاري إنشاء الصورة المصغّرة…</span></div>');status=host.querySelector('.upload-state');}const root=`${sid}/${crypto.randomUUID()}`,extension={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type],originalKey=root+'/original.'+extension,thumbKey=root+'/thumbnail.webp';try{const thumbnail=await compressMarketImage(file);if(status){status.querySelector('progress').value=2;status.querySelector('span').textContent='جاري رفع الصورة الأصلية والمصغّرة…';}const bucket=api.storage.from('store-images');for(const [key,data] of [[originalKey,file],[thumbKey,thumbnail]]){const r=await bucket.upload(key,data,{contentType:data.type,cacheControl:'31536000',upsert:false});if(r.error)throw r.error;}const result=bucket.getPublicUrl(originalKey).data.publicUrl;if(status){status.querySelector('progress').value=3;status.querySelector('span').textContent='تم حفظ الصورة الأصلية والمصغّرة';}return result;}catch(err){try{await api.storage.from('store-images').remove([originalKey,thumbKey]);}catch{}if(status)status.querySelector('span').textContent=marketError(err);throw err;}};

const marketReload=reload;reload=async function(){await marketReload();const ids=products.filter(p=>p.stock_tracking||mine().some(s=>s.id===p.store_id)).map(p=>p.id);if(ids.length){const r=await api.from('product_stock').select('product_id,variant_key,options,stock,revision').in('product_id',ids);if(r.error)throw r.error;for(const p of products)p.stock_rows=(r.data||[]).filter(v=>v.product_id===p.id);}else for(const p of products)p.stock_rows=[];};
const marketAddLine=addLine;addLine=function(p,options){const remaining=availableMarketStock(p,options),key=lineKey(p.id,options);if((cart[key]?.quantity||0)+1>remaining){toast('الكمية أو المقاس المختار لم يعد متوفراً. عدّل السلة وحاول مجدداً.');return;}marketAddLine(p,options);};
const marketAdd=add;add=function(id){marketAdd(id);const p=products.find(p=>p.id===id),form=$('#options-form');if(!p?.stock_tracking||!form)return;form.insertAdjacentHTML('beforeend','<p id="variant-stock-status" class="stock-status" role="status"></p>');const update=()=>{const choices=[...form.querySelectorAll('input:checked')].map(el=>({group:el.name,id:el.value}));try{if(selectionPrice(p,choices)===null)throw Error('incomplete');const count=availableMarketStock(p,choices);$('#variant-stock-status').textContent=count>0?'متوفر: '+count:'هذه التركيبة غير متوفرة';form.querySelector('[type="submit"]').disabled=count<=0;}catch{$('#variant-stock-status').textContent='اختر المقاس واللون لعرض الكمية';}};form.addEventListener('change',update);update();};
let marketStockContext=null;
function renderMarketStock(rows,existing=[]){return rows.map(r=>{const old=existing.find(v=>v.variant_key===stockVariantKey(r.options));return `<label class="stock-row"><span>${esc(r.label)}</span><input data-stock-key="${esc(stockVariantKey(r.options))}" data-stock-options="${esc(JSON.stringify(r.options))}" data-stock-revision="${old?.revision||0}" type="number" min="0" max="1000000" step="1" required value="${old?.stock||0}" aria-label="${esc(r.label)}"></label>`;}).join('');}
function readMarketStock(groups){const enabled=$('#edit-form')?.elements.stock_tracking?.checked;if(!enabled)return [];const expected=stockCombinations(groups);return expected.map(r=>{const input=[...document.querySelectorAll('[data-stock-key]')].find(x=>x.dataset.stockKey===stockVariantKey(r.options));if(!input)throw Error('أعد إنشاء جدول المخزون بعد تعديل الخيارات');const n=Number(input.value);if(!Number.isInteger(n)||n<0||n>1000000)throw Error('أدخل كمية صحيحة للمخزون');return {options:r.options,stock:n,revision:Number(input.dataset.stockRevision)};});}
const marketEditProduct=editProduct;editProduct=function(s,p={}){marketStockContext=p;marketEditProduct(s,p);const form=$('#edit-form');form.querySelector('#groups-editor').insertAdjacentHTML('afterend',`<details class="stock-editor" ${p.stock_tracking?'open':''}><summary>المقاسات والألوان والمخزون</summary><p>أضف مجموعة للمقاس وأخرى للون، واجعلهما إلزاميتين مع اختيار واحد. ثم حدّد الكمية لكل تركيبة. صفر يعني نفاد المخزون.</p><label><input type="checkbox" name="stock_tracking" ${p.stock_tracking?'checked':''}>تتبع مخزون هذا المنتج</label><button type="button" id="build-stock" class="outline">إنشاء / تحديث جدول المخزون</button><div id="stock-grid"></div><p id="stock-editor-error" role="alert"></p></details>`);const rebuild=()=>{try{const current=[...form.querySelectorAll('[data-stock-key]')].map(x=>({variant_key:x.dataset.stockKey,stock:Number(x.value),revision:Number(x.dataset.stockRevision)}));$('#stock-grid').innerHTML=renderMarketStock(stockCombinations(readGroups()),current.length?current:p.stock_rows||[]);$('#stock-editor-error').textContent='';}catch(err){$('#stock-editor-error').textContent=marketError(err);}};$('#build-stock').onclick=rebuild;form.elements.stock_tracking.onchange=()=>{if(form.elements.stock_tracking.checked)rebuild();else $('#stock-grid').innerHTML='';};if(p.stock_tracking)rebuild();addMerchantFormHelp(form,s,'products');};
const marketEditor=merchantEditor;merchantEditor=function(s,section){marketEditor(s,section);const form=$('#merchant-editor');if(form)addMerchantFormHelp(form,s,section);};
const marketDashboard=merchantDashboard;merchantDashboard=function(ms,s,section){marketDashboard(ms,s,section);if(!s)return;const actions=$('.merchant-actions');actions?.insertAdjacentHTML('beforeend',`<a class="button outline" href="#merchant-help/${s.id||''}">دليل صاحب المتجر</a>`);};
function addMerchantFormHelp(form,s,section){form.insertAdjacentHTML('afterbegin',`<aside class="form-help"><a href="#merchant-help/${s.id||''}">دليل صاحب المتجر</a><span>${section==='hours'?'إيقاف استقبال الطلبات لا يغيّر حالة فتح المتجر بحسب الدوام.':section==='products'?'الأسعار بالليرة السورية. اكتب اسم المنتج ووصفه ثم احفظ.':'راجع البيانات ثم احفظ. ستظهر التعديلات للزبائن بعد نجاح الحفظ.'}</span></aside>`);form.querySelectorAll('input[name="price"],input[name="delivery_fee"],input[name="minimum_order"]').forEach(input=>input.addEventListener('change',()=>{const limit=input.name==='delivery_fee'?100000:5000000;if(Number(input.value)>limit&&!confirm(marketText('المبلغ كبير. هل تقصد هذه القيمة بالليرة السورية؟'))){input.value=input.defaultValue;}}));}
function addMarketAddressFields(form,parts={}){const address=form.elements.address;if(!address)return;address.parentElement.insertAdjacentHTML('beforebegin',`<div class="span2 address-parts"><h3>عنوان يسهل الوصول إليه</h3><div class="form-grid">${field('الشارع','street',parts.street||'','text','maxlength="100"')}${field('البناء','building',parts.building||'','text','maxlength="80"')}${field('الطابق','floor',parts.floor||'','text','maxlength="20"')}${field('علامة قريبة','landmark',parts.landmark||'','text','maxlength="100"')}</div><small>يمكنك استخدام الحقول أو كتابة العنوان بالتفصيل أدناه.</small></div>`);const update=()=>{const p=marketAddressParts(new FormData(form));const joined=joinMarketAddress(p);if(joined)address.value=joined;};for(const k of ['street','building','floor','landmark'])form.elements[k].addEventListener('input',update);address.addEventListener('input',()=>{for(const k of ['street','building','floor','landmark'])form.elements[k].value='';});}
const marketCheckout=checkout;checkout=function(s){marketCheckout(s);const form=$('#order-form');if(!form)return;addMarketAddressFields(form,customerProfile?.address_parts);try{const pending=JSON.parse(sessionStorage.getItem(marketPendingKey())||'null');if(pending){const data=JSON.parse(pending.signature);if(data.store===s.id&&data.method===orderMethod(s)){for(const k of ['name','phone','address','area','notes','latitude','longitude'])if(form.elements[k])form.elements[k].value=data[k]||'';form.insertAdjacentHTML('afterbegin','<p class="alert">هناك محاولة طلب لم يتم تأكيد نتيجتها. أعد إرسالها بنفس البيانات أو راجع سجل مشترياتك.</p>');}}}catch{}form.querySelector('[type="submit"]').insertAdjacentHTML('beforebegin','<p class="field-privacy">الهاتف والعنوان يساعدان متجر هذا الطلب على التواصل والتوصيل. لا يظهران للزوار. <a href="#privacy">خصوصية بياناتك</a></p>');form.elements.phone.addEventListener('blur',()=>{try{form.elements.phone.value=normalizeMarketPhone(form.elements.phone.value);form.elements.phone.setCustomValidity('');}catch(err){form.elements.phone.setCustomValidity(marketText(err.message));}});form.elements.phone.addEventListener('input',()=>form.elements.phone.setCustomValidity(''));};
const marketCustomerAccount=renderCustomerAccount;renderCustomerAccount=function(){marketCustomerAccount();const form=$('#customer-profile-form');if(!form)return;addMarketAddressFields(form,customerProfile?.address_parts);const submit=form.onsubmit;form.onsubmit=async e=>{try{e.target.elements.phone.value=normalizeMarketPhone(e.target.elements.phone.value,true);}catch(err){e.preventDefault();$('#customer-profile-status').textContent=err.message;return;}await submit(e);};form.insertAdjacentHTML('beforeend','<p class="field-privacy">العنوان اختياري في الحساب، ومطلوب عند اختيار التوصيل فقط. يمكن تغييره في كل طلب.</p>');form.closest('.customer-account').insertAdjacentHTML('beforeend','<div class="panel"><h2>إدارة بياناتك الشخصية</h2><p>يمكنك تصحيح بياناتك من النموذج أعلاه. لطلب مساعدة أو حذف الحساب، أرسل طلباً للإدارة.</p><form id="data-request-form"><label>نوع الطلب<select name="kind"><option value="correction">طلب تصحيح بيانات</option><option value="deletion">طلب حذف الحساب</option></select></label><label>ملاحظة<textarea name="note" maxlength="400"></textarea></label><p class="muted">إرسال الطلب لا يحذف الحساب فوراً. تراجعه الإدارة وتتواصل معك قبل التنفيذ.</p><button type="submit">إرسال طلب للإدارة</button><p id="data-request-status" role="status"></p></form></div>');$('#data-request-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const f=new FormData(e.target);const r=await api.from('customer_data_requests').insert({user_id:user.id,kind:f.get('kind'),note:f.get('note')});if(r.error)throw r.error;$('#data-request-status').textContent='وصل طلبك إلى الإدارة';}catch(err){$('#data-request-status').textContent=marketError(err);}finally{e.submitter.disabled=false;}};};
// A failed save leaves every field in place. Structured parts are saved together.
const marketSaveProfile=saveCustomerProfile;saveCustomerProfile=async function(profile){const form=$('#customer-profile-form');if(form&&profile.display_name===form.elements.display_name.value)profile.address_parts=marketAddressParts(new FormData(form));await marketSaveProfile(profile);if(form)marketCleanForm(form);};
const merchantHelpLessons=[
 ['details','ابدأ بمعلومات المتجر','اكتب الاسم والوصف والعنوان ورقم التواصل. استخدم عنواناً يستطيع الزبون الوصول إليه، ثم اضغط حفظ وراجع صفحة المتجر.'],
 ['photos','اختر صوراً واضحة','ارفع صورة الواجهة أو الشعار. يُصغّر الموقع صور JPG وPNG وWebP تلقائياً قبل رفعها. استخدم صوراً تملكها وتُظهر البضاعة الفعلية.'],
 ['products','أضف منتجاتك وأسعارها','اكتب الاسم والوصف والسعر بالليرة السورية، وضع صورة وقسماً مناسباً. تكلفة المنتج تظهر لصاحب المتجر في الحسابات. أوقف خيار متاح للطلب عند نفاد المنتج.'],
 ['products','نظّم المقاسات والألوان','أضف مجموعة للمقاس وأخرى للون. اجعل كل مجموعة إلزامية واختياراً واحداً، ثم فعّل تتبع المخزون وأنشئ جدول الكميات. أدخل كمية كل تركيبة؛ صفر يمنع طلبها.'],
 ['delivery','اضبط التوصيل والاستلام','يمكن عرض البضائع والعروض فقط بإيقاف البيع عبر الموقع. عند تفعيل البيع اختر التوصيل أو الاستلام أو كليهما. أدخل رسوم التوصيل والحد الأدنى والمناطق والمدة المتوقعة. الطلب يعرض الرسوم قبل الإرسال، والاستلام من المتجر بلا رسوم توصيل.'],
 ['hours','حدد الدوام والإغلاق المؤقت','اكتب أوقات كل يوم وفعّل الدوام التلقائي إذا أردت. إيقاف استقبال الطلبات يوقفها فوراً حتى أثناء الدوام؛ أعد تفعيله بعد الاستراحة.'],
 ['orders','تابع الطلب حتى التسليم','راجع المنتجات والمقاسات وعنوان الزبون وطريقة الاستلام. حدّث الحالة مع تقدم الطلب. إلغاء الطلب يعيد الكمية المحجوزة للمخزون، والطلبات السابقة تحتفظ بأسعارها الأصلية.'],
 ['reports','راجع حسابات متجرك','راجع المبيعات والطلبات المسلّمة ورسوم التوصيل والتكاليف. سجّل المصروفات والإيرادات اليدوية. لا تعتبر الطلب الملغي مبيعاً؛ راجع الفترة المحددة قبل حساب الأرباح.'],
 ['overview','حل مشكلات الحفظ','إذا انقطع الاتصال، تبقى الحقول في مكانها. أعد المحاولة. إذا ظهرت رسالة بأن البيانات أو المخزون تغيّرا، انسخ تعديلاتك وحدّث الصفحة قبل إعادة الحفظ. لا تغادر قبل ظهور نجاح الحفظ.']
];
function renderMerchantHelp(id){const s=stores.find(s=>s.id===id)||mine()[0];$('#app').innerHTML=`<section class="merchant-help"><div class="help-hero"><span class="section-kicker">خطوة بخطوة</span><h1>دليل صاحب المتجر</h1><p>من تجهيز صفحتك إلى متابعة طلباتك وحساباتك.</p>${s?`<a class="button" href="${merchantHref('overview',s)}">العودة إلى لوحة متجري</a>`:'<a class="button" href="#account">دخول / إنشاء حساب</a>'}</div><nav class="help-contents" aria-label="دروس المساعدة">${merchantHelpLessons.map((l,i)=>`<a href="#merchant-help/${s?.id||''}/lesson-${i}">${esc(l[1])}</a>`).join('')}</nav><div class="help-lessons">${merchantHelpLessons.map((l,i)=>`<article class="panel help-lesson" id="lesson-${i}"><span class="lesson-number">${String(i+1).padStart(2,'0')}</span><div><h2>${l[1]}</h2><p>${l[2]}</p>${s?`<a class="help-action" href="${merchantHref(l[0],s)}">فتح القسم في لوحة متجري ←</a>`:''}</div></article>`).join('')}</div></section>`;const lesson=location.hash.split('/')[2];if(lesson)document.getElementById(lesson)?.scrollIntoView({block:'start'});}
async function renderDataRequests(){if(!user||!admin){$('#app').innerHTML='<div class="panel">هذه الصفحة لإدارة المنصة.</div>';return;}$('#app').innerHTML='<section class="panel"><h1>طلبات البيانات الشخصية</h1><p>راجع الطلب وتواصل مع الزبون قبل تنفيذ حذف الحساب. لا يحذف زر المراجعة أي بيانات.</p><div id="data-requests-results" aria-live="polite">جاري التحميل…</div></section>';const host=$('#data-requests-results'),uid=user.id;try{const r=await api.from('customer_data_requests').select('*').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;if(user?.id!==uid||!admin||!host.isConnected)return;host.innerHTML=r.data.map(row=>`<article class="data-request"><h2>${row.kind==='deletion'?'طلب حذف الحساب':'طلب تصحيح بيانات'}</h2><p dir="ltr" data-no-translate>${esc(row.user_id)}</p><small>${new Date(row.created_at).toLocaleString('ar-SY')}</small><p>${esc(row.note)}</p><span>${row.status==='pending'?'قيد المراجعة':'تمت المراجعة'}</span>${row.status==='pending'?`<button data-review-request="${row.id}">وضع علامة تمت المراجعة</button>`:''}</article>`).join('')||'<p>لا توجد طلبات.</p>';host.querySelectorAll('[data-review-request]').forEach(b=>b.onclick=async()=>{b.disabled=true;const r=await api.from('customer_data_requests').update({status:'reviewed'}).eq('id',b.dataset.reviewRequest);if(r.error){toast(marketError(r.error));b.disabled=false;}else renderDataRequests();});}catch(err){if(host.isConnected)host.textContent=marketError(err);}}
const marketRenderDashboard=renderDashboard;renderDashboard=function(tab,sid){marketRenderDashboard(tab,sid);if(admin)$('.topline')?.insertAdjacentHTML('beforeend','<a class="button outline" href="#data-requests">طلبات البيانات الشخصية</a>');};
const marketRender=render;render=function(){if(location.hash.startsWith('#merchant-help')){updateCustomerNav();clearInterval(trackingTimer);$('#account').hidden=true;$('#dashboard-link').hidden=true;}if(location.hash.startsWith('#merchant-help')){renderMerchantHelp(location.hash.split('/')[1]);return;}if(location.hash==='#data-requests'){renderDataRequests();return;}marketRender();};window.removeEventListener('hashchange',marketRender);window.addEventListener('hashchange',render);
const marketRenderCart=renderCart;renderCart=function(s){marketRenderCart(s);if(!s)return;document.querySelectorAll('[data-plus]').forEach(b=>{const line=cart[b.dataset.plus],p=products.find(p=>p.id===line?.id);if(p&&line.quantity>=availableMarketStock(p,line.options)){b.disabled=true;b.title='الكمية المتاحة في المخزون';}});const invalid=cartItems().some(line=>line.quantity>availableMarketStock(products.find(p=>p.id===line.id),line.options));if(invalid&&$('#checkout')){$('#checkout').disabled=true;$('#checkout').insertAdjacentHTML('beforebegin','<p class="error">بعض الكميات لم تعد متوفرة. قلّل الكمية أو احذف المنتج.</p>');}};

const marketHistory=renderHistory;renderHistory=async function(){await marketHistory();if(!user)return;const uid=user.id;try{const pending=JSON.parse(sessionStorage.getItem(marketPendingKey())||'null');if(pending){const r=await api.rpc('market_attempt',{p_request:pending.id});if(user?.id===uid&&!r.error&&r.data)marketOrderCompleted();}}catch{}};

const marketEditStore=editStore;editStore=function(s={}){marketEditStore(s);const form=$('#edit-form');if(form)addMerchantFormHelp(form,s,'details');};
const marketReadTranslations=readTranslations;readTranslations=function(f,record,fields){const result=marketReadTranslations(f,record,fields);result._review=structuredClone(record.translations?._review||{en:[],de:[]});for(const lang of ['en','de']){const pending=new Set(result._review[lang]||[]);for(const key of fields){const original=f.get(key),translated=f.get(`i18n_${lang}_${key}`);if(original===null||translated===null)continue;const old=key==='areas'?(record.translations?.[lang]?.areas||[]).join('\n'):translatedDefault(record,key,lang);if(!String(translated).trim()||String(translated).trim()!==String(old).trim())pending.delete(key);else if(String(original).trim()!==String(Array.isArray(record[key])?record[key].join('، '):record[key]||'').trim())pending.add(key);}result._review[lang]=[...pending];}return result;};

const serviceCheckoutBase=checkout;checkout=function(s){if(!canStoreOrder(s)){toast(s?.online_ordering===false?'هذا المتجر لا يستقبل طلبات عبر الموقع':'المتجر مغلق أو استقبال الطلبات متوقف');return;}return serviceCheckoutBase(s);};


