'use strict';
(() => {
 const t=(ar,en,de)=>({ar,en,de}[window.ShahinI18n?.language||'ar']||ar);
 const productUrl=(s,p)=>'https://damascus-shop.com/#store/'+encodeURIComponent(s.id)+'/product/'+encodeURIComponent(p.id);
 const shareText=(s,p)=>[p.name+' — '+money(p.price),s.name,s.address?.trim(),s.contact_phone?.trim(),productUrl(s,p)].filter(Boolean).join('\n');
 async function shareProduct(s,p){const text=shareText(s,p);try{if(navigator.share){await navigator.share({title:p.name,text});return;}await navigator.clipboard.writeText(text);toast(t('تم نسخ تفاصيل المنتج ورابطه','Product details and link copied','Produktdetails und Link kopiert'));}catch(e){if(e.name==='AbortError')return;modal('<h2>'+t('مشاركة المنتج','Share product','Produkt teilen')+'</h2><p>'+t('انسخ النص وأرسله لمن تريد','Copy this text and send it','Text kopieren und senden')+'</p><textarea readonly rows="7" style="width:100%">'+esc(text)+'</textarea>');}}
 function qrModel(url){const box=document.createElement('div');const qr=new QRCode(box,{text:url,width:256,height:256,correctLevel:QRCode.CorrectLevel.M,useSVG:true});return qr._oQRCode;}
 function drawQr(ctx,url,x,y,size){const model=qrModel(url),n=model.getModuleCount(),scale=Math.floor(size/(n+8)),actual=scale*(n+8),left=x+(size-actual)/2,top=y+(size-actual)/2;ctx.fillStyle='#fff';ctx.fillRect(x,y,size,size);ctx.fillStyle='#111';for(let row=0;row<n;row++)for(let col=0;col<n;col++)if(model.isDark(row,col))ctx.fillRect(left+(col+4)*scale,top+(row+4)*scale,scale,scale);}
 function wrap(ctx,text,x,y,width,lineHeight,maxLines){const words=String(text).split(/\s+/);let lines=[],line='';for(const word of words){const next=line?line+' '+word:word;if(ctx.measureText(next).width>width&&line){lines.push(line);line=word;}else line=next;}if(line)lines.push(line);if(lines.length>maxLines){lines=lines.slice(0,maxLines);let last=lines[maxLines-1];while(last&&ctx.measureText(last+'…').width>width)last=last.slice(0,-1);lines[maxLines-1]=last+'…';}lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight,width));return lines.length*lineHeight;}
 async function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=()=>reject(Error(t('تعذر استخدام الصورة. اختر صورة من هاتفك ثم أعد التجهيز.','Could not use this photo. Choose a photo from your phone.','Das Foto konnte nicht verwendet werden. Wähle ein Foto vom Handy.')));img.src=src;});}
 async function makeImage(s,p,format,localImage,shopLogo){await document.fonts.ready;const poster=!p;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=poster?1440:format==='story'?1920:1080;const c=canvas.getContext('2d'),h=canvas.height;
 const rounded=(x,y,w,h,r,fill)=>{c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();c.fillStyle=fill;c.fill();};
 const logo=await loadImage(new URL('/daraya-mark-gold.webp',location.href).href);
 const fitted=(image,x,y,w,h)=>{const z=Math.min(w/image.naturalWidth,h/image.naturalHeight);c.drawImage(image,x+(w-image.naturalWidth*z)/2,y+(h-image.naturalHeight*z)/2,image.naturalWidth*z,image.naturalHeight*z);};
 c.fillStyle='#fffaf0';c.fillRect(0,0,1080,h);const header=poster?520:250;c.fillStyle='#173b35';c.fillRect(0,0,1080,header);c.fillStyle='#21483f';c.beginPath();c.arc(60,20,220,0,Math.PI*2);c.fill();c.fillStyle='#bf963c';c.beginPath();c.moveTo(780,header);c.lineTo(1080,header-90);c.lineTo(1080,header);c.closePath();c.fill();c.fillStyle='#efd787';c.fillRect(0,header,1080,8);
 c.textAlign='center';c.direction='rtl';c.fillStyle='#efd787';
 if(poster){
  if(shopLogo){const shopImg=await loadImage(shopLogo);rounded(400,40,280,280,32,'#fff');fitted(shopImg,420,60,240,240);}
  c.fillStyle='#efd787';c.font='bold 74px sans-serif';wrap(c,s.name,540,shopLogo?402:220,950,84,2);
  c.fillStyle='#173b35';c.font='bold 44px sans-serif';wrap(c,directoryIsInfo(s)?t('تعرّف على نشاطنا وموقعنا','Find our business and location','Unser Geschäft und unseren Standort ansehen'):t('بضاعتنا وأسعارنا بين يديك','Our products and prices at your fingertips','Unsere Produkte und Preise auf deinem Handy'),540,605,940,58,1);
  rounded(350,650,380,380,28,'#ead9ab');rounded(362,662,356,356,20,'#fff');drawQr(c,placePublicUrl(s),380,680,320);
  c.fillStyle='#88691e';c.font='bold 32px sans-serif';c.fillText(t('امسح الرمز وافتح صفحة المحل','Scan to open our shop page','Scannen und Geschäftsseite öffnen'),540,1080);
  c.fillStyle='#173b35';c.font='30px sans-serif';wrap(c,s.address||'',540,1140,920,42,2);
  if(s.contact_phone?.trim()){c.direction='ltr';c.font='bold 40px sans-serif';c.fillText(s.contact_phone.trim(),540,1250,940);}
  c.fillStyle='#173b35';c.fillRect(0,1325,1080,115);rounded(930,1340,80,80,12,'#fff');fitted(logo,939,1349,62,62);
  c.textAlign='center';c.direction='rtl';c.fillStyle='#fff';c.font='28px sans-serif';c.fillText('سوق داريا الإلكتروني',540,1366);c.direction='ltr';c.fillText('damascus-shop.com',540,1410);
  if(s.is_example){c.font='18px sans-serif';c.fillStyle='#efd787';c.textAlign='left';c.direction='rtl';c.fillText(t('متجر تجريبي — مثال','Example shop','Beispielgeschäft'),35,1410);}
  return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('PNG export failed')),'image/png'));
 }
 if(shopLogo){const shopImg=await loadImage(shopLogo);rounded(825,20,220,210,24,'#fff');fitted(shopImg,840,35,190,180);}
 c.fillStyle='#efd787';c.font='bold 60px sans-serif';wrap(c,s.name,shopLogo?420:540,110,shopLogo?740:960,72,2);
 const src=localImage||safeImage(p.image);if(!src)throw Error(t('أضف صورة للمنتج أو اختر صورة من هاتفك','Choose a product photo','Wähle ein Produktfoto'));const img=await loadImage(src);const photoTop=280,photoH=format==='story'?955:300,scale=Math.min(960/img.naturalWidth,photoH/img.naturalHeight),iw=img.naturalWidth*scale,ih=img.naturalHeight*scale;c.fillStyle='#fff';c.fillRect(60,photoTop,960,photoH);c.drawImage(img,(1080-iw)/2,photoTop+(photoH-ih)/2,iw,ih);
 let y=photoTop+photoH+58;c.fillStyle='#173b35';c.font='bold 42px sans-serif';y+=wrap(c,p.name,540,y,940,50,2);c.font='bold 52px sans-serif';c.fillStyle='#88691e';c.fillText(money(p.price),540,y+22);
 const contactTop=h-265;c.fillStyle='#173b35';c.font='28px sans-serif';c.direction='rtl';if(s.address?.trim())wrap(c,s.address.trim(),540,contactTop+35,900,36,2);if(s.contact_phone?.trim()){c.direction='ltr';c.font='bold 34px sans-serif';c.fillText(s.contact_phone.trim(),540,contactTop+120);}
 const footer=h-110;c.fillStyle='#173b35';c.fillRect(0,footer,1080,110);c.fillStyle='#fff';c.fillRect(950,footer+12,80,80);const ls=Math.min(68/logo.naturalWidth,68/logo.naturalHeight);c.drawImage(logo,990-logo.naturalWidth*ls/2,footer+52-logo.naturalHeight*ls/2,logo.naturalWidth*ls,logo.naturalHeight*ls);drawQr(c,productUrl(s,p),40,footer+10,90);c.textAlign='center';c.fillStyle='#fff';c.font='27px sans-serif';c.direction='rtl';c.fillText('سوق داريا الإلكتروني',540,footer+39);c.direction='ltr';c.fillText('damascus-shop.com',540,footer+76);if(s.is_example){c.font='18px sans-serif';c.direction='rtl';c.fillStyle='#efd787';c.textAlign='left';c.fillText(t('متجر تجريبي — مثال','Example shop','Beispielgeschäft'),145,footer+96);}return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('PNG export failed')),'image/png'));

 }
 function composer(s,p){let previewUrl='',localUrl='',logoUrl='',blob=null,shareFile=null,token=0;const poster=!p;modal(`<section class="promo-composer" data-no-translate><h2>${poster?t('لوحة للمحل جاهزة للطباعة','Printable shop sign','Druckbares Geschäftsschild'):t('صورة إعلان جاهزة للنشر','Ready to share product image','Produktbild zum Teilen')}</h2><p>${esc(p?p.name:s.name)}</p>${poster?'':`<label>${t('شكل الصورة','Image format','Bildformat')}<select id="promo-format"><option value="square">${t('منشور مربّع — 1080 × 1080','Square post — 1080 × 1080','Quadratischer Beitrag — 1080 × 1080')}</option><option value="story">${t('حالة واتساب / ستوري — 1080 × 1920','WhatsApp status / story — 1080 × 1920','WhatsApp-Status / Story — 1080 × 1920')}</option></select></label><label>${t('صورة بديلة من الهاتف — اختيارية ولا تُرفع للموقع','Optional photo from your phone; it stays on your device','Optionales Foto vom Handy; es wird nicht hochgeladen')}<input id="promo-local" type="file" accept="image/jpeg,image/png,image/webp"></label>`}<label>${t('شعار المحل — اختياري لهذا الإعلان','Shop logo — optional for this image','Geschäftslogo — optional für dieses Bild')}<input id="promo-logo" type="file" accept="image/jpeg,image/png,image/webp"></label><button type="button" id="promo-build">${t('تجهيز المعاينة','Build preview','Vorschau erstellen')}</button><p id="promo-status" role="status" aria-live="polite"></p><img id="promo-preview" alt="${t('معاينة التصميم','Design preview','Designvorschau')}" hidden><div class="form-actions"><button id="promo-download" type="button" disabled>${t('تحميل الصورة PNG','Download PNG','PNG herunterladen')}</button><button id="promo-share" type="button" disabled>${t('مشاركة الصورة','Share image','Bild teilen')}</button></div>${p?`<label>${t('نص جاهز للنشر مع رابط المنتج','Text with product link','Text mit Produktlink')}<textarea id="promo-text" readonly rows="4">${esc(shareText(s,p))}</textarea></label><button type="button" id="promo-copy">${t('نسخ النص والرابط','Copy text and link','Text und Link kopieren')}</button><p class="muted">${t('الرابط داخل الصورة لا يُضغط؛ انشر النص معها. السعر هو السعر المحفوظ وقت تجهيز الصورة.','Links inside images cannot be tapped. Share the text too. The image uses the current saved price.','Links im Bild sind nicht anklickbar. Teile auch den Text. Das Bild nutzt den aktuell gespeicherten Preis.')}</p>`:`<p>${t('رمز QR يفتح صفحة المحل. جرّب مسحه قبل الطباعة.','The QR code opens your shop page. Test it before printing.','Der QR-Code öffnet deine Geschäftsseite. Vor dem Drucken testen.')}</p>`}</section>`);
 const root=document.querySelector('.promo-composer'),build=root.querySelector('#promo-build'),download=root.querySelector('#promo-download'),share=root.querySelector('#promo-share'),status=root.querySelector('#promo-status'),preview=root.querySelector('#promo-preview');
 const reset=()=>{token++;blob=null;shareFile=null;download.disabled=share.disabled=true;preview.hidden=true;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';};root.querySelector('#promo-format')?.addEventListener('change',reset);root.querySelector('#promo-local')?.addEventListener('change',()=>{reset();if(localUrl)URL.revokeObjectURL(localUrl);localUrl='';const file=root.querySelector('#promo-local').files[0];if(file){if(file.size>10*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){status.textContent=t('اختر JPG أو PNG أو WebP بحجم أقل من 10 ميغابايت','Choose JPG, PNG or WebP under 10 MB','Wähle JPG, PNG oder WebP unter 10 MB');return;}localUrl=URL.createObjectURL(file);}});
 root.querySelector('#promo-logo').addEventListener('change',()=>{reset();if(logoUrl)URL.revokeObjectURL(logoUrl);logoUrl='';const file=root.querySelector('#promo-logo').files[0];if(!file)return;if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){status.textContent=t('اختر شعار JPG أو PNG أو WebP أصغر من 5 ميغابايت','Choose a JPG, PNG or WebP logo under 5 MB','Wähle ein JPG-, PNG- oder WebP-Logo unter 5 MB');return;}logoUrl=URL.createObjectURL(file);});
 build.onclick=async()=>{reset();const attempt=token;build.disabled=true;status.textContent=t('جاري تجهيز الصورة…','Making image…','Bild wird erstellt…');try{const result=await makeImage(s,p,root.querySelector('#promo-format')?.value,localUrl,logoUrl);if(!root.isConnected||attempt!==token)return;blob=result;shareFile=new File([blob],filename(),{type:"image/png"});previewUrl=URL.createObjectURL(blob);preview.src=previewUrl;preview.hidden=false;download.disabled=share.disabled=false;status.textContent=t('راجع المعاينة ثم حمّلها أو شاركها','Check the preview, then download or share it','Vorschau prüfen, dann herunterladen oder teilen');}catch(e){if(root.isConnected&&attempt===token)status.textContent=e.message;}finally{if(root.isConnected)build.disabled=false;}};
 const filename=()=>`daraya-${poster?'shop-sign':p.id}-${root.querySelector('#promo-format')?.value||'print'}.png`;
 const nativeImage=()=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('Image read failed'));reader.onload=()=>{window.DarayaImageShare.onmessage=event=>{try{const reply=JSON.parse(event.data);reply.ok?resolve():reject(Error(reply.error||'Share failed'));}catch(e){reject(e);}};window.DarayaImageShare.postMessage(JSON.stringify({png:String(reader.result).split(',')[1],text:p?shareText(s,p):placePublicUrl(s)}));};reader.readAsDataURL(blob);});
 if(window.DarayaImageShare)download.textContent=t('حفظ أو مشاركة الصورة','Save or share image','Bild speichern oder teilen');
 const oldApp=()=>/ShahinAndroid/.test(navigator.userAgent)&&!window.DarayaImageShare;
 const fallback=()=>{if(oldApp()){status.textContent=t('هذه النسخة تحتاج تحديثًا لمشاركة الصور. انسخ رابط الأداة من الزر أدناه وافتحه في Chrome، أو حدّث التطبيق.','Update the app or open the image tool in your browser.','App aktualisieren oder das Bildwerkzeug im Browser öffnen.');if(!root.querySelector('[data-promo-browser]')){const a=document.createElement('button');a.type='button';a.dataset.promoBrowser='';a.textContent=t('نسخ رابط الأداة لفتحه في Chrome','Copy tool link for Chrome','Werkzeuglink für Chrome kopieren');a.onclick=async()=>{const url=p?productUrl(s,p)+'/promo-browser':placePublicUrl(s);try{await navigator.clipboard.writeText(url);status.textContent=t('تم النسخ. افتح Chrome والصق الرابط ثم أعد تجهيز الإعلان.','Copied. Paste in Chrome and build the image again.','Kopiert. In Chrome einfügen und Bild erneut erstellen.');}catch{status.textContent=url;}};share.after(a);}return;}const a=document.createElement('a');a.href=previewUrl;a.download=filename();a.click();status.textContent=t('احفظ الصورة ثم شاركها من الصور أو معرض الهاتف.','Save the image, then share it from your gallery.','Bild speichern und aus der Galerie teilen.');};
 download.onclick=()=>{if(!blob)return;if(window.DarayaImageShare){nativeImage().catch(()=>fallback());}else fallback();};
 share.onclick=async()=>{if(!blob)return;try{if(window.DarayaImageShare){await nativeImage();status.textContent=t('اختر التطبيق الذي تريد مشاركة الصورة معه','Choose an app to share the image','App zum Teilen wählen');}else if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[shareFile]}))){await navigator.share({files:[shareFile],title:p?.name||s.name});}else fallback();}catch(e){if(e.name!=='AbortError')fallback();}};
 root.querySelector('#promo-copy')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(shareText(s,p));status.textContent=t('تم نسخ النص والرابط','Text and link copied','Text und Link kopiert');}catch{root.querySelector('#promo-text').select();status.textContent=t('حدد النص وانسخه من الحقل','Select and copy the text','Text markieren und kopieren');}});
 const close=()=>{token++;if(previewUrl)URL.revokeObjectURL(previewUrl);if(localUrl)URL.revokeObjectURL(localUrl);if(logoUrl)URL.revokeObjectURL(logoUrl);document.querySelector('#modal').removeEventListener('close',close);};document.querySelector('#modal').addEventListener('close',close);
 }
 function tools(s){document.querySelectorAll('[data-edit-product]').forEach(b=>{if(b.parentElement.querySelector('[data-promo-product]'))return;const p=products.find(p=>p.id===b.dataset.editProduct&&p.store_id===s.id);if(!p||directoryIsInfo(s))return;const action=document.createElement('button');action.type='button';action.className='outline';action.dataset.promoProduct=p.id;action.textContent=t('📸 صورة للنشر','📸 Share image','📸 Bild zum Teilen');action.onclick=()=>composer(s,p);b.parentElement.append(action);});}
 const baseProducts=merchantProducts;merchantProducts=function(s){baseProducts.apply(this,arguments);tools(s);};const baseAdmin=dashboardProducts;dashboardProducts=function(ms,s){baseAdmin.apply(this,arguments);if(s)tools(s);};
 const baseDashboard=merchantDashboard;merchantDashboard=function(ms,s,section){baseDashboard.call(this,ms,s,section==='promo'?'workspace-tools':section);if(!s)return;if(section==='promo'){const host=document.querySelector('#dashboard-content'),ps=products.filter(p=>p.store_id===s.id);host.innerHTML='<section class="panel" data-no-translate><h2>'+t('صور الإعلانات والمشاركة','Promo images and sharing','Werbebilder und Teilen')+'</h2><p>'+t('اختر منتجًا لتجهيز منشور أو حالة واتساب. البيانات من المنتج المحفوظ.','Choose a product for a post or WhatsApp status. Uses saved product data.','Wähle ein Produkt für einen Beitrag oder WhatsApp-Status. Nutzt gespeicherte Produktdaten.')+'</p><button type="button" data-studio-sign>'+t('🪧 لوحة للمحل جاهزة للطباعة','🪧 Printable shop sign','🪧 Druckbares Geschäftsschild')+'</button><div class="promo-product-list">'+(directoryIsInfo(s)?'':ps.map(p=>'<button type="button" class="outline" data-studio-product="'+esc(p.id)+'">📸 '+esc(p.name)+' — '+esc(money(p.price))+'</button>').join(''))+'</div></section>';host.querySelector('[data-studio-sign]').onclick=()=>composer(s,null);host.querySelectorAll('[data-studio-product]').forEach(b=>b.onclick=()=>composer(s,ps.find(p=>p.id===b.dataset.studioProduct)));return;}const home=!section||['overview','stores'].includes(section);if(home){const nav=document.querySelector('.dashboard-menu-grid');if(nav&&!nav.querySelector('[data-promo-sign]')){const b=document.createElement('button');b.type='button';b.className='dashboard-menu-card';b.dataset.promoSign='';b.dataset.noTranslate='';b.innerHTML='<span data-dashboard-icon aria-hidden="true"><span class="dashboard-color-icon">🪧</span></span><span class="merchant-nav-label">'+t('لوحة للمحل جاهزة للطباعة','Printable shop sign','Druckbares Geschäftsschild')+'</span>';b.onclick=()=>composer(s,null);nav.append(b);const a=document.createElement('a');a.href=merchantHref('promo',s);a.className='dashboard-menu-card';a.dataset.noTranslate='';a.innerHTML='<span data-dashboard-icon aria-hidden="true"><span class="dashboard-color-icon">🎨</span></span><span class="merchant-nav-label">'+t('صور الإعلانات والمشاركة','Promo images and sharing','Werbebilder und Teilen')+'</span>';nav.append(a);}}};
 const baseStore=renderStore;renderStore=function(id){baseStore.apply(this,arguments);const s=stores.find(x=>x.id===id&&x.active&&!x.deleted_at);if(!s||directoryIsInfo(s))return;const seenNames=new Map();document.querySelectorAll('.product').forEach(card=>{const add=card.querySelector('[data-add]');const name=card.querySelector('h3')?.textContent;const matches=products.filter(p=>p.store_id===s.id&&p.available&&p.name===name);const offset=seenNames.get(name)||0;seenNames.set(name,offset+1);const p=add?products.find(p=>p.store_id===s.id&&p.available&&p.id===add.dataset.add):matches[offset];if(!p)return;card.dataset.promoProductId=p.id;const b=document.createElement('button');b.type='button';b.className='outline promo-public-share';b.dataset.noTranslate='';b.textContent=t('🔗 مشاركة المنتج','🔗 Share product','🔗 Produkt teilen');b.onclick=()=>shareProduct(s,p);const image=document.createElement('button');image.type='button';image.className='outline promo-public-share';image.dataset.noTranslate='';image.textContent=t('📸 صورة للمشاركة','📸 Share image','📸 Bild zum Teilen');image.onclick=()=>composer(s,p);card.querySelector('h3')?.parentElement?.append(b,image);});const pid=location.hash.split('/')[3];if(location.hash.split('/')[2]==='product'&&pid){const card=Array.from(document.querySelectorAll('[data-promo-product-id]')).find(c=>c.dataset.promoProductId===pid);if(card){card.classList.add('promo-highlight');if(location.hash.endsWith('/promo-browser')){const p=products.find(x=>x.id===pid&&x.store_id===s.id);if(p)composer(s,p);}requestAnimationFrame(()=>requestAnimationFrame(()=>{card.scrollIntoView({block:'center'});}));}else{const note=document.createElement('p');note.className='panel';note.textContent=t('هذا المنتج غير متاح حاليًا؛ يمكنك مشاهدة باقي المعروضات.','This product is not available now. View the other products.','Dieses Produkt ist derzeit nicht verfügbar. Sieh dir andere Produkte an.');document.querySelector('.store-banner')?.after(note);}}};
 window.DarayaPromo={productUrl,shareText,makeImage};
})();



