'use strict';
(()=>{
const t=(a,e,d)=>ct(a,e,d),fail=()=>toast(t('تعذر إكمال العملية. حاول مجددًا.','Could not complete the action. Try again.','Aktion fehlgeschlagen. Bitte erneut versuchen.'));
const scope=()=>user?.id||'guest';
const key=()=> 'daraya-blocks:'+scope();
const local=()=>{try{return JSON.parse(localStorage.getItem(key())||'[]');}catch{return [];}};
let loaded='',loading=false;
function persist(ids){localStorage.setItem(key(),JSON.stringify([...new Set(ids)]));}
async function refresh(){if(!api||!user||loaded===scope()||loading)return;loading=true;const uid=user.id;try{const r=await api.from('daraya_user_blocks').select('blocked_user_id').eq('user_id',uid);if(!r.error&&user?.id===uid){persist((r.data||[]).map(x=>x.blocked_user_id));loaded=uid;decorate();}}finally{loading=false;}}
function reason(title,action){modal('<section data-no-translate><h2>'+title+'</h2><form id="moderation-reason"><label>'+t('السبب','Reason','Grund')+'<textarea name="reason" required minlength="3" maxlength="1000"></textarea></label><button type="submit">'+t('إرسال','Send','Senden')+'</button><p role="status"></p></form></section>');const f=document.querySelector('#moderation-reason');f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await action(f.elements.reason.value.trim());document.querySelector('#modal').close();toast(t('تمت العملية','Done','Erledigt'));}catch{f.querySelector('[role=status]').textContent=t('تعذر إكمال العملية. حاول مجددًا.','Could not complete the action. Try again.','Aktion fehlgeschlagen. Bitte erneut versuchen.');e.submitter.disabled=false;}};}
function reportOffer(id){if(!user){location.hash='#account';toast(t('سجل الدخول لإرسال البلاغ','Sign in to send a report','Zum Melden bitte anmelden'));return;}reason(t('الإبلاغ عن العرض أو ناشره','Report offer or publisher','Angebot oder Verfasser melden'),async reason=>{const r=await api.rpc('report_daily_offer',{p_offer:id,p_reason:reason});if(r.error)throw r.error;});}
function block(id){modal('<section data-no-translate><h2>'+t('حظر الناشر','Block publisher','Verfasser blockieren')+'</h2><p>'+t('ستختفي إعلانات هذا الناشر وعروضه عنك. يمكنك إلغاء الحظر لاحقًا.','This publisher’s ads and offers will be hidden from you. You can unblock them later.','Anzeigen und Angebote dieses Verfassers werden für dich ausgeblendet. Du kannst die Blockierung später aufheben.')+'</p><button id="confirm-publisher-block">'+t('حظر','Block','Blockieren')+'</button></section>');document.querySelector('#confirm-publisher-block').onclick=async e=>{e.target.disabled=true;try{if(user){const r=await api.from('daraya_user_blocks').insert({user_id:user.id,blocked_user_id:id});if(r.error&&r.error.code!=='23505')throw r.error;}persist([...local(),id]);document.querySelector('#modal').close();decorate();toast(t('تم حظر الناشر','Publisher blocked','Verfasser blockiert'));}catch{fail();e.target.disabled=false;}};}
function decorate(){refresh();const blocked=local(),review=['#board-reports','#offer-reports','#offer-review'].includes(location.hash);document.querySelectorAll('article[data-publisher]').forEach(c=>{const id=c.dataset.publisher;if(!id)return;c.hidden=!review&&blocked.includes(id)&&id!==user?.id;if(id===user?.id||review||c.querySelector('[data-block-publisher]'))return;const b=document.createElement('button');b.type='button';b.className='outline';b.dataset.noTranslate='';b.dataset.blockPublisher=id;b.textContent=t('🚫 حظر الناشر','🚫 Block publisher','🚫 Verfasser blockieren');b.onclick=()=>block(id);(c.querySelector('.board-actions')||c).append(b);});document.querySelectorAll('[data-offer-report]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.onclick=()=>reportOffer(b.dataset.offerReport);});const app=document.querySelector('#app');if(!app||app.querySelector('[data-moderation-nav]'))return;if(location.hash==='#account'||(admin&&location.hash.startsWith('#dashboard'))){const nav=document.createElement('div');nav.dataset.moderationNav='';nav.dataset.noTranslate='';nav.className='form-actions';nav.innerHTML='<a class="button outline" href="#blocked-publishers">'+t('🚫 الناشرون المحظورون','🚫 Blocked publishers','🚫 Blockierte Verfasser')+'</a>'+(admin?'<a class="button outline" href="#moderation">'+t('🛡️ البلاغات ومراجعة المحتوى','🛡️ Reports and moderation','🛡️ Meldungen und Moderation')+'</a>':'');app.prepend(nav);}}
async function blockedPage(){communityPublicHeader();const app=document.querySelector('#app');app.innerHTML='<section class="panel" data-no-translate><a href="#account">'+t('حسابي','My account','Mein Konto')+'</a><h1>'+t('الناشرون المحظورون','Blocked publishers','Blockierte Verfasser')+'</h1><p>'+t('الحظر يخفي إعلانات الناشر وعروضه عنك فقط.','Blocking hides the publisher’s ads and offers only for you.','Blockieren blendet Anzeigen und Angebote nur für dich aus.')+'</p><div id="blocked-list"></div></section>';await refresh();const box=document.querySelector('#blocked-list');if(!box)return;const ids=local();box.innerHTML=ids.length?ids.map((id,i)=>'<p>'+t('ناشر محظور','Blocked publisher','Blockierter Verfasser')+' '+(i+1)+' <button class="outline" data-unblock="'+esc(id)+'">'+t('إلغاء الحظر','Unblock','Entsperren')+'</button></p>').join(''):'<p>'+t('لا يوجد ناشرون محظورون.','No blocked publishers.','Keine blockierten Verfasser.')+'</p>';box.querySelectorAll('[data-unblock]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{if(user){const r=await api.from('daraya_user_blocks').delete().eq('user_id',user.id).eq('blocked_user_id',b.dataset.unblock);if(r.error)throw r.error;}persist(local().filter(x=>x!==b.dataset.unblock));blockedPage();}catch{fail();b.disabled=false;}});}
function hub(){communityPublicHeader();document.querySelector('#app').innerHTML='<section class="panel" data-no-translate><h1>'+t('البلاغات ومراجعة المحتوى','Reports and moderation','Meldungen und Moderation')+'</h1>'+(admin?'<div class="form-actions">'+[['offer-review',t('عروض بانتظار الموافقة','Offers awaiting approval','Angebote zur Freigabe')],['board-reports',t('بلاغات الإعلانات والمستعمل','Ad and used-item reports','Meldungen zu Anzeigen')],['offer-reports',t('بلاغات عروض اليوم','Offer reports','Angebotsmeldungen')],['banned-ad-accounts',t('الحسابات المحظورة من النشر','Accounts banned from publishing','Gesperrte Verfasser')]].map(x=>'<a class="button outline" href="#'+x[0]+'">'+x[1]+'</a>').join('')+'</div>':t('للإدارة فقط','Site team only','Nur für die Verwaltung'))+'</section>';}
async function reports(){hub();if(!admin)return;const app=document.querySelector('#app');app.insertAdjacentHTML('beforeend','<section class="panel" data-no-translate><h2>'+t('بلاغات عروض اليوم','Offer reports','Angebotsmeldungen')+'</h2><div id="offer-report-list" role="status">'+t('جاري التحميل…','Loading…','Wird geladen…')+'</div></section>');const box=document.querySelector('#offer-report-list');const r=await api.from('daily_offer_reports').select('*,daily_offers(*)').eq('status','new').order('created_at',{ascending:false}).limit(100);if(!box.isConnected)return;if(r.error){box.textContent=t('تعذر تحميل البلاغات','Could not load reports','Meldungen konnten nicht geladen werden');return;}box.innerHTML=r.data.length?r.data.map(x=>'<article class="panel"><h3>'+esc(x.daily_offers?.title||'')+'</h3><p>'+esc(x.reason)+'</p><p>'+esc(x.daily_offers?.details||'')+'</p><div class="form-actions"><button data-report-review="'+x.id+'" data-hide="true">'+t('إخفاء العرض','Hide offer','Angebot ausblenden')+'</button><button class="outline" data-report-review="'+x.id+'" data-hide="false">'+t('إغلاق البلاغ دون إخفاء','Dismiss report','Meldung schließen')+'</button><button class="outline" data-offer-ban="'+x.offer_id+'">'+t('حظر الناشر من النشر','Ban publisher','Verfasser sperren')+'</button></div></article>').join(''):t('لا توجد بلاغات جديدة','No new reports','Keine neuen Meldungen');box.querySelectorAll('[data-report-review]').forEach(b=>b.onclick=async()=>{b.disabled=true;const x=await api.rpc('review_daily_offer_report',{p_report:b.dataset.reportReview,p_hide:b.dataset.hide==='true'});if(x.error){fail();b.disabled=false;}else reports();});box.querySelectorAll('[data-offer-ban]').forEach(b=>b.onclick=()=>reason(t('سبب حظر الناشر','Reason for banning publisher','Grund der Sperrung'),async p_reason=>{const x=await api.rpc('ban_daily_offer_publisher',{p_offer:b.dataset.offerBan,p_reason});if(x.error)throw x.error;reports();}));}
const base=render;render=function(){if(api&&!passwordRecovery){if(location.hash==='#blocked-publishers')return blockedPage();if(location.hash==='#moderation')return hub();if(location.hash==='#offer-reports')return reports();}return base.apply(this,arguments);};
window.addEventListener('hashchange',()=>{if(['#blocked-publishers','#moderation','#offer-reports'].includes(location.hash))render();});
new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});decorate();
})();