'use strict';
(() => {

 const pinCategories=(window.DARAYA_SECTORS||[]).map(x=>[x[0],x[5],x[1],x[2],x[3]]);
 function pinCategory(s){const kind=directoryKind(s);return kind;}
 window.darayaMapPin=function(s){const color=(pinCategories.find(x=>x[0]===pinCategory(s))||pinCategories[1])[1];return L.divIcon({className:'daraya-color-pin',html:'<svg xmlns="http://www.w3.org/2000/svg" width="30" height="42" viewBox="0 0 30 42" aria-hidden="true"><path d="M15 40C12 35 2 24 2 15a13 13 0 0 1 26 0c0 9-10 20-13 25Z" fill="'+color+'" stroke="white" stroke-width="2"/><circle cx="15" cy="15" r="5" fill="white"/></svg>',iconSize:[30,42],iconAnchor:[15,40],popupAnchor:[0,-38],tooltipAnchor:[0,-34]});};
 function pinLegend(rows,selected='all'){const kinds=new Set(rows.filter(s=>storeCoordinates(s)).map(pinCategory));return '<div class="daraya-map-legend" aria-label="'+text('تصفية الأقسام','Filter categories','Bereiche filtern')+'" style="display:flex;flex-wrap:wrap;gap:6px 8px;margin:8px 0;font-size:12px">'+[['all','#173f35','الكل','All','Alle'],...pinCategories.filter(x=>kinds.has(x[0]))].map(x=>'<button type="button" data-map-category="'+esc(x[0])+'" aria-pressed="'+(selected===x[0])+'" style="display:inline-flex;align-items:center;gap:5px;padding:7px 9px;font-size:inherit;border:1px solid '+(selected===x[0]?x[1]:'#ddd')+';background:'+(selected===x[0]?'#edf4ee':'white')+';color:#173f35;border-radius:10px"><i aria-hidden="true" style="width:10px;height:10px;border-radius:50%;background:'+x[1]+'"></i>'+esc(text(x[2],x[3],x[4]))+'</button>').join('')+'</div>';}


 const catalog=window.DARAYA_MOSQUES||[];
 const isMapCategory=kind=>directoryKinds.some(x=>x[0]===kind)||['apparel','mobile'].includes(kind);
 const normalize=name=>String(name||'').replace(/^(مسجد|جامع)\s+/,'').replace(/[أإآ]/g,'ا').replace(/[ًٌٍَُِّْـ]/g,'').trim();
 function match(seed,rows=stores){return rows.find(s=>s.id===seed.id||s.translations?._directory?.slug===seed.slug||directoryKind(s)==='mosque'&&normalize(s.name)===normalize(seed.name));}
 function payload(seed){return {id:seed.id,name:seed.name,category:'shop',description:'مسجد في مدينة داريا، ريف دمشق.',image:new URL('images/services/mosque.svg',document.baseURI).href,address:'داريا، ريف دمشق، سوريا',contact_phone:'',owner_email:'',active:true,is_open:false,online_ordering:false,delivery_enabled:false,pickup_enabled:false,text_only:true,is_example:false,areas:[],delivery_fee:0,minimum_order:0,delivery_time:'',latitude:seed.latitude,longitude:seed.longitude,translations:{_directory:{kind:'mosque',mode:'info',slug:seed.slug,location_source:seed.location_source}}};}
 function addCatalog(){for(const seed of catalog){if(!seed.adopted&&!match(seed))stores.push({...payload(seed),_mosqueCatalog:true,created_at:'2026-10-04T00:00:00Z',revision:0,opening_hours:{}});}}
 // Database rows always win, so saved names, coordinates and page settings are preserved.
 const originalReload=reload;
 reload=async function(){await originalReload.apply(this,arguments);addCatalog();};
 addCatalog();
 function publicPlaces(kind='all'){return stores.filter(s=>s.active&&!s.deleted_at&&!s.is_example&&(kind==='all'||(directoryKinds.some(x=>x[0]===kind)?directoryKind(s)===kind:matchesCategory(s,kind))));}
 function mapTitle(kind){const titles={apparel:['خريطة الألبسة والتسوّق في داريا','Daraya clothing map','Bekleidung in Daraya'],mobile:['خريطة الجوالات وإكسسواراتها في داريا','Daraya phone shops map','Handygeschäfte in Daraya'],mosque:['خريطة مساجد داريا','Daraya mosque map','Moscheekarte von Daraya'],doctor:['خريطة أطباء داريا','Daraya doctor map','Ärztekarte von Daraya'],pharmacy:['خريطة صيدليات داريا','Daraya pharmacy map','Apothekenkarte von Daraya'],school:['خريطة مدارس داريا','Daraya school map','Schulkarte von Daraya'],restaurant:['خريطة مطاعم ومقاهي داريا','Daraya restaurant map','Restaurantkarte von Daraya'],shop:['خريطة متاجر داريا','Daraya shop map','Geschäftekarte von Daraya'],services:['خريطة مهن وخدمات داريا','Daraya services map','Dienstleistungen in Daraya'],lawyer:['خريطة محامي داريا','Daraya lawyer map','Anwaltskarte von Daraya']};return text(...(titles[kind]||['خريطة داريا','Daraya map','Daraya-Karte']));}
 function text(ar,en,de){return ({ar,en,de})[window.ShahinI18n?.language||'ar'];}
 function searchUrl(s){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(s.name+' داريا ريف دمشق سوريا');}
 let map=null,mapRequest=0;
 function clearMap(){mapRequest++;map?.remove();map=null;}
 async function drawMap(box,rows,zoom=14){
  const status=box.parentElement?.querySelector('[data-mosques-map-status]');const request=++mapRequest;
  try{await loadLeaflet();if(!box.isConnected||request!==mapRequest)return;map?.remove();map=L.map(box,{scrollWheelZoom:false}).setView([33.4588,36.2388],zoom);
   L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,referrerPolicy:'strict-origin-when-cross-origin',attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a>'}).addTo(map);
   const points=[];
   for(const s of rows){const point=storeCoordinates(s);if(!point)continue;points.push(point);const label=document.createElement('span');label.textContent=s.name;const popup=document.createElement('div');const title=document.createElement('strong');title.textContent=s.name;const link=document.createElement('a');link.href='#store/'+s.id;link.className='mosque-pin-action';link.textContent=text('فتح صفحة المكان','Open place page','Ortsseite öffnen');popup.append(title,link);L.marker(point,{title:s.name,alt:s.name,icon:window.darayaMapPin(s)}).addTo(map).bindTooltip(label,{permanent:true,direction:'top',className:'mosque-label'}).bindPopup(popup);}
   if(rows.length===1&&points.length)map.setView(points[0],17);
   else if(points.length>1)map.fitBounds(L.latLngBounds(points).extend([33.4588,36.2388]),{padding:[60,60],maxZoom:15});
   map.invalidateSize();if(status)status.textContent='';
  }catch(e){if(status?.isConnected){status.textContent=text('تعذر تحميل الخريطة. صفحات الأماكن متاحة في القائمة.','The map could not load. You can still open the mosque pages.','Die Karte konnte nicht geladen werden. Die Moscheeseiten sind weiterhin erreichbar.');const retry=document.createElement('button');retry.textContent=text('إعادة المحاولة','Try again','Erneut versuchen');retry.onclick=()=>drawMap(box,rows,zoom);status.append(' ',retry);}}
 }
 function row(s){const point=storeCoordinates(s);return '<a class="mosque-row" href="#store/'+esc(s.id)+'"><strong>'+esc(s.name)+'</strong><small>'+text(point?'الموقع محدد على الخريطة':'الموقع الدقيق قيد التحديد',point?'Map location is available':'Exact location has not been added',point?'Kartenstandort vorhanden':'Genauer Standort noch nicht eingetragen')+'</small></a>';}
 function mapMarkup(kind,rows,full=false){const located=rows.filter(s=>storeCoordinates(s));return '<section class="panel category-map-section'+(full?' full-map-section':'')+'"><div class="topline"><h'+(full?'1':'2')+'>'+esc(mapTitle(kind))+'</h'+(full?'1':'2')+'>'+(full?'':'<a class="button outline" href="#map/'+encodeURIComponent(kind)+'">'+text('فتح الخريطة والقائمة','Open map and list','Karte und Liste öffnen')+'</a>')+'</div><p>'+text('اضغط على الدبوس لفتح صفحة المكان.','Select a pin to open the place page.','Wähle eine Markierung, um die Ortsseite zu öffnen.')+'</p><p class="mosques-status">'+text('عدد الأماكن: '+rows.length+' · المواقع المحددة: '+located.length+' · بانتظار تحديد الموقع: '+(rows.length-located.length),'Places: '+rows.length+' · With a location: '+located.length+' · Location needed: '+(rows.length-located.length),'Orte: '+rows.length+' · Mit Standort: '+located.length+' · Standort fehlt: '+(rows.length-located.length))+'</p>'+(full?'<div class="mosques-controls"><label>'+text('البحث عن مكان','Find a place','Ort suchen')+'<input id="mosque-search" type="search"></label></div><div class="mosques-layout">':'')+'<div>'+pinLegend(rows)+'<div class="mosques-map" id="mosques-map" role="region" aria-label="'+esc(mapTitle(kind))+'"></div><p data-mosques-map-status role="status"></p><p class="field-hint">'+text('تظهر الدبابيس للأماكن التي أُضيف موقع GPS لها. الأماكن التي تنتظر تحديد موقعها متاحة في القائمة.','Pins show places with a GPS location. Places without a location are available in the list.','Markierungen zeigen Orte mit GPS-Standort. Orte ohne Standort sind in der Liste verfügbar.')+'</p></div>'+(full?'<div class="mosques-list" id="mosques-list">'+(rows.map(row).join('')||'<p>'+text('لم تُضف أماكن في هذا القسم بعد.','No places have been added to this section yet.','In diesem Bereich wurden noch keine Orte eingetragen.')+'</p>')+'</div></div>':'')+'</section>';}
 function renderMap(kind='all'){addCatalog();clearMap();const rows=publicPlaces(kind);let selected='all';$('#app').classList.remove('professional-home');$('#app').innerHTML=mapMarkup(kind,rows,true);
  function update(){const term=normalize($('#mosque-search').value).toLowerCase();const found=rows.filter(s=>(selected==='all'||pinCategory(s)===selected)&&normalize(s.name+' '+(s.address||'')).toLowerCase().includes(term));$('#mosques-list').innerHTML=found.map(row).join('')||'<p>'+text('لا توجد نتائج.','No results.','Keine Ergebnisse.')+'</p>';const located=found.filter(s=>storeCoordinates(s)).length;$('.mosques-status').textContent=text('عدد الأماكن: '+found.length+' · المواقع المحددة: '+located+' · بانتظار تحديد الموقع: '+(found.length-located),'Places: '+found.length+' · With a location: '+located+' · Location needed: '+(found.length-located),'Orte: '+found.length+' · Mit Standort: '+located+' · Standort fehlt: '+(found.length-located));drawMap($('#mosques-map'),found);}
  $('#mosque-search').oninput=update;
  $('.daraya-map-legend').onclick=function selectCategory(e){const button=e.target.closest('[data-map-category]');if(!button)return;selected=button.dataset.mapCategory;const legend=$('.daraya-map-legend');legend.outerHTML=pinLegend(rows,selected);$('.daraya-map-legend').onclick=selectCategory;update();};drawMap($('#mosques-map'),rows);
 }
 const previousRender=render;
 render=function(){addCatalog();const route=location.hash.slice(1).split('/');if(route[0]==='mosques-map'){renderMap('mosque');return;}if(route[0]==='map'){const kind=route[1]||'all';renderMap(kind==='all'||isMapCategory(kind)?kind:'all');return;}clearMap();previousRender.apply(this,arguments);};
 const previousHome=renderHome;
 renderHome=function(){addCatalog();clearMap();previousHome.apply(this,arguments);const anchor=$('.shahin-hero')||$('#app').firstElementChild;if(!anchor)return;
  if(filter!=='all'&&isMapCategory(filter)){const entry=document.createElement('section');entry.className='mosques-entry';entry.innerHTML='<div><strong>'+esc(mapTitle(filter))+'</strong><p>'+text('اعرض أماكن هذا القسم على الخريطة.','View places in this section on the map.','Zeige Orte dieses Bereichs auf der Karte.')+'</p></div><a class="button" href="#map/'+encodeURIComponent(filter)+'">'+esc(mapTitle(filter))+'</a>';anchor.insertAdjacentElement('afterend',entry);return;}
 };
 const previousStore=renderStore;
 renderStore=function(id){addCatalog();previousStore.apply(this,arguments);const s=stores.find(x=>x.id===id&&x.active&&!x.deleted_at);if(!s||directoryKind(s)!=='mosque')return;
  const banner=$('.store-banner>div');if(!banner)return;
  banner.querySelector('[data-visit-store] span')?.replaceChildren(document.createTextNode(text('موقع المسجد والعنوان','Mosque location and address','Moscheestandort und Adresse')));
  const point=storeCoordinates(s),section=document.createElement('section');section.className='panel mosque-location';
  section.innerHTML='<h2>'+text('موقع المسجد GPS','Mosque GPS location','GPS-Standort der Moschee')+'</h2>'+(point?'<p><bdi class="mosque-gps">'+point.join(', ')+'</bdi></p><a class="button" target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(point.join(','))+'">'+text('الاتجاهات إلى المسجد','Directions to the mosque','Anfahrt zur Moschee')+'</a><button type="button" class="outline" data-open-mosque-map>'+text('عرض موقع المسجد على الخريطة','Show mosque on the map','Moschee auf der Karte zeigen')+'</button><div data-mosque-map-container></div>':'<p>'+text('لم يُحدد موقع GPS الدقيق لهذا المسجد بعد.','The exact GPS location has not been added yet.','Der genaue GPS-Standort ist noch nicht eingetragen.')+'</p><a class="button outline" target="_blank" rel="noopener noreferrer" href="'+searchUrl(s)+'">'+text('البحث باسم المسجد على Google Maps','Search by mosque name on Google Maps','Nach dem Moscheenamen in Google Maps suchen')+'</a><p class="field-hint">'+text('رابط البحث لا يمثل إحداثيات مؤكدة.','This search link is not a known GPS point.','Dieser Suchlink ist kein bestätigter GPS-Standort.')+'</p>')+'<p><a href="#mosques-map">'+text('عرض خريطة جميع المساجد','View all mosques on the map','Alle Moscheen auf der Karte ansehen')+'</a></p>';
  $('.store-banner').insertAdjacentElement('afterend',section);if(point)section.querySelector('[data-open-mosque-map]').onclick=e=>{e.currentTarget.hidden=true;const box=section.querySelector('[data-mosque-map-container]');box.innerHTML='<div class="mosques-map" id="mosque-page-map"></div><p data-mosques-map-status role="status"></p>';drawMap($('#mosque-page-map'),[s],17);};
 };
 // Import uses the existing admin session and RLS. Nothing changes for an ordinary visitor.
 const previousDashboard=dashboardStores;
 dashboardStores=function(ms){previousDashboard.apply(this,arguments);if(!admin)return;const pending=catalog.filter(seed=>match(seed)?._mosqueCatalog);if(!pending.length)return;const panel=document.createElement('section');panel.className='panel';panel.innerHTML='<h2>صفحات المساجد</h2><p>الصفحات التعريفية ظاهرة للزوار. احفظها في لوحة التحكم لتعديل العناوين والصور والمواقع لاحقاً.</p><button data-import-mosques>إضافة '+pending.length+' مسجدًا إلى لوحة التحكم</button><p data-import-status role="status"></p>';$('#dashboard-content').prepend(panel);panel.querySelector('button').onclick=async e=>{e.target.disabled=true;const status=panel.querySelector('[data-import-status]');try{const result=await api.from('stores').upsert(pending.map(payload),{onConflict:'id',ignoreDuplicates:true});if(result.error)throw result.error;await reload();render();toast('تم حفظ صفحات المساجد في لوحة التحكم');}catch(err){status.textContent='تعذر حفظ المساجد: '+err.message;e.target.disabled=false;}};};
 const menu=$('#site-menu');if(menu){const link=document.createElement('a');link.href='#map';link.textContent=text('خريطة داريا','Daraya map','Daraya-Karte');menu.append(link);}
 window.addEventListener?.('hashchange',()=>{if(/^#(?:map(?:\/|$)|mosques-map$)/.test(location.hash))render();});
 document.querySelector('#language')?.addEventListener('change',()=>render());
})();
