'use strict';
(() => {
 const catalog=window.DARAYA_MOSQUES||[];
 const normalize=name=>String(name||'').replace(/^(مسجد|جامع)\s+/,'').replace(/[أإآ]/g,'ا').replace(/[ًٌٍَُِّْـ]/g,'').trim();
 function match(seed,rows=stores){return rows.find(s=>s.id===seed.id||s.translations?._directory?.slug===seed.slug||directoryKind(s)==='mosque'&&normalize(s.name)===normalize(seed.name));}
 function payload(seed){return {id:seed.id,name:seed.name,category:'shop',description:'مسجد في مدينة داريا، ريف دمشق.',image:new URL('images/services/mosque.svg',document.baseURI).href,address:'داريا، ريف دمشق، سوريا',contact_phone:'',owner_email:'',active:true,is_open:false,online_ordering:false,delivery_enabled:false,pickup_enabled:false,text_only:true,is_example:false,areas:[],delivery_fee:0,minimum_order:0,delivery_time:'',latitude:seed.latitude,longitude:seed.longitude,translations:{_directory:{kind:'mosque',mode:'info',slug:seed.slug,location_source:seed.location_source}}};}
 function addCatalog(){for(const seed of catalog){if(!seed.adopted&&!match(seed))stores.push({...payload(seed),_mosqueCatalog:true,created_at:'2026-10-04T00:00:00Z',revision:0,opening_hours:{}});}}
 // Database rows always win, so saved names, coordinates and page settings are preserved.
 const originalReload=reload;
 reload=async function(){await originalReload.apply(this,arguments);addCatalog();};
 addCatalog();
 function publicMosques(){return stores.filter(s=>s.active&&!s.deleted_at&&directoryKind(s)==='mosque');}
 function text(ar,en,de){return ({ar,en,de})[window.ShahinI18n?.language||'ar'];}
 function searchUrl(s){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(s.name+' داريا ريف دمشق سوريا');}
 let map=null;
 function clearMap(){map?.remove();map=null;}
 async function drawMap(box,rows,zoom=14){
  const status=document.querySelector('[data-mosques-map-status]');
  try{await loadLeaflet();if(!box.isConnected)return;clearMap();map=L.map(box,{scrollWheelZoom:false}).setView([33.4588,36.2388],zoom);
   L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a>'}).addTo(map);
   const points=[];
   for(const s of rows){const point=storeCoordinates(s);if(!point)continue;points.push(point);const label=document.createElement('span');label.textContent=s.name;const popup=document.createElement('div');const title=document.createElement('strong');title.textContent=s.name;const link=document.createElement('a');link.href='#store/'+s.id;link.className='mosque-pin-action';link.textContent=text('فتح صفحة المسجد','Open mosque page','Moscheeseite öffnen');popup.append(title,link);L.marker(point,{title:s.name,alt:s.name}).addTo(map).bindTooltip(label,{permanent:true,direction:'top',className:'mosque-label'}).bindPopup(popup);}
   if(rows.length===1&&points.length)map.setView(points[0],17);
   else if(points.length>1)map.fitBounds(L.latLngBounds(points).extend([33.4588,36.2388]),{padding:[60,60],maxZoom:15});
   map.invalidateSize();if(status)status.textContent='';
  }catch(e){if(status?.isConnected){status.textContent=text('تعذر تحميل الخريطة. صفحات المساجد متاحة في القائمة.','The map could not load. You can still open the mosque pages.','Die Karte konnte nicht geladen werden. Die Moscheeseiten sind weiterhin erreichbar.');const retry=document.createElement('button');retry.textContent=text('إعادة المحاولة','Try again','Erneut versuchen');retry.onclick=()=>drawMap(box,rows,zoom);status.append(' ',retry);}}
 }
 function row(s){const point=storeCoordinates(s);return '<a class="mosque-row" href="#store/'+esc(s.id)+'"><strong>'+esc(s.name)+'</strong><small>'+text(point?'الموقع محدد على الخريطة':'الموقع الدقيق قيد التحديد',point?'Map location is available':'Exact location has not been added',point?'Kartenstandort vorhanden':'Genauer Standort noch nicht eingetragen')+'</small></a>';}
 function renderMap(){clearMap();const rows=publicMosques(),located=rows.filter(s=>storeCoordinates(s));$('#app').innerHTML='<section class="panel"><div class="topline"><div><span class="eyebrow">'+text('داريا · ريف دمشق','Daraya · Damascus countryside','Daraya · Umland von Damaskus')+'</span><h1>'+text('خريطة مساجد داريا','Daraya mosque map','Moscheekarte von Daraya')+'</h1></div><a class="button outline" href="#home">'+text('العودة للسوق','Back to the market','Zurück zum Markt')+'</a></div><p>'+text('اضغط على الدبوس لفتح صفحة المسجد، أو اختر اسمه من القائمة.','Select a pin or a name to open a mosque page.','Wähle eine Markierung oder einen Namen, um die Moscheeseite zu öffnen.')+'</p><p class="mosques-status">'+text('عدد المساجد: '+rows.length+' · المواقع المحددة: '+located.length+' · بانتظار تحديد الموقع: '+(rows.length-located.length),'Mosques: '+rows.length+' · With a location: '+located.length+' · Location needed: '+(rows.length-located.length),'Moscheen: '+rows.length+' · Mit Standort: '+located.length+' · Standort fehlt: '+(rows.length-located.length))+'</p><div class="mosques-controls"><label>'+text('البحث عن مسجد','Find a mosque','Moschee suchen')+'<input id="mosque-search" type="search"></label></div><div class="mosques-layout"><div><div class="mosques-map" id="mosques-map" role="region" aria-label="'+text('خريطة مساجد داريا','Daraya mosque map','Moscheekarte von Daraya')+'"></div><p data-mosques-map-status role="status"></p><p class="field-hint">'+text('تظهر الدبابيس فقط للمساجد التي يتوفر لها موقع محدد. بقية المساجد لها صفحات وتنتظر تحديد موقعها.','Only mosques with a known location have a pin. All other mosque pages are in the list.','Nur Moscheen mit bekanntem Standort haben eine Markierung. Alle weiteren Seiten stehen in der Liste.')+'</p></div><div class="mosques-list" id="mosques-list">'+rows.map(row).join('')+'</div></div></section>';
  $('#mosque-search').oninput=e=>{const term=normalize(e.target.value);const found=rows.filter(s=>normalize(s.name).includes(term));$('#mosques-list').innerHTML=found.map(row).join('')||'<p>'+text('لا توجد نتائج.','No results.','Keine Ergebnisse.')+'</p>';};drawMap($('#mosques-map'),rows);
 }
 const previousRender=render;
 render=function(){if(location.hash==='#mosques-map'){renderMap();return;}clearMap();previousRender.apply(this,arguments);};
 const previousHome=renderHome;
 renderHome=function(){previousHome.apply(this,arguments);const anchor=$('.shahin-hero')||$('#app').firstElementChild;if(!anchor)return;const entry=document.createElement('section');entry.className='mosques-entry';entry.innerHTML='<div><strong>'+text('مساجد داريا على الخريطة','Daraya mosques on the map','Darayas Moscheen auf der Karte')+'</strong><p>'+text('اكتشف المساجد وصفحاتها وطرق الوصول إليها.','Find mosque pages and directions.','Entdecke Moscheeseiten und Anfahrtswege.')+'</p></div><a class="button" href="#mosques-map">'+text('فتح خريطة داريا','Open Daraya map','Daraya-Karte öffnen')+'</a>';anchor.insertAdjacentElement('afterend',entry);};
 const previousStore=renderStore;
 renderStore=function(id){previousStore.apply(this,arguments);const s=stores.find(x=>x.id===id&&x.active&&!x.deleted_at);if(!s||directoryKind(s)!=='mosque')return;
  const banner=$('.store-banner>div');if(!banner)return;
  banner.querySelector('[data-visit-store] span')?.replaceChildren(document.createTextNode(text('موقع المسجد والعنوان','Mosque location and address','Moscheestandort und Adresse')));
  const point=storeCoordinates(s),section=document.createElement('section');section.className='panel mosque-location';
  section.innerHTML='<h2>'+text('موقع المسجد GPS','Mosque GPS location','GPS-Standort der Moschee')+'</h2>'+(point?'<p><bdi class="mosque-gps">'+point.join(', ')+'</bdi></p><a class="button" target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(point.join(','))+'">'+text('الاتجاهات إلى المسجد','Directions to the mosque','Anfahrt zur Moschee')+'</a><div class="mosques-map" id="mosque-page-map"></div><p data-mosques-map-status role="status"></p>':'<p>'+text('لم يُحدد موقع GPS الدقيق لهذا المسجد بعد.','The exact GPS location has not been added yet.','Der genaue GPS-Standort ist noch nicht eingetragen.')+'</p><a class="button outline" target="_blank" rel="noopener noreferrer" href="'+searchUrl(s)+'">'+text('البحث باسم المسجد على Google Maps','Search by mosque name on Google Maps','Nach dem Moscheenamen in Google Maps suchen')+'</a><p class="field-hint">'+text('رابط البحث لا يمثل إحداثيات مؤكدة.','This search link is not a known GPS point.','Dieser Suchlink ist kein bestätigter GPS-Standort.')+'</p>')+'<p><a href="#mosques-map">'+text('عرض خريطة جميع المساجد','View all mosques on the map','Alle Moscheen auf der Karte ansehen')+'</a></p>';
  $('.store-banner').insertAdjacentElement('afterend',section);if(point)drawMap($('#mosque-page-map'),[s],17);
 };
 // Import uses the existing admin session and RLS. Nothing changes for an ordinary visitor.
 const previousDashboard=dashboardStores;
 dashboardStores=function(ms){previousDashboard.apply(this,arguments);if(!admin)return;const pending=catalog.filter(seed=>match(seed)?._mosqueCatalog);if(!pending.length)return;const panel=document.createElement('section');panel.className='panel';panel.innerHTML='<h2>صفحات المساجد</h2><p>الصفحات التعريفية ظاهرة للزوار. احفظها في لوحة التحكم لتعديل العناوين والصور والمواقع لاحقاً.</p><button data-import-mosques>إضافة '+pending.length+' مسجدًا إلى لوحة التحكم</button><p data-import-status role="status"></p>';$('#dashboard-content').prepend(panel);panel.querySelector('button').onclick=async e=>{e.target.disabled=true;const status=panel.querySelector('[data-import-status]');try{const result=await api.from('stores').upsert(pending.map(payload),{onConflict:'id',ignoreDuplicates:true});if(result.error)throw result.error;await reload();render();toast('تم حفظ صفحات المساجد في لوحة التحكم');}catch(err){status.textContent='تعذر حفظ المساجد: '+err.message;e.target.disabled=false;}};};
 const menu=$('#site-menu');if(menu){const link=document.createElement('a');link.href='#mosques-map';link.textContent=text('خريطة مساجد داريا','Daraya mosque map','Moscheekarte von Daraya');menu.append(link);}
 document.querySelector('#language')?.addEventListener('change',()=>render());
})();
