'use strict';
(function(){
const steps=[
['⌕','ابحث عمّا تحتاجه','اختر القسم أو اكتب اسم المكان أو الخدمة أو الشارع.'],
['⌖','اعرف المكان قبل زيارته','شاهد صورة المكان وعنوانه، وافتح الاتجاهات عندما تكون متاحة.'],
['↗','تواصل أو اطلب','تواصل مباشرة مع المكان، أو اطلب من المتاجر التي توفر الطلب عبر الموقع.']
];let step=0;let dismissed=false;try{dismissed=localStorage.getItem('daraya-guide-dismissed')==='1';}catch{}
function guideMarkup(){return '<div class="welcome-guide-head"><strong>كيف تستفيد من سوق داريا؟</strong><button type="button" data-guide-close aria-label="إخفاء الشرح">×</button></div><div class="welcome-guide-slide" aria-live="polite"><span class="guide-symbol" aria-hidden="true">'+steps[step][0]+'</span><div><h3>'+steps[step][1]+'</h3><p>'+steps[step][2]+'</p></div></div><div class="welcome-guide-controls"><div class="guide-dots">'+steps.map((s,i)=>'<button type="button" data-guide-step="'+i+'" aria-label="الخطوة '+(i+1)+'" aria-pressed="'+(i===step)+'">'+(i+1)+'</button>').join('')+'</div><button type="button" data-guide-next>'+(step===2?'ابدأ الاستكشاف':'التالي ←')+'</button></div>';}
function closeGuide(){dismissed=true;try{localStorage.setItem('daraya-guide-dismissed','1');}catch{}document.querySelector('.welcome-guide')?.remove();}
function bindGuide(el){el.innerHTML=guideMarkup();el.querySelector('[data-guide-close]').onclick=closeGuide;el.querySelectorAll('[data-guide-step]').forEach(b=>b.onclick=()=>{step=Number(b.dataset.guideStep);bindGuide(el);});el.querySelector('[data-guide-next]').onclick=()=>{if(step<2){step++;bindGuide(el);}else{closeGuide();document.querySelector('#search')?.focus();}};let start=null;el.addEventListener('touchstart',e=>{start=e.touches[0].clientX;},{passive:true,once:true});el.addEventListener('touchend',e=>{if(start===null)return;const dx=e.changedTouches[0].clientX-start;if(Math.abs(dx)>50){step=Math.max(0,Math.min(2,step+(dx>0?1:-1)));bindGuide(el);}},{passive:true,once:true});}
const previous=renderHome;renderHome=function(){previous.apply(this,arguments);const app=document.querySelector('#app'),hero=app.querySelector('.shahin-hero'),browse=app.querySelector('#browse');if(!hero||!browse)return;app.classList.add('professional-home');hero.innerHTML='<div class="directory-welcome"><span class="welcome-location">داريا · ريف دمشق</span><h1>دليلك إلى متاجر داريا وخدماتها</h1><p>اعثر على متجر، طبيب أو خدمة، وشاهد العنوان وطريقة الوصول والتواصل.</p><button type="button" class="how-it-works">كيف يعمل الموقع؟ <span aria-hidden="true">←</span></button></div>';app.querySelector('.service-strip')?.remove();const filters=browse.querySelector('.filters');if(filters)hero.append(filters);const heading=browse.querySelector('h2');if(heading)heading.textContent=search?'نتائج البحث':'استكشف الأماكن والخدمات';const kicker=browse.querySelector('.section-kicker');if(kicker)kicker.textContent='من داريا، لأهل داريا';const note=app.querySelector('.brand-note');if(note)note.innerHTML='<span class="section-kicker">سوق داريا الإلكتروني</span><h2>اعرف مدينتك. ووصل لوجهتك بسهولة.</h2><p>العناوين والتواصل متاحة للتصفح دون إنشاء حساب. الطلب عبر الموقع متاح لدى المتاجر التي توفره.</p>';function openGuide(){let el=app.querySelector('.welcome-guide');if(!el){el=document.createElement('section');el.className='welcome-guide';el.setAttribute('aria-label','شرح استخدام الموقع');hero.after(el);}bindGuide(el);}hero.querySelector('.how-it-works').onclick=()=>{step=0;openGuide();};if(!dismissed&&!search&&filter==='all')openGuide();const input=hero.querySelector('#search');if(input)input.placeholder='عمّ تبحث في داريا؟';};
window.addEventListener('hashchange',()=>{if(location.hash&&!['#home','#browse'].includes(location.hash))document.querySelector('#app')?.classList.remove('professional-home');});
})();
