'use strict';
(()=>{
const t=(a,e,d)=>ct(a,e,d);
const style=document.createElement('style');style.textContent='.store-banner.store-compact{display:flex!important;flex-direction:column!important;gap:12px!important;padding:16px!important}.store-compact>.store-image,.store-compact .store-header-media{width:100%!important;max-width:760px}.store-compact>.store-image,.store-compact .store-header-media>.store-image{max-height:260px!important;object-fit:cover;aspect-ratio:16/9}.store-compact>.store-identity{width:100%;min-width:0}.store-compact h1{font-size:clamp(24px,5vw,36px)!important;margin:6px 0!important}.shop-info-tabs{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.shop-info-tabs button{min-height:42px;padding:9px 13px;font-size:14px;background:#fff8e0;color:#173b35;border:1px solid #d7bd71;border-radius:12px}.shop-info-tabs button[aria-expanded=true]{background:#173b35;color:#fff}.shop-info-panel{padding:16px;border:1px solid #ddd4bc;border-radius:14px;background:#fff;margin:8px 0;overflow-wrap:anywhere}.shop-info-panel[hidden]{display:none!important}.shop-info-panel .visit-store-button{margin:8px 0;padding:12px;min-height:44px;background:#173b35}.shop-info-panel .panel{margin:0}.store-compact .example-badge{font-size:12px;display:inline-block;padding:3px 8px;background:#fff3c9;border-radius:6px}.store-compact .directory-actions{margin:0}.store-compact .store-header-media{gap:0!important}@media(max-width:600px){.store-banner.store-compact{padding:12px!important}.store-compact>.store-image,.store-compact .store-header-media>.store-image{max-height:190px!important}.shop-info-tabs{gap:6px;margin:8px 0}.shop-info-tabs button{font-size:13px;padding:8px 10px}.store-compact .directory-actions{gap:6px;flex-wrap:wrap}.store-compact .directory-actions>*{font-size:12px;padding:8px;min-height:36px}}';document.head.append(style);
function compact(id){
const s=stores.find(x=>x.id===id&&x.active),banner=document.querySelector('.store-banner');if(!s||!banner||banner.dataset.compact)return;banner.dataset.compact='1';banner.classList.add('store-compact');
const identity=[...banner.children].find(x=>x.tagName==='DIV'&&!x.classList.contains('store-header-media'));if(!identity)return;identity.classList.add('store-identity');
const nav=document.createElement('nav');nav.className='shop-info-tabs';nav.setAttribute('aria-label',t('معلومات المحل','Shop information','Geschäftsinformationen'));nav.dataset.noTranslate='';
const body=document.createElement('div');body.className='shop-info-content';
let index=0;function group(label,nodes){nodes=nodes.filter(Boolean);if(!nodes.length)return;const panel=document.createElement('section');panel.className='shop-info-panel';panel.id='shop-info-'+index++;panel.hidden=true;nodes.forEach(n=>panel.append(n));const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-controls',panel.id);b.setAttribute('aria-expanded','false');b.onclick=()=>{const open=panel.hidden;body.querySelectorAll('.shop-info-panel').forEach(p=>p.hidden=true);nav.querySelectorAll('button').forEach(x=>x.setAttribute('aria-expanded','false'));panel.hidden=!open;b.setAttribute('aria-expanded',String(open));};nav.append(b);body.append(panel);}
const desc=identity.querySelector('h1+p'),example=identity.querySelector('.example-notice');if(example){const badge=document.createElement('span');badge.className='example-badge';badge.dataset.noTranslate='';badge.textContent=t('متجر تجريبي — مثال','Demo shop — example','Beispielgeschäft');identity.querySelector('h1').before(badge);}
group(t('📝 عن المحل','📝 About','📝 Über das Geschäft'),[desc,example]);
const visit=identity.querySelector('[data-visit-store]');const address=[...identity.querySelectorAll(':scope>p')].filter(x=>x!==desc&&x!==example);group(t('📍 العنوان والتواصل','📍 Address and contact','📍 Adresse und Kontakt'),[visit,...address,document.querySelector('[data-store-social]')]);
const meta=identity.querySelector('.meta'),other=[...identity.children].filter(x=>x.tagName==='SMALL'||(x.classList.contains('tag')&&!x.hasAttribute('data-store-status')));
group(t('🚚 التوصيل والاستلام','🚚 Delivery and pickup','🚚 Lieferung und Abholung'),[meta,...other]);
const hours=identity.querySelector('.public-hours');if(hours){hours.open=true;group(t('🕒 أوقات الدوام','🕒 Opening hours','🕒 Öffnungszeiten'),[hours]);}
group(t('🎬 فيديو المحل','🎬 Shop video','🎬 Geschäftsvideo'),[banner.querySelector('.place-video-panel')]);
document.querySelectorAll('.public-shop-section').forEach(x=>group(x.querySelector('h2')?.textContent||t('معلومات إضافية','More information','Weitere Informationen'),[x]));
banner.append(nav,body);
const layout=document.querySelector('.store-layout');if(layout){const tools=[...banner.parentElement.children].filter(x=>x!==banner&&x!==layout&&(x.classList.contains('store-customer-tools')||x.classList.contains('community-offer-grid')));tools.forEach(x=>layout.after(x));}
if(typeof directoryIsInfo==='function'&&directoryIsInfo(s)){const first=nav.querySelector('button');if(first)first.click();}
}
const previous=renderStore;renderStore=function(id){previous.apply(this,arguments);compact(id);};
})();
