'use strict';
let subscriptionSystemEnabled=true,subscriptionSettingsReady=false;
let subscriptionPlans=[],storeSubscriptions=[],storePagePhotos=[];
const planBooleanFields=[['phone','إظهار رقم التواصل'],['catalog','عرض المنتجات والخدمات'],['ordering','الطلب عبر الموقع'],['hours','ساعات الدوام'],['gps','الاتجاهات وGPS'],['featured_home','الظهور المميز في الرئيسية'],['featured_category','الأولوية داخل القسم']];
const planNumberFields=[['max_photos','إجمالي الصور، بما فيها الواجهة والمنتجات',1,1000],['caption_length','حد أحرف وصف الصورة',0,4000],['description_length','حد أحرف وصف المنتج',0,4000]];
const legacyPlan={phone:true,max_photos:1000,caption_length:1000,catalog:true,description_length:1000,ordering:true,hours:true,gps:true,featured_home:false,featured_category:false};
function storePlan(s){if(!subscriptionSystemEnabled)return {name:"نظام الباقات معطل",features:{...legacyPlan,delivery:true}};const sub=storeSubscriptions.find(x=>x.store_id===s.id);if(!sub)return {name:'غير مصنف — الميزات الحالية',features:legacyPlan};const id=sub.active?sub.plan_id:'free',p=subscriptionPlans.find(x=>x.id===id)||{name:'المجاني',features:{max_photos:1}};return {name:p.name,features:{...p.features,...(sub.active?sub.overrides:{})}};}
function placePhotoCount(s){return (s.image?1:0)+storePagePhotos.filter(x=>x.store_id===s.id).length+products.filter(x=>x.store_id===s.id).reduce((n,p)=>n+(p.image?1:0)+(p.gallery||[]).length,0);}
let subscriptionDataLoaded=false,subscriptionDataPending=null;
async function loadSubscriptionData(){
if(subscriptionDataPending)return subscriptionDataPending;
subscriptionDataPending=(async()=>{if(!api)throw Error('انتظر اكتمال الاتصال ثم أعد المحاولة');const results=await Promise.all([api.from('subscription_plans').select('*').order('id'),api.from('store_subscriptions').select('*'),api.from('store_page_photos').select('*').order('position').order('created_at')]);for(const r of results)if(r.error)throw r.error;if(!results[0].data?.length)throw Error('لم تصل الباقات. حدّث البيانات وأعد المحاولة');const settings=await api.from('platform_settings').select('subscriptions_enabled').eq('id',true).single();subscriptionSettingsReady=!settings.error;if(subscriptionSettingsReady)subscriptionSystemEnabled=settings.data.subscriptions_enabled;subscriptionPlans=results[0].data;storeSubscriptions=results[1].data||[];storePagePhotos=results[2].data||[];subscriptionDataLoaded=true;})();
try{return await subscriptionDataPending;}finally{subscriptionDataPending=null;}
}
const subscriptionReload=reload;reload=async function(){await subscriptionReload();await loadSubscriptionData();};
async function savePlanRequest(request){const r=await request;if(r.error)throw r.error;await reload();}
function planFields(features,override=false){return '<div class="form-grid">'+planBooleanFields.map(([key,label])=>override?'<label>'+label+'<select name="'+key+'"><option value="">حسب الباقة</option><option value="true" '+(features[key]===true?'selected':'')+'>تفعيل</option><option value="false" '+(features[key]===false?'selected':'')+'>إلغاء</option></select></label>':'<label class="quality-review"><input type="checkbox" name="'+key+'" '+(features[key]?'checked':'')+'>'+label+'</label>').join('')+planNumberFields.map(([key,label,min,max])=>'<label>'+label+'<input name="'+key+'" type="number" min="'+min+'" max="'+max+'" value="'+(features[key]??'')+'" '+(override?'placeholder="حسب الباقة"':'required')+'></label>').join('')+'</div>';}
function readPlanFields(form,override=false){const f=new FormData(form),out={};for(const [key] of planBooleanFields){if(override){if(f.get(key)!=='')out[key]=f.get(key)==='true';}else out[key]=f.has(key);}for(const [key] of planNumberFields)if(f.get(key)!=='')out[key]=Number(f.get(key));return out;}
async function editSubscription(s){if(!admin)return;try{await loadSubscriptionData();}catch(err){toast('تعذر تحميل الباقات: '+err.message);return;}const sub=storeSubscriptions.find(x=>x.store_id===s.id);modal('<h2>اشتراك '+esc(s.name)+'</h2><form id="subscription-form"><label>الباقة<select name="plan" required>'+subscriptionPlans.map(p=>'<option value="'+p.id+'" '+((sub?.plan_id||'free')===p.id?'selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select></label><label class="quality-review"><input name="active" type="checkbox" '+(sub?.active!==false?'checked':'')+'>الاشتراك مفعّل</label><p class="field-hint">عند الإيقاف تعمل ميزات المجاني. الصور والمنتجات تبقى محفوظة. يمكنك إعطاء هذا المكان استثناءات مستقلة:</p>'+planFields(sub?.overrides||{},true)+'<div class="form-actions"><button>حفظ الاشتراك</button></div><p role="alert" id="subscription-error"></p></form>');
document.querySelector('#subscription-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const f=new FormData(e.target);if(!subscriptionPlans.some(p=>p.id===f.get('plan')))throw Error('اختر باقة صالحة');await savePlanRequest(api.from('store_subscriptions').upsert({store_id:s.id,plan_id:f.get('plan'),active:f.has('active'),overrides:readPlanFields(e.target,true)}));document.querySelector('#modal').close();render();toast('تم حفظ الاشتراك');}catch(err){document.querySelector('#subscription-error').textContent=err.message;b.disabled=false;}};}
async function showPlanSettings(){if(!admin)return;try{await loadSubscriptionData();}catch(err){toast('تعذر تحميل الباقات: '+err.message);return;}modal('<h2>ميزات باقات الاشتراك</h2><p class="field-hint">التعديل يطبق على جميع المشتركين في الباقة، مع احترام استثناءات كل مكان. لا توجد أسعار أو دفعات آلية.</p><div class="plan-settings">'+subscriptionPlans.map(p=>'<details><summary>'+esc(p.name)+'</summary><form data-plan-form="'+p.id+'">'+planFields(p.features)+'<button>حفظ ميزات '+esc(p.name)+'</button><p role="status"></p></form></details>').join('')+'</div>');
document.querySelectorAll('[data-plan-form]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;try{await savePlanRequest(api.from('subscription_plans').update({features:readPlanFields(form)}).eq('id',form.dataset.planForm));form.querySelector('[role=status]').textContent='تم حفظ ميزات الباقة';}catch(err){form.querySelector('[role=status]').textContent=err.message;}finally{b.disabled=false;}});}
const subscriptionDashboard=renderDashboard;renderDashboard=function(tab,sid){subscriptionDashboard.apply(this,arguments);if(!admin)return;const heading=document.querySelector('.admin-heading');if(heading){const b=document.createElement('button');b.className='outline';b.textContent='باقات الاشتراك';b.onclick=showPlanSettings;heading.append(b);const toggle=document.createElement('button');toggle.type='button';toggle.className='outline';toggle.textContent=subscriptionSettingsReady?(subscriptionSystemEnabled?'تعطيل نظام الباقات':'تفعيل نظام الباقات'):'تهيئة مفتاح نظام الباقات';toggle.setAttribute('aria-pressed',String(subscriptionSettingsReady&&subscriptionSystemEnabled));toggle.onclick=async()=>{if(!subscriptionSettingsReady){modal('<h2>تهيئة نظام الباقات</h2><p>يلزم تطبيق تحديث قاعدة البيانات مرة واحدة حتى يُحفظ هذا الإعداد لجميع المستخدمين.</p><a class="button" target="_blank" rel="noopener" href="https://github.com/abdallrahimbirekdar-rgb/beep-beep-daraya/blob/main/supabase/migrations/20261004_delivery_and_plan_switch.sql">فتح تحديث قاعدة البيانات</a>');return;}toggle.disabled=true;try{const r=await api.from('platform_settings').update({subscriptions_enabled:!subscriptionSystemEnabled}).eq('id',true).select('subscriptions_enabled').single();if(r.error)throw r.error;await reload();render();toast(subscriptionSystemEnabled?'تم تفعيل نظام الباقات':'تم تعطيل نظام الباقات');}catch(err){toast(err.message);toggle.disabled=false;}};heading.append(toggle);}};
const subscriptionStores=dashboardStores;dashboardStores=function(ms){subscriptionStores.apply(this,arguments);document.querySelectorAll('.admin-place-card').forEach(card=>{const a=card.querySelector('a[href^="#store/"]'),s=ms.find(x=>x.id===a?.getAttribute('href').split('/')[1]);if(!s)return;const b=document.createElement('button');b.className='outline';b.textContent='الاشتراك: '+storePlan(s).name;b.onclick=()=>editSubscription(s);card.querySelector('.admin-place-actions').append(b);});};
const subscriptionHome=renderHome;renderHome=function(){subscriptionHome.apply(this,arguments);const grid=document.querySelector('#browse .grid');if(grid){const cards=[...grid.querySelectorAll(':scope>.card')];const sid=c=>c.querySelector('a[href*="#store/"]')?.hash.split('/')[1];cards.sort((a,b)=>Number(!!storePlan(stores.find(s=>s.id===sid(b))||{}).features.featured_category)-Number(!!storePlan(stores.find(s=>s.id===sid(a))||{}).features.featured_category));cards.forEach(c=>{grid.append(c);const s=stores.find(x=>x.id===sid(c));if(!s)return;const f=storePlan(s).features;if(!f.phone)c.querySelectorAll('a[href^="tel:"]').forEach(x=>x.remove());if(!f.gps)c.querySelectorAll('a[href*="maps/"]').forEach(x=>x.remove());if(!f.catalog){const bottom=c.querySelector('.card-bottom');if(bottom)bottom.innerHTML='<strong>العنوان والتواصل ←</strong>';c.querySelector('.card-details')?.remove();}if(f.featured_category)c.querySelector('.card-body')?.insertAdjacentHTML('afterbegin','<span class="featured-plan-badge">مكان مميز</span>');});}
const featured=stores.filter(s=>s.active&&!s.deleted_at&&storePlan(s).features.featured_home);if(featured.length&&!search&&filter==='all'){const hero=document.querySelector('.shahin-hero');hero?.insertAdjacentHTML('afterend','<section class="featured-places"><h2>متاجر وأماكن مميزة <button type="button" class="featured-info-button" aria-label="لماذا تظهر هذه المتاجر هنا؟" style="display:inline-flex;width:32px;height:32px;min-height:32px;padding:0;margin-inline-start:6px;border-radius:50%;background:#fff;color:#9d752c;border:1px solid #d8c396;font-size:19px;vertical-align:middle">ⓘ</button></h2><div class="featured-place-track">'+featured.map(s=>'<a href="#store/'+s.id+'">'+photo(s.image,s.name,'featured-place-image')+'<strong>'+esc(s.name)+'</strong><small>'+esc(directoryKinds.find(x=>x[0]===directoryKind(s))?.[1]||'')+'</small></a>').join('')+'</div></section>');const info=document.querySelector('.featured-info-button');if(info)info.onclick=()=>modal('<h2>لماذا تظهر هذه المتاجر هنا؟</h2><p>هذه المتاجر والأماكن مشتركة في الباقة الذهبية، التي تمنحها الظهور في هذا القسم المميز.</p>');}};
const subscriptionStore=renderStore;renderStore=function(id){const s=stores.find(s=>s.id===id);if(!s){subscriptionStore.apply(this,arguments);return;}const f=storePlan(s).features;subscriptionStore.apply(this,arguments);const banner=document.querySelector('.store-banner');if(!banner)return;if(!f.phone)banner.querySelectorAll('a[href^="tel:"]').forEach(a=>a.closest('p')?a.closest('p').remove():a.remove());if(!f.gps){document.querySelectorAll('.directory-actions a[href*="maps/"]').forEach(x=>x.remove());document.querySelector('[data-visit-store]')?.remove();}if(!f.hours)banner.querySelectorAll('details').forEach(x=>x.remove());if(!f.catalog)document.querySelector('.store-layout')?.remove();else{document.querySelectorAll('.product p.muted').forEach(x=>x.textContent=x.textContent.slice(0,f.description_length||0));if(!f.ordering){document.querySelectorAll('[data-add]').forEach(x=>x.remove());document.querySelector('#cart')?.remove();}}
let remaining=Math.max(0,f.max_photos-(s.image?1:0));const photos=storePagePhotos.filter(p=>p.store_id===id).slice(0,remaining);remaining-=photos.length;if(photos.length)banner.insertAdjacentHTML('afterend','<section class="place-photo-gallery">'+photos.map(p=>'<figure>'+photo(p.image,s.name,'gallery-image')+(f.caption_length?'<figcaption>'+esc(p.caption.slice(0,f.caption_length))+'</figcaption>':'')+'</figure>').join('')+'</section>');document.querySelectorAll('.product .photo-button').forEach((x,i)=>{if(i>=remaining)x.remove();});
};
const subscriptionCanOrder=canStoreOrder;canStoreOrder=function(s){return storePlan(s).features.ordering&&subscriptionCanOrder(s);};
function photoGalleryEditor(s){const box=document.querySelector('#dashboard-content');if(!box)return;const f=storePlan(s).features,photos=storePagePhotos.filter(x=>x.store_id===s.id);box.insertAdjacentHTML('beforeend','<section class="panel"><h3>صور المكان ووصفها</h3><p>الاشتراك: '+esc(storePlan(s).name)+' · '+placePhotoCount(s)+' من '+f.max_photos+' صورة إجمالاً</p><p class="field-hint">الحد يشمل صورة الواجهة وصور المنتجات والصور الإضافية.</p><button id="add-place-photo" '+(placePhotoCount(s)>=f.max_photos?'disabled':'')+'>إضافة صورة للمكان</button><div class="place-photo-gallery">'+photos.map(p=>'<figure>'+photo(p.image,s.name,'preview-image')+'<figcaption>'+esc(p.caption)+'</figcaption><button class="outline" data-caption-photo="'+p.id+'">تعديل الوصف</button><button class="danger" data-remove-photo="'+p.id+'">حذف الصورة</button></figure>').join('')+'</div></section>');
document.querySelector('#add-place-photo').onclick=()=>{modal('<h2>إضافة صورة للمكان</h2><form id="edit-form">'+imageFields('')+'<label>وصف الصورة<textarea name="caption" maxlength="'+f.caption_length+'" '+(!f.caption_length?'readonly':'')+'></textarea></label><button type="submit">حفظ الصورة</button><p id="form-error" role="alert"></p></form>');bindSave(async form=>{if(placePhotoCount(s)>=f.max_photos)throw Error('بلغت حد صور الاشتراك');const image=await uploadOrLink(form,s.id);if(!image)throw Error('اختر صورة');const r=await api.from('store_page_photos').insert({store_id:s.id,image,caption:String(form.get('caption')||'').slice(0,f.caption_length),position:photos.length});if(r.error)throw r.error;});};
document.querySelectorAll('[data-caption-photo]').forEach(b=>b.onclick=()=>{const p=photos.find(p=>p.id===b.dataset.captionPhoto);modal('<h2>وصف الصورة</h2><form id="edit-form"><textarea name="caption" maxlength="'+f.caption_length+'">'+esc(p.caption.slice(0,f.caption_length))+'</textarea><button>حفظ</button><p id="form-error"></p></form>');bindSave(async form=>{const r=await api.from('store_page_photos').update({caption:form.get('caption')}).eq('id',p.id);if(r.error)throw r.error;});});
document.querySelectorAll('[data-remove-photo]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await savePlanRequest(api.from('store_page_photos').delete().eq('id',b.dataset.removePhoto));render();}catch(err){toast(err.message);b.disabled=false;}});
}
function lockedPlanPanel(s,label){return '<section class="panel locked-feature-panel"><span class="feature-lock-icon" aria-hidden="true">🔒</span><h2>'+esc(label)+'</h2><p>هذه الخدمة مقفلة في اشتراك '+esc(storePlan(s).name)+'.</p><p class="muted">يمكنك مشاهدة الميزات المتاحة في الباقات الأخرى، والتواصل مع إدارة الموقع لطلب تفعيل الخدمة أو تغيير الاشتراك.</p><a class="button" href="mailto:info@damascus-shop.com?subject='+encodeURIComponent('طلب تطوير اشتراك '+s.name)+'">تواصل مع الإدارة</a><a class="button outline" href="'+merchantHref('overview',s)+'">العودة إلى لوحة المتجر</a></section>';}
const subscriptionMerchantEditor=merchantEditor;merchantEditor=function(s,section){subscriptionMerchantEditor.apply(this,arguments);const f=storePlan(s).features;if(section==='photos')photoGalleryEditor(s);if(section==='details'&&!f.phone){const input=document.querySelector('#merchant-editor [name=contact_phone]'),label=input?.closest('label');if(label){label.hidden=false;label.classList.add('locked-plan-field');input.readOnly=true;label.insertAdjacentHTML('beforeend','<small>🔒 رقم التواصل مقفل في اشتراكك الحالي</small>');}}};
const subscriptionMerchantDashboard=merchantDashboard;merchantDashboard=function(ms,s,section){subscriptionMerchantDashboard.apply(this,arguments);if(!s)return;const f=storePlan(s).features;document.querySelector('.merchant-top')?.insertAdjacentHTML('beforeend','<span class="tag">الاشتراك: '+esc(storePlan(s).name)+'</span>');
const gates={products:['catalog','المنتجات والخدمات'],orders:['ordering','إدارة الطلبات'],delivery:['ordering','الطلب والتوصيل والاستلام'],hours:['hours','ساعات الدوام'],reports:['catalog','الحسابات والتقارير']};
document.querySelectorAll('.merchant-nav a').forEach(a=>{const key=Object.keys(gates).find(key=>a.getAttribute('href')===merchantHref(key,s));a.hidden=false;if(key&&!f[gates[key][0]]){a.classList.add('locked-plan-nav');a.setAttribute('aria-label',gates[key][1]+' — مقفل بسبب الاشتراك');a.insertAdjacentHTML('beforeend','<small class="nav-lock-label">🔒 مقفل</small>');}});
if(gates[section]&&!f[gates[section][0]])document.querySelector('#dashboard-content').innerHTML=lockedPlanPanel(s,gates[section][1]);
if(subscriptionSystemEnabled&&section==='overview'){const services=[['catalog','عرض المنتجات والخدمات','products'],['ordering','الطلبات والتوصيل والاستلام','delivery'],['phone','رقم التواصل','details'],['hours','ساعات الدوام','hours'],['gps','الموقع والاتجاهات','details'],['caption_length','كتابة وصف لكل صورة','photos'],['description_length','كتابة وصف المنتجات','products'],['featured_home','ظهور مميز في الرئيسية','overview'],['featured_category','الأولوية داخل القسم','overview']];document.querySelector('#dashboard-content').insertAdjacentHTML('beforeend','<section class="panel"><h3>الخدمات حسب اشتراكك</h3><p class="field-hint">الخدمات المقفلة ظاهرة للاطلاع، وتحتاج تفعيلًا من الإدارة.</p><div class="plan-service-list">'+services.map(([key,label,target])=>'<a href="'+merchantHref(target,s)+'" class="'+(!f[key]?'locked-plan-service':'')+'" '+(!f[key]?'data-locked-plan="'+key+'"':'')+'><span>'+label+'</span><small>'+(f[key]?'✓ متاحة':'🔒 مقفلة')+'</small></a>').join('')+'</div><p class="field-hint">عدد الصور المتاح: '+f.max_photos+' · وصف الصورة: '+f.caption_length+' حرفًا · وصف المنتج: '+f.description_length+' حرفًا</p></section>');document.querySelectorAll('[data-locked-plan]').forEach(a=>a.onclick=e=>{e.preventDefault();const label=services.find(x=>x[0]===a.dataset.lockedPlan)?.[1];modal(lockedPlanPanel(s,label));});}
};
const subscriptionProduct=editProduct;editProduct=function(s,p={}){const f=storePlan(s).features;if(!f.catalog){toast('عرض المنتجات غير متاح في الاشتراك الحالي');return;}subscriptionProduct.apply(this,arguments);const desc=document.querySelector('#edit-form [name=description]');if(desc)desc.maxLength=f.description_length;document.querySelector('#edit-form')?.insertAdjacentHTML('afterbegin','<p class="field-hint">حد الصور الإجمالي '+f.max_photos+' · وصف المنتج حتى '+f.description_length+' حرفاً</p>');};

const subscriptionInfo=directoryIsInfo;directoryIsInfo=function(s){if(!subscriptionSystemEnabled)return subscriptionInfo(s);if(storeSubscriptions.some(x=>x.store_id===s.id))return !storePlan(s).features.catalog;return subscriptionInfo(s);};

const subscriptionAddress=showStoreAddress;showStoreAddress=function(s){const f=storePlan(s).features;subscriptionAddress({...s,contact_phone:f.phone?s.contact_phone:'',latitude:f.gps?s.latitude:null,longitude:f.gps?s.longitude:null});};
const subscriptionGallery=gallery;gallery=function(p){const s=stores.find(x=>x.id===p.store_id);if(!s)return;const f=storePlan(s).features;if(!f.catalog)return;subscriptionGallery({...p,gallery:(p.gallery||[]).slice(0,Math.max(0,f.max_photos-2))});};

const subscriptionMatchesProduct=matchesProduct;matchesProduct=function(p,term){const s=stores.find(x=>x.id===p.store_id);return !!s&&storePlan(s).features.catalog&&subscriptionMatchesProduct(p,term);};

(function(){let attempted=false;const observer=new MutationObserver(async()=>{if(attempted||subscriptionDataLoaded||!api||!stores.length)return;attempted=true;try{await loadSubscriptionData();if(!document.querySelector('#modal')?.open&&!document.querySelector('#merchant-editor'))render();}catch(err){console.error('Subscription data load failed',err);}finally{observer.disconnect();}});observer.observe(document.querySelector('#app'),{childList:true,subtree:true});})();

function subscriptionMaterialIcon(key){
const palettes={gold:['#ffe7a0','#d9a532','#986618'],silver:['#f3f7fb','#b9c5d0','#718291'],bronze:['#edbc8f','#b87a43','#744425'],iron:['#bac3cc','#687582','#35424e']};
if(key==='free')return '<svg viewBox="0 0 36 36" width="28" height="28" aria-hidden="true" focusable="false"><path d="M6 29L27 8M14 21l-5-9M20 15l10 1M10 25l8 3" fill="none" stroke="#825533" stroke-width="4" stroke-linecap="round"/><path d="M9 12l-2-4M27 8l3-3" fill="none" stroke="#bb8957" stroke-width="2.5" stroke-linecap="round"/><path d="M11 25l12-12" stroke="#d6ab78" stroke-width="1.3" stroke-linecap="round"/></svg>';
const p=palettes[key];if(!p)return '<svg viewBox="0 0 36 36" width="28" height="28" aria-hidden="true" focusable="false"><circle cx="18" cy="18" r="10" fill="none" stroke="#9ba49d" stroke-width="2"/></svg>';
if(key==='iron')return '<svg viewBox="0 0 36 36" width="28" height="28" aria-hidden="true" focusable="false"><path d="M7 9l22-3v6l-7 1v10l7-1v6L7 31v-6l7-1V14l-7 1z" fill="'+p[1]+'" stroke="'+p[2]+'" stroke-width="1.2"/><path d="M7 9l22-3v3L7 12zM15 14l3-.4v10l-3 .4zM7 25l22-3v3L7 28z" fill="'+p[0]+'"/></svg>';
const uid='bullion-'+key+'-'+(subscriptionMaterialIcon.sequence=(subscriptionMaterialIcon.sequence||0)+1);
const metal=key==='gold'?'GOLD':key==='silver'?'SILVER':'BRONZE';
return '<svg viewBox="0 0 36 36" width="28" height="28" aria-hidden="true" focusable="false"><defs>'+
'<linearGradient id="'+uid+'" x1="0" y1="0" x2="1" y2=".8"><stop stop-color="'+p[2]+'"/><stop offset=".16" stop-color="'+p[1]+'"/><stop offset=".38" stop-color="'+p[0]+'"/><stop offset=".52" stop-color="#fff"/><stop offset=".65" stop-color="'+p[0]+'"/><stop offset="1" stop-color="'+p[1]+'"/></linearGradient>'+
'</defs><ellipse cx="18" cy="31.5" rx="12" ry="2" fill="#172820" opacity=".15"/>'+
'<path d="M8 6L25 3Q27 3 28 6L32 25Q33 28 30 29L12 33Q9 33 8 30L4 11Q3 8 8 6Z" fill="'+p[2]+'"/>'+
'<path d="M7 6L24 3Q27 2.5 27.7 6L31 24Q31.5 26.5 28.5 27.2L11 31Q8.5 31.5 8 28.5L4.5 10Q4 7 7 6Z" fill="url(#'+uid+')" stroke="'+p[2]+'" stroke-width=".6"/>'+
'<path d="M9 8L23 5.5Q25 5 25.5 7L28.6 23Q29 25 27 25.5L12 28.5Q10 29 9.7 27L6.8 11Q6.5 8.5 9 8Z" fill="none" stroke="'+p[2]+'" stroke-opacity=".5" stroke-width=".65"/>'+
'<path d="M7 7L24 4M5.5 10L9 28" stroke="#fff" stroke-opacity=".8" stroke-width=".7" stroke-linecap="round"/>'+
'<g transform="rotate(-11 18 18)" text-anchor="middle" font-family="Arial,sans-serif" font-weight="bold" fill="'+p[2]+'"><path d="M16 10h4l1.2 2-3.2 2-3.2-2z" fill="none" stroke="'+p[2]+'" stroke-width=".65"/><text x="18" y="18" font-size="3.4" letter-spacing=".4">'+metal+'</text><text x="18" y="23" font-size="5.5">1 oz</text><path d="M14 25h8" stroke="'+p[2]+'" stroke-width=".5"/></g></svg>';

}
function customerPlanBadge(s){
const sub=storeSubscriptions.find(x=>x.store_id===s.id);const key=sub?(sub.active?sub.plan_id:'free'):'unassigned';
const colors={free:'#825533',iron:'#687582',bronze:'#b87a43',silver:'#899ba9',gold:'#d9a532',unassigned:'#9ba49d'},color=colors[key]||colors.unassigned,icon=subscriptionMaterialIcon(key);
const label=sub?storePlan(s).name:'بدون اشتراك محدد';const b=document.createElement('button');b.type='button';b.className='customer-plan-badge';b.style.setProperty('--plan-badge-color',color);b.innerHTML=icon;b.title='الاشتراك: '+label;b.setAttribute('aria-label','نوع الاشتراك: '+label);
b.onclick=e=>{e.preventDefault();e.stopPropagation();modal('<section class="customer-plan-info"><span class="customer-plan-symbol" aria-hidden="true" style="display:inline-flex;align-items:center;justify-content:center">'+icon.replace('width="28" height="28"','width="64" height="64"')+'</span><h2>'+esc(label)+'</h2><p>هذا الرمز يوضح باقة اشتراك المكان في الموقع.</p></section>');};return b;
}
const badgeRenderHome=renderHome;renderHome=function(){badgeRenderHome.apply(this,arguments);document.querySelectorAll('#browse .card').forEach(card=>{const link=card.querySelector('a[href*="#store/"]'),s=stores.find(s=>s.id===link?.hash.split('/')[1]);const title=card.querySelector('.card-title');if(subscriptionSystemEnabled&&s&&title)title.append(customerPlanBadge(s));});};
const badgeRenderStore=renderStore;renderStore=function(id){badgeRenderStore.apply(this,arguments);const s=stores.find(s=>s.id===id),title=document.querySelector('.store-banner h1');if(subscriptionSystemEnabled&&s&&title)title.append(customerPlanBadge(s));};

// Delivery is an explicit shop choice, separate from online ordering and plan access.
function storeDeliveryAllowed(s){
 if(!subscriptionSystemEnabled)return true;
 const sub=storeSubscriptions.find(x=>x.store_id===s.id);
 return !!(sub?.active&&['silver','gold'].includes(sub.plan_id));
}
function storeOffersDelivery(s){return !!(s&&s.active&&!s.deleted_at&&s.delivery_enabled===true&&storeDeliveryAllowed(s));}
const deliveryMatchesCategory=matchesCategory;matchesCategory=function(s,key=filter){return key==='delivery'?storeOffersDelivery(s):deliveryMatchesCategory(s,key);};
const deliveryHome=renderHome;renderHome=function(){deliveryHome.apply(this,arguments);const hero=document.querySelector('.shahin-hero');if(!hero)return;const b=document.createElement('button');b.type='button';b.dataset.filter='delivery';b.textContent='التوصيل';b.className='delivery-hero-button'+(filter==='delivery'?' selected':'');b.setAttribute('aria-pressed',String(filter==='delivery'));b.onclick=()=>{filter='delivery';search='';browseFavorites=false;renderHome();document.querySelector('#browse')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};const welcome=hero.querySelector('.directory-welcome');if(welcome)welcome.after(b);else hero.prepend(b);if(filter==='delivery'){const heading=document.querySelector('#browse h2');if(heading)heading.textContent='محلات تقدم خدمة التوصيل';const empty=document.querySelector('#browse .empty');if(empty&&!search)empty.textContent='لا توجد محلات تقدم خدمة التوصيل حالياً.';}};
function deliveryViewStore(s){return {...s,delivery_enabled:s.delivery_enabled===true&&storeDeliveryAllowed(s)};}
const deliveryStore=renderStore;renderStore=function(id){const s=stores.find(x=>x.id===id);if(!s)return deliveryStore.apply(this,arguments);const choice=s.delivery_enabled;s.delivery_enabled=deliveryViewStore(s).delivery_enabled;try{return deliveryStore.apply(this,arguments);}finally{s.delivery_enabled=choice;}};
const deliveryCart=renderCart;renderCart=function(s){return deliveryCart(deliveryViewStore(s));};
const deliveryOrderMethod=orderMethod;orderMethod=function(s){return deliveryOrderMethod(deliveryViewStore(s));};
const deliveryCanOrder=canStoreOrder;canStoreOrder=function(s,date){return deliveryCanOrder(deliveryViewStore(s),date);};
const deliveryCheckout=checkout;checkout=function(s){if(orderMethod(s)==='delivery'&&!storeOffersDelivery(s)){toast('هذا المحل لا يقدم خدمة التوصيل حالياً');return;}return deliveryCheckout(s);};
function applyDeliveryChoice(form,s){
 const input=form?.elements.delivery_enabled;if(!input)return;
 const allowed=storeDeliveryAllowed(s);input.checked=allowed&&s.delivery_enabled===true;input.disabled=!allowed;
 const label=input.closest('label');if(label&&!allowed)label.insertAdjacentHTML('beforeend','<small>خدمة التوصيل متاحة من الاشتراك الفضي فما فوق، وتحتاج تفعيل صاحب المحل.</small>');
 input.dispatchEvent(new Event('change'));
}
const deliveryEditStore=editStore;editStore=function(s={}){deliveryEditStore.apply(this,arguments);applyDeliveryChoice(document.querySelector('#edit-form'),s);};
const deliveryMerchantEditor=merchantEditor;merchantEditor=function(s,section){deliveryMerchantEditor.apply(this,arguments);if(section==='delivery')applyDeliveryChoice(document.querySelector('#merchant-editor'),s);};
const deliveryService=storeService;storeService=function(s){return deliveryService(deliveryViewStore(s));};
