'use strict';
(()=>{
 const VERSION='2026-10-10',t=(a,e,d)=>ct(a,e,d);
 const language=()=>window.ShahinI18n?.language||'ar';
 const accepted=()=>user?.user_metadata?.terms_version===VERSION;
 const links=()=>'<a href="terms.html?lang='+language()+'" target="_blank" rel="noopener">'+t('شروط الاستخدام وقواعد النشر','Terms and publishing rules','Nutzungsbedingungen und Veröffentlichungsregeln')+'</a>';
 function check(post=false){return '<label data-terms-check data-no-translate style="display:flex;align-items:flex-start;gap:10px;margin:16px 0;line-height:1.7"><input type="checkbox" name="terms_agreement" required style="width:20px;height:20px;flex:none;margin-top:5px"><span>'+ (post?t('أؤكد صحة المعلومات وامتلاكي حق نشرها والتزام هذا المحتوى بـ ','I confirm that the details are correct, I have the right to post them and this content follows the ','Ich bestätige die Richtigkeit der Angaben, meine Veröffentlichungsrechte und die Einhaltung der '):t('أوافق على ','I agree to the ','Ich stimme den '))+links()+(post?'':t('، وقد اطّلعت على ',' and I have read the ',' zu und habe die ')+ '<a href="privacy.html" target="_blank" rel="noopener">'+t('سياسة الخصوصية','privacy policy','Datenschutzerklärung')+'</a>')+'</span></label>';}
 const posting='.board-form[data-publishing],#daily-offer-form,#community-offer-form,#community-request-form,#community-reply-form,#business-application-form';
 function decorate(){const auth=document.querySelector('#customer-auth-form');if(auth?.elements.confirm&&!auth.querySelector('[data-terms-check]'))auth.querySelector('[type=submit]').insertAdjacentHTML('beforebegin',check());document.querySelectorAll(posting).forEach(f=>{if(!f.querySelector('[data-terms-check]')){const b=f.querySelector('button:not([type=button])');if(b)b.insertAdjacentHTML('beforebegin',check(true));}});}
 async function save(){if(!user||!api)throw Error('Sign in required');const uid=user.id;const r=await api.auth.updateUser({data:{terms_version:VERSION,terms_accepted_at:new Date().toISOString()}});if(r.error)throw r.error;if(user?.id===uid)user=r.data.user;}
 const released=new WeakSet();
 document.addEventListener('submit',async e=>{const f=e.target;if(!f.matches?.(posting))return;if(released.has(f)){released.delete(f);return;}const box=f.querySelector('[name=terms_agreement]');if(!box?.checked){e.preventDefault();e.stopImmediatePropagation();box?.reportValidity();return;}if(accepted())return;e.preventDefault();e.stopImmediatePropagation();const b=e.submitter;if(b)b.disabled=true;try{await save();if(!f.isConnected)return;if(b)b.disabled=false;released.add(f);f.requestSubmit(b||undefined);}catch{toast(t('تعذر حفظ الموافقة. حاول مجددًا.','Could not save your agreement. Try again.','Zustimmung konnte nicht gespeichert werden. Versuche es erneut.'));}finally{if(b?.isConnected)b.disabled=false;}},true);
 const account=renderCustomerAccount;
 renderCustomerAccount=function(){if(!user||accepted())return account.apply(this,arguments);const r=window.DarayaTermsRules[language()]||window.DarayaTermsRules.ar;document.querySelector('#app').innerHTML='<section class="panel" data-no-translate><h1>'+r.title+'</h1><p>'+t('لإكمال إعداد حسابك، راجع القواعد ووافق عليها. يمكنك التصفح دون الموافقة.','To finish setting up your account, read and agree to the rules. You can browse without agreeing.','Lies die Regeln und stimme zu, um dein Konto einzurichten. Ohne Zustimmung kannst du weiter stöbern.')+'</p><ul>'+r.items.map(x=>'<li>'+x+'</li>').join('')+'</ul><form id="terms-account-form">'+check()+'<button type="submit">'+t('أوافق وأتابع','Agree and continue','Zustimmen und weiter')+'</button><p role="status"></p></form><div class="form-actions"><a href="#home">'+r.home+'</a><button id="terms-signout" class="outline">'+t('تسجيل الخروج','Sign out','Abmelden')+'</button><a href="delete-account.html">'+t('حذف الحساب','Delete account','Konto löschen')+'</a></div></section>';document.querySelector('#terms-signout').onclick=customerSignOut;document.querySelector('#terms-account-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await save();render();}catch{e.target.querySelector('[role=status]').textContent=t('تعذر حفظ الموافقة. حاول مجددًا.','Could not save your agreement. Try again.','Zustimmung konnte nicht gespeichert werden. Versuche es erneut.');b.disabled=false;}};};
 const footer=document.querySelector('footer');if(footer){const a=document.createElement('a');a.href='terms.html';a.dataset.noTranslate='';a.textContent=t('شروط الاستخدام وقواعد النشر','Terms and publishing rules','Nutzungsbedingungen und Veröffentlichungsregeln');footer.append(a);}
 new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});decorate();
})();
