const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('community-tools.js','utf8');
function helpers(){const ctx=vm.createContext({window:{ShahinI18n:{language:'ar'}},api:null,Date,Intl,console,Number});vm.runInContext(code.split('const communityHomeBase=')[0],ctx);return s=>vm.runInContext(s,ctx);}
test('nearby distance is symmetric, handles same point, and is correct for one degree',()=>{const r=helpers();assert.equal(r('communityDistance([33.45,36.23],[33.45,36.23])'),0);assert.ok(Math.abs(r('communityDistance([0,0],[0,1])')-111.195)<0.01);assert.equal(r('communityDistance([33,36],[35,38])'),r('communityDistance([35,38],[33,36])'));});
test('offers start and expire at exact boundaries and disabled offers stay hidden',()=>{const r=helpers();r(`s={translations:{_community:{offers:[{title:'live',starts_at:'2026-10-05T10:00:00Z',ends_at:'2026-10-05T12:00:00Z'},{title:'disabled',active:false,ends_at:'2026-10-06T12:00:00Z'},{title:'future',starts_at:'2026-10-06T10:00:00Z',ends_at:'2026-10-07T12:00:00Z'},{title:'bad',ends_at:'wrong'}]}}}`);assert.equal(r("communityOffers(s,Date.parse('2026-10-05T10:00:00Z')).length"),1);assert.equal(r("communityOffers(s,Date.parse('2026-10-05T12:00:00Z')).length"),0);});
test('Syria date input does not depend on customer timezone and roundtrips',()=>{const r=helpers();assert.equal(r("communityLocalTime('2026-10-06T13:30')"),'2026-10-06T10:30:00.000Z');assert.equal(r("communityKnownDate(communityLocalTime('2026-10-06T13:30'))"),'2026-10-06T13:30');assert.equal(r("communityLocalTime('')"),'');});
test('unknown hours never count as open-now and invalid schedules stay out',()=>{const r=helpers();assert.equal(r('communityHasHours({opening_hours:{}})'),false);assert.equal(r("communityHasHours({opening_hours:{mon:{closed:true}}})"),false);assert.equal(r("communityHasHours({opening_hours:{mon:{closed:false,open:'09:00',close:'22:00'}}})"),true);});
test('database readiness uses one probe, retries failures, and never reports a false success',async()=>{const r=helpers();assert.equal(await r('communityReady()'),false);r("calls=0;api={rpc:async()=>{calls++;return {error:{code:'PGRST202'}}}};");assert.deepEqual(await Promise.all([r('communityReady()'),r('communityReady()')]),[false,false]);assert.equal(r('calls'),1);r("api={rpc:async()=>{calls++;return {data:1}}};");assert.equal(await r('communityReady()'),true);assert.equal(await r('communityReady()'),true);assert.equal(r('calls'),2);});
test('RLS denies public tables and contacts are restricted to customer or provider',()=>{const sql=fs.readFileSync('supabase/migrations/20261005_community_tools.sql','utf8');for(const t of ['market_requests','market_replies','service_bookings','place_reports','place_events'])assert.match(sql,new RegExp(`alter table public\\.${t} enable row level security`));assert.match(sql,/revoke all on public.market_requests,public.market_replies,public.service_bookings,public.place_reports,public.place_events from anon,authenticated/);assert.match(sql,/using\(user_id=auth.uid\(\) or public.manages_store\(store_id\)\)/);assert.match(sql,/using\(public.is_admin\(\)\)/);assert.match(sql,/if auth.uid\(\) is null or not public.manages_store\(p_store\)/);});
