const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function app(){const elements={};const doc={querySelector:s=>elements[s]||(elements[s]={innerHTML:'',textContent:'',hidden:false,setAttribute(){},addEventListener(){},insertAdjacentHTML(){},querySelector(){return null;}}),querySelectorAll:()=>[]};const context=vm.createContext({document:doc,window:{BEEP_CONFIG:{},addEventListener(){},removeEventListener(){}},localStorage:{getItem(){return null},setItem(){}},location:{hash:'#home',href:'https://example.com/site/'},URL,Intl,Date,console,setTimeout,clearTimeout,setInterval(){},clearInterval(){},FileReader:function(){},structuredClone});vm.runInContext(['merchant','app','features','customer'].map(f=>fs.readFileSync('public/'+f+'.js','utf8').replace(/init\(\);\s*$/,'')).join('\n'),context);vm.runInContext(fs.readFileSync('public/market-tools.js','utf8').split('const marketDirtyForms=')[0],context);return {run:s=>vm.runInContext(s,context),elements};}
test('guest checkout cannot invoke order API and keeps the cart',()=>{const a=app();a.run("api={rpc(){throw Error('guest API call')}};cartStore='s';cart={p:{id:'p',quantity:1,options:[]}};checkout({id:'s'})");assert.equal(a.run('location.hash'),'account');assert.equal(a.run('pendingCustomerCheckout'),'s');assert.equal(a.run('cartStore'),'s');assert.match(a.elements['#app'].innerHTML,/customer-auth-form/);});
test('product search handles Arabic vowels and matches translated product names, excludes hidden and sold out items',()=>{const a=app();a.run("window.ShahinI18n={translate:t=>t==='برغر لحم'?'Beef Burger':t};stores=[{id:'s',active:true,category:'restaurant'},{id:'hidden',active:false,category:'restaurant'}];products=[{id:'a',store_id:'s',available:true,name:'برغر لحم'},{id:'b',store_id:'s',available:true,name:'فَلافِل'},{id:'c',store_id:'hidden',available:true,name:'برغر لحم'},{id:'d',store_id:'s',available:false,name:'برغر لحم'}]");assert.equal(a.run("searchProducts('beef burger').length"),1);assert.equal(a.run("searchProducts('فلافل')[0].id"),'b');a.run("browseFavorites=true;favoriteIds=[]");assert.equal(a.run("searchProducts('burger').length"),0);});
test('profile writes use authenticated identity and reject guests',async()=>{const a=app();a.run("user={id:'own'};api={from:()=>({upsert:async p=>{window.saved=p;return {error:null}}})}");await a.run("saveCustomerProfile({user_id:'other',display_name:' Ali ',address:'street'})");assert.equal(a.run('window.saved.user_id'),'own');assert.equal(a.run('window.saved.display_name'),'Ali');a.run('user=null');await assert.rejects(a.run('saveCustomerProfile({})'));});
test('switching accounts drops old profile and cart before reload',async()=>{const a=app();a.run("user={id:'first'};customerProfile={address:'private'};cart={secret:1};cartStore='s';reload=async()=>{};render=()=>{}");await a.run("customerAuthChanged('SIGNED_IN',{user:{id:'second'}})");assert.equal(a.run('customerProfile'),null);assert.equal(a.run('cartStore'),null);assert.equal(a.run('Object.keys(cart).length'),0);});

test('store search finds professions by synonyms and respects every query word',()=>{const a=app();a.run("window.clinic={name:'عيادة طب عام',description:'زيارات ومتابعة'};window.barber={name:'حلاق داريا',description:'قص الشعر'}");assert.equal(a.run("matchesStore(window.clinic,'طبيب')"),true);assert.equal(a.run("matchesStore(window.clinic,'الدكتور')"),true);assert.equal(a.run("matchesStore(window.clinic,'طَبِيب عام')"),true);assert.equal(a.run("matchesStore(window.clinic,'طبيب اسنان')"),false);assert.equal(a.run("matchesStore(window.barber,'حلاقة')"),true);assert.equal(a.run("matchesStore({name:'نجار داريا'},'اثاث')"),true);assert.equal(a.run("matchesStore({name:'مطعم',description:'طلب وجبة'},'طبيب')"),false);assert.equal(a.run("matchesStore(window.clinic,'Arzt')"),true);});

test('home rendering retains a clinic matched by a profession synonym',()=>{const a=app();a.run("stores=[{id:'clinic',name:'عيادة طب عام',description:'زيارة عيادة',active:true,category:'shop',text_only:true,online_ordering:false,opening_hours:{}}];products=[];search='طبيب';renderHome()");assert.match(a.elements['#app'].innerHTML,/عيادة طب عام/);assert.doesNotMatch(a.elements['#app'].innerHTML,/لا توجد محلات مطابقة لبحثك/);});

test('colloquial phone words and one-letter typos find mobile shops without unrelated matches',()=>{const a=app();a.run("window.mobile={name:'داريا فون للإكسسوارات',description:'سماعات وكابلات وباور بنك لإكسسوارات هاتفك اليومية'}");for(const word of ['تلفون','تليفون','تلفونات','التلفونات','تليفونات','موبيل','اكسسوارت','mobile'])assert.equal(a.run(`matchesStore(window.mobile,${JSON.stringify(word)})`),true,word);assert.equal(a.run("matchesStore(window.mobile,'تلفون اطفال')"),false);assert.equal(a.run("matchesStore({name:'عيادة طب عام'},'تلفون')"),false);assert.equal(a.run("matchesStore({name:'حلاق داريا'},'حلاقه')"),true);});
