const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const A='a5e8abe7-974a-416c-a570-858d6fd03572',B='de55d8a4-e315-4c6d-95c8-1a8b6d731001';
function setup(rows=[],saved=null){const calls=[],app={innerHTML:''},timers=[];let imageCallback,mutationCallback;const body={nodeType:1,matches:()=>false,querySelectorAll:()=>[]};const c={Event:class{constructor(type){this.type=type}},dispatchEvent(){},console,Set,Map,Date,JSON,Promise,location:{hash:'#home'},user:null,api:{from(table){const q={table};const b={select(v){q.select=v;return b},in(k,v){q.ids=v;return b},eq(k,v){q.eq=[k,v];return b},order(){return b},or(v){q.or=v;return b},async range(lo,hi){calls.push({...q,lo,hi});return {data:rows.filter(r=>!q.ids||q.ids.includes(r.store_id)).slice(lo,hi+1)}}};return b}},products:[],cartStore:null,passwordRecovery:false,localStorage:{getItem:()=>JSON.stringify(saved)},document:{body,activeElement:null},MutationObserver:class{constructor(fn){mutationCallback=fn}observe(){}},IntersectionObserver:class{constructor(fn){imageCallback=fn}observe(){}unobserve(){}},setTimeout(fn){timers.push(fn);return timers.length},clearTimeout(){},searchProducts(){return c.products},renderHome(){},matchesStore(){return false},search:'',repeatOrder(){c.repeated=true},toast(){},render(){c.rendered=true},reload:async()=>{await c.window.DarayaDemand.fetchProducts()},$:()=>app};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../demand-loading.js','utf8'),c);return {c,calls,timers,app,mutations:r=>mutationCallback(r),intersect:e=>imageCallback(e)}}
test('home performs no product query',async()=>{const {c,calls}=setup();await c.DarayaDemand.fetchProducts();assert.equal(calls.length,0)});
test('opened shop and saved basket load, unrelated products do not',async()=>{const {c,calls}=setup([{id:1,store_id:A},{id:2,store_id:B},{id:3,store_id:'other'}],{cartStore:B});c.location.hash='#store/'+A;await c.DarayaDemand.fetchProducts();assert.equal(c.products.length,2);assert.equal(calls[0].ids.length,2)});
test('management loads all pages beyond the Supabase default row limit',async()=>{const rows=Array.from({length:1501},(_,id)=>({id,store_id:A}));const {c,calls}=setup(rows);c.user={id:'admin'};c.location.hash='#dashboard';await c.DarayaDemand.fetchProducts();assert.equal(c.products.length,1501);assert.equal(calls.length,2)});
test('logged out dashboard does not download every product',async()=>{const {c,calls}=setup();c.location.hash='#dashboard';await c.DarayaDemand.fetchProducts();assert.equal(calls.length,0)});
test('shop route waits for products and rerenders; immediate revisit uses memory',async()=>{const {c,calls}=setup([{store_id:A}]);c.location.hash='#store/'+A;assert.equal(c.DarayaDemand.deferRender(),true);await new Promise(r=>setImmediate(r));assert.equal(c.rendered,true);assert.equal(c.DarayaDemand.deferRender(),false);assert.equal(calls.length,1)});
test('repeat order fetches its shop even from order history',async()=>{const {c,calls}=setup([{id:'p',store_id:A}]);await c.repeatOrder({store_id:A});assert.equal(calls[0].eq[1],A);assert.equal(c.repeated,true)});
test('search fetches matching IDs without image or gallery columns',async()=>{const {c,calls,timers}=setup([{id:'p',store_id:A}]);c.search='falafel';c.renderHome();await timers.pop()();assert.equal(calls[0].select.includes('gallery'),false);assert.equal(calls[0].select.includes('option_groups'),false);assert.match(calls[0].or,/name.ilike/);assert.equal(c.matchesStore({id:A},'falafel'),true)});
test('images receive their URL only when approaching viewport',()=>{const {mutations,intersect}=setup();const img={nodeType:1,dataset:{lazySrc:'https://example.com/photo.webp'},matches:()=>true,querySelectorAll:()=>[]};mutations([{removedNodes:[],addedNodes:[img]}]);assert.equal(img.src,undefined);intersect([{target:img,isIntersecting:false}]);assert.equal(img.src,undefined);intersect([{target:img,isIntersecting:true}]);assert.equal(img.src,'https://example.com/photo.webp')});
