const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const crypto=require('node:crypto').webcrypto;global.crypto=crypto;
const src=fs.readFileSync('supabase/functions/driver-code/index.ts','utf8').replace(/^import .*\n/,'').split('\nconst keys=')[0].replaceAll('export function','function').replaceAll('export async function','async function');const {createHandler,driverCodeEmail,generateDriverCode}=new Function(src+';return {createHandler,driverCodeEmail,generateDriverCode};')();
const sid='11111111-1111-4111-8111-111111111111',did='22222222-2222-4222-8222-222222222222';
function fixture({admin=false,owner=true,valid=true,previous=null,bindFail=false,savedCode=null}={}){const created=[],bound=[],deleted=[],banned=[];const client={auth:{getUser:async()=>({data:{user:valid?{id:'actor',email:'owner@example.com'}:null}}),admin:{createUser:async body=>{created.push(body);return {data:{user:{id:'new-user'}}};},deleteUser:async id=>{deleted.push(id);return {};},updateUserById:async(id,p)=>{banned.push({id,p});return {};}}},from:table=>{const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:table==='platform_admins'?(admin?{user_id:'actor'}:null):table==='store_drivers'?previous:{owner_email:owner?'owner@example.com':'another@example.com',deleted_at:null}})};return q;},rpc:async(name,p)=>{bound.push({name,p});return {data:savedCode?{code:savedCode}:null,error:bindFail?{}:null};}};return {handler:createHandler(client),created,bound,deleted,banned};}
function req(extra={},token=true){return new Request('https://example.com',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://damascus-shop.com',...(token?{Authorization:'Bearer session'}:{})},body:JSON.stringify({store_id:sid,name:'Driver',phone:'0945123456',...extra})});}
test('anonymous, expired and other-store actors cannot create driver access',async()=>{for(const f of [fixture({valid:false}),fixture({owner:false})]){assert.ok([401,403].includes((await f.handler(req())).status));assert.equal(f.created.length,0);}const f=fixture();assert.equal((await f.handler(req({},false))).status,401);});
test('merchant cannot create platform driver; admin can',async()=>{let f=fixture();assert.equal((await f.handler(req({store_id:null}))).status,403);f=fixture({admin:true});assert.equal((await f.handler(req({store_id:null}))).status,201);assert.equal(f.bound[0].p.p_store,null);});
test('server creates own random code and limited Auth identity; client cannot inject credentials or role',async()=>{const f=fixture();const r=await f.handler(req({code:'111111111111',password:'attack',role:'admin',user_id:'victim'}));assert.equal(r.status,201);const data=await r.json();assert.match(data.code,/^\d{12}$/);assert.equal(f.created[0].password,data.code);assert.equal(f.created[0].email,await driverCodeEmail(data.code));assert.deepEqual(f.created[0].app_metadata,{driver_code_only:true});assert.equal(f.bound[0].p.p_actor,'actor');assert.equal(f.bound[0].p.p_user,'new-user');assert.equal(f.bound[0].p.p_code,data.code);assert.equal(f.bound[0].name,'provision_driver_code_with_secret');assert.equal(r.headers.get('Cache-Control'),'no-store');});
test('binding conflict cleans only newly created account and never affects old driver',async()=>{const f=fixture({bindFail:true});assert.equal((await f.handler(req())).status,409);assert.deepEqual(f.deleted,['new-user']);assert.equal(f.banned.length,0);});
test('rotation derives scope from stored driver and passes expected owner; old ordinary user is never banned',async()=>{for(const coded of [false,true]){const previous={id:did,store_id:sid,user_id:'old',name:'D',phone:'0999',email:coded?'hash@driver.damascus-shop.invalid':'normal@example.com',active:true};const f=fixture({previous});assert.equal((await f.handler(req({driver_id:did,store_id:null}))).status,201);assert.equal(f.bound[0].p.p_expected_user,'old');assert.equal(f.bound[0].p.p_store,sid);assert.equal(f.banned.length,coded?1:0);}});
test('inactive driver gets no new identity',async()=>{const f=fixture({previous:{id:did,store_id:sid,active:false}});assert.equal((await f.handler(req({driver_id:did}))).status,400);assert.equal(f.created.length,0);});
test('frontend normalization and hash agree with server; only trusted app metadata restricts UI',async()=>{const c=vm.createContext({crypto,TextEncoder,Uint8Array,user:null,merchantDrivers(){},renderDriverDashboard(){},render(){},window:{removeEventListener(){},addEventListener(){}},console});vm.runInContext(fs.readFileSync('driver-code.js','utf8'),c);assert.equal(c.normalizeDriverCode('٥٨٤٧ ٢٩١٦ ٣٨٠٥'),'584729163805');assert.equal(await c.driverCodeIdentity('584729163805'),await driverCodeEmail('584729163805'));assert.throws(()=>c.normalizeDriverCode('1234'));c.user={user_metadata:{driver_code_only:true}};assert.equal(c.isCodeDriver(),false);c.user={app_metadata:{driver_code_only:true}};assert.equal(c.isCodeDriver(),true);assert.match(generateDriverCode(),/^\d{12}$/);});
test('database binding is service-only and checks actor, scope and expected user',()=>{const sql=fs.readFileSync('supabase/migrations/20261004_driver_code_access.sql','utf8');assert.match(sql,/revoke all.*from public,anon,authenticated/);assert.match(sql,/grant execute.*to service_role/);assert.match(sql,/d\.user_id is distinct from p_expected_user/);assert.match(sql,/lower\(owner_email\)=actor_email/);});
test('code driver is forced to work screen when opening store or admin routes',()=>{let screen=0,base=0,rewrites=[];const elements={'#driver-code-entry':{},'#driver-code-signout':{},'#account':{},'#dashboard-link':{}};const c=vm.createContext({crypto,TextEncoder,Uint8Array,user:{app_metadata:{driver_code_only:true}},api:{},passwordRecovery:false,location:{hash:'#dashboard/stores'},history:{replaceState:(a,b,value)=>{rewrites.push(value);c.location.hash=value;}},trackingTimer:1,clearInterval(){},document:{body:{classList:{toggle(){}}}},$:s=>elements[s],merchantDrivers(){},renderDriverDashboard(){},render(){base++;},customerSignOut(){},window:{removeEventListener(){},addEventListener(){}}});vm.runInContext(fs.readFileSync('driver-code.js','utf8')+'\nrenderDriverDashboard=()=>{globalThis.screenCount=(globalThis.screenCount||0)+1;};',c);c.render();assert.deepEqual(rewrites,['#driver']);assert.equal(c.screenCount,1);assert.equal(base,0);assert.equal(elements['#driver-code-signout'].hidden,false);c.location.hash='#store/other';c.render();assert.equal(c.screenCount,2);});

test('view and delete require driver scope and never create or rotate identity',async()=>{const previous={id:did,store_id:sid,user_id:'old',name:'D',phone:'0999',email:'hash@driver.damascus-shop.invalid',active:false};for(const action of ['view','delete']){const f=fixture({previous,savedCode:'123456789012'});const r=await f.handler(req({driver_id:did,action}));assert.equal(r.status,200);assert.equal(f.created.length,0);assert.equal(f.bound[0].name,'manage_driver_code');assert.equal(f.bound[0].p.p_action,action);const denied=fixture({previous,owner:false});assert.equal((await denied.handler(req({driver_id:did,action}))).status,403);assert.equal(denied.bound.length,0);}});
test('old code cannot be recovered; deleted driver cannot be viewed or rotated',async()=>{const previous={id:did,store_id:sid,active:true,name:'D',phone:'0999'};const f=fixture({previous});assert.equal((await f.handler(req({driver_id:did,action:'view'}))).status,404);for(const action of ['issue','view','delete']){const gone=fixture({previous:{...previous,deleted_at:'2026-10-04'}});assert.equal((await gone.handler(req({driver_id:did,action}))).status,404);assert.equal(gone.created.length,0);}});
