const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function app(){const elements={};const document={querySelector:s=>elements[s]||(elements[s]={innerHTML:'',textContent:'',addEventListener(){},insertAdjacentHTML(){},querySelector(){return null;}}),querySelectorAll:()=>[]};const data=new Map();const context=vm.createContext({document,window:{BEEP_CONFIG:{},addEventListener(){},removeEventListener(){}},localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},location:{hash:'#home',href:'https://example.com'},URL,Intl,Date,console,setTimeout,clearTimeout,setInterval(){},clearInterval(){},FileReader:function(){},structuredClone});vm.runInContext(fs.readFileSync('public/merchant.js','utf8')+'\n'+fs.readFileSync('public/app.js','utf8').replace(/init\(\);\s*$/,'')+'\n'+fs.readFileSync('public/features.js','utf8'),context);return {run:s=>vm.runInContext(s,context)};}
test('Damascus opening hours allow overnight tail and order pause is separate from physical opening',()=>{const a=app();a.run("s={active:true,is_open:true,auto_hours:true,opening_hours:{wed:{closed:false,open:'18:00',close:'02:00'},thu:{closed:true}}}");assert.equal(a.run("isStoreOpen(s,new Date('2026-10-01T00:30:00+03:00'))"),true);assert.equal(a.run("isStoreOpen(s,new Date('2026-10-01T02:00:00+03:00'))"),false);a.run('s.is_open=false');assert.equal(a.run("isStoreOpen(s,new Date('2026-10-01T00:30:00+03:00'))"),true);assert.equal(a.run("canStoreOrder(s,new Date('2026-10-01T00:30:00+03:00'))"),false);});
test('option prices reject missing required, unknown and excessive single selections',()=>{const a=app();a.run("p={price:100,option_groups:[{id:'size',required:true,multiple:false,options:[{id:'a',price:20},{id:'b',price:40}]}]}");assert.equal(a.run('selectionPrice(p,[])'),null);assert.equal(a.run("selectionPrice(p,[{group:'size',id:'a'}])"),120);assert.equal(a.run("selectionPrice(p,[{group:'size',id:'unknown'}])"),null);assert.equal(a.run("selectionPrice(p,[{group:'size',id:'a'},{group:'size',id:'b'}])"),null);});
test('restored cart uses current prices and excludes sold out and removed options',()=>{const a=app();a.run("products=[{id:'p',store_id:'s',price:150,available:true,option_groups:[]},{id:'out',store_id:'s',price:10,available:false}];cartStore='s';cart={first:{id:'p',quantity:2,options:[]},second:{id:'out',quantity:1,options:[]},bad:{id:'p',quantity:1,options:[{group:'none',id:'none'}]}}");assert.equal(a.run('subtotal()'),300);assert.equal(a.run('cartItems().length'),1);a.run('saveCart();cart={};cartStore=null;restoreCart()');assert.equal(a.run('subtotal()'),300);});
test('combination key is independent of selection order',()=>{const a=app();assert.equal(a.run("lineKey('p',[{group:'x',id:'1'},{group:'y',id:'2'}])"),a.run("lineKey('p',[{group:'y',id:'2'},{group:'x',id:'1'}])"));});

test('hours are respected even when the old auto_hours flag is false, catalogue does not accept orders',()=>{const a=app();a.run("s={active:true,is_open:true,auto_hours:false,online_ordering:false,delivery_enabled:false,pickup_enabled:false,opening_hours:{fri:{closed:false,open:'10:00',close:'21:00'}}}");assert.equal(a.run("isStoreOpen(s,new Date('2026-10-02T12:00:00+03:00'))"),true);assert.equal(a.run("isStoreOpen(s,new Date('2026-10-02T21:00:00+03:00'))"),false);assert.equal(a.run("canStoreOrder(s,new Date('2026-10-02T12:00:00+03:00'))"),false);a.run('s.online_ordering=true;s.pickup_enabled=true');assert.equal(a.run("canStoreOrder(s,new Date('2026-10-02T12:00:00+03:00'))"),true);a.run('s.opening_hours={fri:{closed:false,open:"10:00",close:"10:00"}}');assert.equal(a.run("isStoreOpen(s,new Date('2026-10-02T12:00:00+03:00'))"),false);});
test('catalogue product renderer shows prices and galleries with no add-to-cart controls',()=>{const a=app();a.run("stores=[{id:'cat',active:true,is_open:true,online_ordering:false,delivery_enabled:false,pickup_enabled:false,name:'Catalogue',description:'',image:'',areas:[],opening_hours:{}}];renderCart=()=>{};products=[{id:'p',store_id:'cat',available:true,name:'Shirt',description:'',price:100,image:'',option_groups:[]}];renderStore('cat')");assert.equal(a.run("document.querySelector('.products').innerHTML.includes('data-add')"),false);assert.equal(a.run("document.querySelector('.products').innerHTML.includes('data-gallery')"),true);assert.equal(a.run("document.querySelector('#app').innerHTML.includes('عرض البضائع والعروض فقط')"),true);});
