const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function tools(){const code=fs.readFileSync('public/market-tools.js','utf8').split('const marketDirtyForms=')[0];const ctx=vm.createContext({console});vm.runInContext(code,ctx);return s=>vm.runInContext(s,ctx);}
test('normalizes Arabic and Persian phone digits and Syrian numbers, rejects malformed contacts',()=>{const run=tools();assert.equal(run("normalizeMarketPhone('٠٩٣٣ ١٢٣ ٤٥٦')"),'+963933123456');assert.equal(run("normalizeMarketPhone('۰۰۴۹ ۱۵۱ ۱۲۳۴۵۶۷۸')"),'+4915112345678');assert.equal(run("normalizeMarketPhone('',true)"),'');for(const n of ['09','abc123','++963999999999','+0123456789'])assert.throws(()=>run(`normalizeMarketPhone(${JSON.stringify(n)})`));});
test('stock distinguishes size/color combinations and zero blocks unavailable variants',()=>{const run=tools();run("g=[{id:'size',name:'Size',required:true,multiple:false,options:[{id:'m',name:'M'},{id:'l',name:'L'}]},{id:'color',name:'Color',required:true,multiple:false,options:[{id:'black',name:'Black'},{id:'white',name:'White'}]}];p={stock_tracking:true,stock_rows:[{variant_key:'color:black|size:m',stock:2}]}");assert.equal(run('stockCombinations(g).length'),4);assert.equal(run("availableMarketStock(p,[{group:'size',id:'m'},{group:'color',id:'black'}])"),2);assert.equal(run("availableMarketStock(p,[{group:'size',id:'l'},{group:'color',id:'black'}])"),0);assert.throws(()=>run('stockCombinations([{...g[0],multiple:true}])'));});
test('inventory limits combinations and offers general stock for products without options',()=>{const run=tools();assert.equal(run('stockCombinations([]).length'),1);assert.throws(()=>run("stockCombinations(Array.from({length:4},(_,i)=>({id:String(i),required:true,multiple:false,options:Array.from({length:4},(_,n)=>({id:String(n),name:String(n)}))})))"));});
test('address ignores empty parts and connection errors explain safe retries',()=>{const run=tools();assert.equal(run("joinMarketAddress({street:'شارع السوق',building:'12',floor:'2',landmark:''})"),'شارع السوق، 12، الطابق 2');assert.match(run("marketError({message:'Failed to fetch'})"),/سجل مشترياتك/);assert.equal(run("marketError({message:'المنتج غير متاح',code:'P0001'})"),'المنتج غير متاح');});
test('uncertain request retries reuse one identity and reject changed input until history is checked',()=>{const code=fs.readFileSync('public/market-tools.js','utf8');let counter=0;const saved=new Map();const ctx=vm.createContext({user:{id:'one'},crypto:{randomUUID:()=>`attempt-${++counter}`},sessionStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)},FormData:class{constructor(f){this.f=f;}get(k){return this.f[k]??null;}},orderMethod:()=> 'pickup',cartItems:()=>[{id:'p',quantity:1,options:[]}],console});vm.runInContext(code.split('const marketDirtyForms=')[0]+'\n'+code.slice(code.indexOf('let marketPending='),code.indexOf('// Stage progress')),ctx);const run=s=>vm.runInContext(s,ctx);run("f={name:'Ali',phone:'0933123456'};s={id:'s'}");assert.equal(run('marketOrderRequest(f,s)'),'attempt-1');assert.equal(run('marketOrderRequest(f,s)'),'attempt-1');run("marketOrderRejected({message:'Failed to fetch'})");assert.equal(run('marketOrderRequest(f,s)'),'attempt-1');assert.throws(()=>run("marketOrderRequest({...f,name:'New'},s)"));run("marketOrderRejected({code:'P0001'})");assert.equal(run('marketOrderRequest(f,s)'),'attempt-2');});

test('in-memory retry identity survives blocked session storage and does not carry to another account',()=>{const code=fs.readFileSync('public/market-tools.js','utf8');let n=0;const ctx=vm.createContext({user:{id:'one'},crypto:{randomUUID:()=>`r-${++n}`},sessionStorage:{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')},removeItem(){throw Error('blocked')}},FormData:class{constructor(f){this.f=f;}get(k){return this.f[k]??null;}},orderMethod:()=> 'pickup',cartItems:()=>[{id:'p',quantity:1,options:[]}]});vm.runInContext(code.split('const marketDirtyForms=')[0]+'\n'+code.slice(code.indexOf('let marketPending='),code.indexOf('// Stage progress')),ctx);const run=s=>vm.runInContext(s,ctx);run("f={name:'Ali',phone:'0933123456'};s={id:'s'}");assert.equal(run('marketOrderRequest(f,s)'),'r-1');assert.equal(run('marketOrderRequest(f,s)'),'r-1');run("user={id:'two'}");assert.equal(run('marketOrderRequest(f,s)'),'r-2');});
test('Arabic edits keep a persistent translation review flag until translated values are updated',()=>{const code=fs.readFileSync('public/market-tools.js','utf8');const ctx=vm.createContext({structuredClone,readTranslations:(f,r)=>structuredClone(r.translations),translatedDefault:(r,k,l)=>r.translations[l]?.[k]||''});vm.runInContext(code.slice(code.indexOf('const marketReadTranslations='),code.indexOf('const marketHelpForm=')),ctx);const run=s=>vm.runInContext(s,ctx);run("record={name:'قديم',translations:{tr:{name:'Old TR'},de:{name:'Old DE'}}};values={name:'جديد',i18n_tr_name:'Old TR',i18n_de_name:'Old DE'};f={get:k=>values[k]??null}");assert.equal(run("readTranslations(f,record,['name'])._review.tr[0]"),'name');assert.equal(run("readTranslations(f,record,['name'])._review.de[0]"),'name');run("values.i18n_tr_name='New TR'");assert.equal(run("readTranslations(f,record,['name'])._review.tr.length"),0);assert.equal(run("readTranslations(f,record,['name'])._review.de.length"),1);});
