const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const code=fs.readFileSync('supabase/functions/create-phone-account/index.ts','utf8').replace(/^import .*\n/,'').split('\nconst keys=')[0].replaceAll('export function','function');
const {createHandler,normalizePhone}=new Function(code+';return {createHandler,normalizePhone};')();
const sid='11111111-1111-4111-8111-111111111111';
function fixture({admin=true,valid=true,duplicate=false,conflict=false}={}){const calls=[],deleted=[];let updates=[];const client={auth:{getUser:async()=>({data:{user:valid?{id:'admin'}:null}}),admin:{createUser:async p=>{calls.push(p);return duplicate?{error:{code:'email_exists',message:'already exists'}}:{data:{user:{id:'new'}}};},deleteUser:async id=>{deleted.push(id);return {};}}},from:table=>{const q={select:()=>q,eq:()=>q,is:()=>q,maybeSingle:async()=>({data:table==='platform_admins'?(admin?{user_id:'admin'}:null):{id:sid,name:'Shop',revision:4}})};return q;}};const scoped=token=>{assert.equal(token,'test');return {from:()=>{const q={update:p=>{updates.push(p);return q;},eq:()=>q,select:async()=>({data:conflict?[]:[{id:sid}]})};return q;}}};return {handler:createHandler(client,scoped),calls,deleted,updates};}
function req(extra={},token=true){return new Request('https://example.com',{method:'POST',headers:{origin:'https://damascus-shop.com','content-type':'application/json',...(token?{authorization:'Bearer test'}:{})},body:JSON.stringify({name:'Person',phone:'0945123456',password:'584729163805',...extra})});}
test('normalizes local, international and Arabic phone digits consistently',()=>{for(const s of ['0945123456','+963 945 123 456','00963945123456','٩٦٣٩٤٥١٢٣٤٥٦','۰۹۴۵۱۲۳۴۵۶'])assert.equal(normalizePhone(s),'+963945123456');for(const s of ['1234','foo','+00012345678'])assert.throws(()=>normalizePhone(s));});
test('requires admin and valid session before any user creation',async()=>{for(const f of [fixture({admin:false}),fixture({valid:false})]){assert.ok([401,403].includes((await f.handler(req())).status));assert.equal(f.calls.length,0);}const f=fixture();assert.equal((await f.handler(req({},false))).status,401);});
test('rejects short, repeated, sequential and nonnumeric secrets',async()=>{for(const password of ['123456','111111111111','123456789012','not-a-number']){const f=fixture();assert.equal((await f.handler(req({password}))).status,400);assert.equal(f.calls.length,0);}});
test('creates phone identity without granting platform privilege or returning password',async()=>{const f=fixture();const r=await f.handler(req({role:'admin',email:'other@example.com'}));assert.equal(r.status,201);assert.equal(f.calls[0].email,'963945123456@phone.damascus-shop.invalid');assert.deepEqual(f.calls[0].app_metadata,{managed_phone_account:true});assert.deepEqual(await r.json(),{phone:'+963945123456',name:'Person',store_name:null});assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://damascus-shop.com');assert.equal(r.headers.get('Cache-Control'),'no-store');});
test('existing account never overwritten',async()=>{const f=fixture({duplicate:true});assert.equal((await f.handler(req())).status,409);assert.equal(f.updates.length,0);assert.equal(f.deleted.length,0);});
test('store linking uses admin session and expected revision; conflict cleans up newly created account',async()=>{let f=fixture();assert.equal((await f.handler(req({store_id:sid}))).status,201);assert.deepEqual(f.updates,[{owner_email:'963945123456@phone.damascus-shop.invalid'}]);f=fixture({conflict:true});assert.equal((await f.handler(req({store_id:sid}))).status,409);assert.deepEqual(f.deleted,['new']);});
test('client login uses same canonical identity and cryptographic 12 digit generator',()=>{const c=vm.createContext({dashboardAccounts(){},crypto:require('node:crypto').webcrypto,Uint8Array});vm.runInContext(fs.readFileSync('phone-login.js','utf8')+'\n'+fs.readFileSync('phone-accounts.js','utf8'),c);for(const v of ['0945123456','+963945123456','٠٩٤٥١٢٣٤٥٦'])assert.equal(c.accountLoginIdentity(v),'963945123456@phone.damascus-shop.invalid');assert.equal(c.accountLoginIdentity('old@example.com'),'old@example.com');assert.match(c.numericAccountPassword(),/^\d{12}$/);assert.equal(c.accountIdentityLabel('963945123456@phone.damascus-shop.invalid'),'+963945123456');});
