import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import worker,{measureBucket,operationClasses} from '../cloudflare/images/worker.mjs';
test('bucket measurement follows cursors and includes thumbnails',async()=>{const seen=[];const bucket={list:async options=>{seen.push(options.cursor);return options.cursor?{objects:[{size:40}],truncated:false}:{objects:[{size:500},{size:70}],truncated:true,cursor:'next'};}};assert.deepEqual(await measureBucket(bucket),{bytes:610,objects:3,complete:true});assert.deepEqual(seen,[undefined,'next']);});
test('a capped bucket scan is explicitly partial',async()=>{const result=await measureBucket({list:async()=>({objects:[{size:1}],truncated:true,cursor:'next'})});assert.deepEqual(result,{bytes:20,objects:20,complete:false});});
test('R2 classification separates multipart listing, reads, free deletes and unknown operations',()=>{const rows=['ListParts','ListMultipartUploads','GetObject','UsageSummary','DeleteObject','Unknown'].map(actionType=>({dimensions:{actionType},sum:{requests:2}}));assert.deepEqual(operationClasses(rows),{classA:4,classB:4,unclassified:2});});
const origin='https://damascus-shop.com',url='https://images.test/admin/usage';
test('usage is inaccessible to visitors, foreign origins and merchants',async()=>{let listed=false;const env={ALLOWED_ORIGINS:origin,SUPABASE_URL:'https://supabase.test',SUPABASE_ANON_KEY:'public',IMAGES:{list:async()=>{listed=true;throw Error('must not reach');}}};const previous=globalThis.fetch;globalThis.fetch=async()=>Response.json(false);try{for(const [headers,status] of [[{Origin:origin},401],[{Origin:'https://foreign.test',Authorization:'Bearer token'},403],[{Origin:origin,Authorization:'Bearer merchant'},403]]){const response=await worker.fetch(new Request(url,{method:'POST',headers}),env);assert.equal(response.status,status);}assert.equal(listed,false);}finally{globalThis.fetch=previous;}});
test('admin can measure R2 without an analytics secret; missing analytics is null',async()=>{const previous=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json(true);};try{const env={ALLOWED_ORIGINS:origin,SUPABASE_URL:'https://supabase.test',SUPABASE_ANON_KEY:'public',CF_ACCOUNT_ID:'test-usage',IMAGES:{list:async()=>({objects:[{size:120}],truncated:false})}};const request=()=>new Request(url,{method:'POST',headers:{Origin:origin,Authorization:'Bearer admin'}});const response=await worker.fetch(request(),env),body=await response.json();assert.equal(response.status,200);assert.deepEqual(body.r2,{bytes:120,objects:1,complete:true});assert.equal(body.workers,null);assert.equal(body.operations,null);assert.ok(body.errors.workers);await worker.fetch(request(),env);assert.equal(calls,2,'cached measurements still require administrator authorization');}finally{globalThis.fetch=previous;}});
function client(admin=true){const handlers={},content={dataset:{},setAttribute(){},querySelector(selector){return handlers[selector]||(handlers[selector]={});}},tabs={querySelector:()=>({}),querySelectorAll:()=>[]};let rpc=0,network=0;const context={admin,user:{id:'admin'},location:{hash:'#dashboard/usage'},window:{BEEP_CONFIG:{r2UploadUrl:'https://images.test/upload'},addEventListener(){}},document:{getElementById:id=>id==='dashboard-content'?content:null,querySelector:()=>tabs},localStorage:{getItem:()=>null,setItem(){}},renderDashboard(){},esc:String,URL,AbortSignal,Date,Number,Promise,JSON,api:{rpc:async()=>{rpc++;return {data:{database_bytes:100,storage_bytes:0,storage_objects:0,registered_users:2,measured_at:new Date().toISOString()}};},auth:{getSession:async()=>({data:{session:{access_token:'test'}}})}},fetch:async()=>{network++;return new Response('Not found',{status:404});}};vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('../service-usage.js',import.meta.url),'utf8'),context);return {context,content,handlers,calls:()=>({rpc,network})};}
test('usage screen makes no requests until clicked and isolates provider failures',async()=>{const c=client();assert.deepEqual(c.calls(),{rpc:0,network:0});assert.match(c.content.innerHTML,/غير متصل/);await c.handlers['[data-usage-refresh]'].onclick();assert.deepEqual(c.calls(),{rpc:1,network:1});assert.match(c.content.innerHTML,/حدّث كود Worker/);assert.match(c.content.innerHTML,/آخر قراءة ناجحة/);assert.match(c.content.innerHTML,/غير متصل/);});
test('non-admin users do not get a usage screen or request data',()=>{const c=client(false);assert.equal(c.content.innerHTML,undefined);assert.deepEqual(c.calls(),{rpc:0,network:0});});
