const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('video-links.js','utf8');
function helpers(){const ctx=vm.createContext({URL,document:{documentElement:{lang:'ar'}}});vm.runInContext(code.slice(0,code.indexOf('function videoSurface(')),ctx);return input=>vm.runInContext('parsePlaceVideo('+JSON.stringify(input)+')',ctx);}
test('YouTube watch, share, shorts, live and embed links use a fixed player host',()=>{const parse=helpers();for(const link of ['https://youtube.com/watch?v=M7lc1UVf-VE','https://youtu.be/M7lc1UVf-VE?si=tracking','https://youtube.com/shorts/M7lc1UVf-VE','https://youtube.com/live/M7lc1UVf-VE','https://www.youtube-nocookie.com/embed/M7lc1UVf-VE']){const info=parse(link);assert.equal(info.kind,'embed');assert.equal(new URL(info.src).hostname,'www.youtube-nocookie.com');assert.equal(new URL(info.src).searchParams.get('autoplay'),'0');assert.equal(info.url,'https://www.youtube.com/watch?v=M7lc1UVf-VE');}});
test('YouTube timestamp is kept and invalid video paths are rejected',()=>{const parse=helpers();assert.equal(new URL(parse('https://youtu.be/M7lc1UVf-VE?t=1m30s').src).searchParams.get('start'),'90');assert.throws(()=>parse('https://youtube.com/watch?v=broken'));assert.throws(()=>parse('https://youtube.com/channel/anything'));});
test('Vimeo unlisted hash survives save and normalization roundtrip',()=>{const parse=helpers();const video=parse('https://player.vimeo.com/video/76979871?h=abc123def4');assert.equal(video.url,'https://vimeo.com/76979871/abc123def4');assert.equal(new URL(parse(video.url).src).searchParams.get('h'),'abc123def4');});
test('Facebook full video URLs use the video plugin and share links have honest fallback',()=>{const parse=helpers();const video=parse('https://m.facebook.com/myshop/videos/123456789/?tracking=yes');assert.equal(new URL(video.src).pathname,'/plugins/video.php');assert.equal(new URL(video.src).searchParams.get('href'),'https://www.facebook.com/watch/?v=123456789');assert.equal(parse('https://www.facebook.com/share/v/AbCd/').kind,'link');assert.equal(parse('https://fb.watch/AbCd/').kind,'link');});
test('direct video links use media player; other sites never become arbitrary iframes',()=>{const parse=helpers();assert.equal(parse('https://cdn.example.com/product.MP4?token=abc').kind,'video');const unknown=parse('https://youtube.com.evil.example/watch?v=M7lc1UVf-VE');assert.equal(unknown.kind,'link');assert.equal(unknown.src,undefined);assert.equal(parse('https://example.com/video-page').kind,'link');});
test('unsafe links and pasted embed HTML are rejected',()=>{const parse=helpers();for(const value of ['javascript:alert(1)','data:video/mp4,abc','http://youtube.com/watch?v=M7lc1UVf-VE','https://user:pass@example.com/video.mp4','https://127.0.0.1/video.mp4','https://[::1]/video.mp4','https://localhost/video.mp4','https://device.local/video.mp4','https://example.com:8443/video.mp4','<iframe src="https://youtube.com/embed/M7lc1UVf-VE"></iframe>'])assert.throws(()=>parse(value),value);assert.equal(parse('  '),null);});
test('video save and removal preserve translations and other shop metadata',()=>{const context=vm.createContext({URL,document:{documentElement:{lang:'en'},querySelector:()=>({addEventListener(){}})},readTranslations:(form,record)=>structuredClone(record.translations),merchantEditor(){},editStore(){},editProduct(){},renderStore(){}});vm.runInContext(code,context);const record={translations:{en:{name:'Shop'},_social_links:{website:'https://example.com'},_community:{booking_enabled:true}}};context.record=record;context.form=new Map([['video_url','https://youtu.be/M7lc1UVf-VE']]);let result=vm.runInContext('readTranslations(form,record,[])',context);assert.equal(result._video_url,'https://www.youtube.com/watch?v=M7lc1UVf-VE');assert.deepEqual(result._social_links,record.translations._social_links);assert.equal(result._community.booking_enabled,true);context.record={translations:result};context.form=new Map([['video_url','']]);result=vm.runInContext('readTranslations(form,record,[])',context);assert.equal(result._video_url,undefined);assert.equal(result.en.name,'Shop');});
test('external players load and start only after visitor click',()=>{const nodes=[];class Element{constructor(tag){this.tag=tag;this.children=[];this.dataset={};nodes.push(this);}append(...items){for(const item of items){item.parent=this;this.children.push(item);}}replaceWith(item){const i=this.parent.children.indexOf(this);this.parent.children[i]=item;item.parent=this.parent;}setAttribute(name,value){this[name]=value;}addEventListener(){}}
 const context=vm.createContext({URL,navigator:{userAgent:'Chrome'},esc:x=>x,document:{documentElement:{lang:'en'},createElement:tag=>new Element(tag)}});vm.runInContext(code.slice(0,code.indexOf('function addVideoFields(')),context);const box=vm.runInContext("videoSurface(parsePlaceVideo('https://youtu.be/M7lc1UVf-VE'),'Demo')",context);assert.equal(nodes.filter(n=>n.tag==='iframe').length,0);box.children.find(n=>n.tag==='button').onclick();const frame=nodes.find(n=>n.tag==='iframe');assert.equal(new URL(frame.src).searchParams.get('autoplay'),'1');assert.ok(frame.allow.includes('autoplay'));assert.equal(frame.referrerPolicy,'strict-origin-when-cross-origin');assert.equal(frame.title,'Demo');});

test('original video link works in the Android window and keeps source referrer',()=>{
 for(const [userAgent,target] of [['Chrome','_blank'],['Chrome ShahinAndroid/1.2','_self']]){
  const context=vm.createContext({URL,navigator:{userAgent},document:{documentElement:{lang:'en'},createElement:()=>({dataset:{},children:[],append(...items){this.children.push(...items)}})}});
  vm.runInContext(code.slice(0,code.indexOf('function addVideoFields(')),context);
  const box=vm.runInContext("videoSurface(parsePlaceVideo('https://example.com/video-page'),'Demo')",context);
  const link=box.children.at(-1);
  assert.equal(link.href,'https://example.com/video-page');
  assert.equal(link.target,target);
  assert.equal(link.referrerPolicy,'strict-origin-when-cross-origin');
  assert.equal(link.rel,'noopener');
 }
});
