const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export function imageType(bytes){if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';if([137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n))return 'image/png';if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')return 'image/webp';return null;}
export default {async fetch(request,env){const url=new URL(request.url),allowed=(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()),origin=request.headers.get('Origin'),cors=allowed.includes(origin)?{'Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'POST, OPTIONS'}:{};const json=(data,status=200)=>Response.json(data,{status,headers:cors});
 if(request.method==='OPTIONS')return allowed.includes(origin)?new Response(null,{status:204,headers:cors}):json({error:'Origin denied'},403);
 if(request.method==='GET'&&/^\/images\/[0-9a-f-]{36}\/[0-9a-f-]{36}\/(original\.(jpg|png|webp)|thumbnail.webp)$/.test(url.pathname)){const object=await env.IMAGES.get(url.pathname.slice(8));if(!object)return new Response('Not found',{status:404});return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff'}});}
 if(request.method!=='POST'||url.pathname!=='/upload')return json({error:'Not found'},404);if(!allowed.includes(origin))return json({error:'Origin denied'},403);const auth=request.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({error:'سجّل الدخول'},401);if(Number(request.headers.get('Content-Length'))>2000000)return json({error:'الصورة كبيرة جدًا'},413);
 try{const headers={apikey:env.SUPABASE_ANON_KEY,Authorization:auth};const user=await fetch(env.SUPABASE_URL+'/auth/v1/user',{headers});if(!user.ok)return json({error:'سجّل الدخول مجددًا'},401);const form=await request.formData(),sid=form.get('store_id');if(!UUID.test(sid))return json({error:'متجر غير صالح'},400);const access=await fetch(env.SUPABASE_URL+'/rest/v1/rpc/manages_store',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({sid})});if(!access.ok||await access.json()!==true)return json({error:'ليس لديك صلاحية لهذا المحل'},403);
 const files=[form.get('photo'),form.get('thumbnail')],limits=[1572864,65536],types=[];for(let i=0;i<2;i++){const file=files[i];if(!file||typeof file.arrayBuffer!=='function'||!file.size||file.size>limits[i])return json({error:'حجم الصورة غير صالح'},400);const type=imageType(new Uint8Array(await file.arrayBuffer()));if(!type||type!==file.type||(i===1&&type!=='image/webp'))return json({error:'صيغة الصورة غير صالحة'},400);types.push(type);}const root=sid+'/'+crypto.randomUUID(),ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[types[0]],keys=[root+'/original.'+ext,root+'/thumbnail.webp'];try{for(let i=0;i<2;i++)await env.IMAGES.put(keys[i],files[i].stream(),{httpMetadata:{contentType:types[i]}});}catch(err){await env.IMAGES.delete(keys);throw err;}return json({url:url.origin+'/images/'+keys[0]},201);
 }catch{return json({error:'تعذر رفع الصورة. حاول مرة أخرى.'},500);}
}};
