const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export function imageType(bytes){if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';if([137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n))return 'image/png';if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')return 'image/webp';return null;}
export default {async fetch(request,env){const url=new URL(request.url),allowed=(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()),origin=request.headers.get('Origin'),cors=allowed.includes(origin)?{'Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'POST, OPTIONS'}:{};const json=(data,status=200)=>Response.json(data,{status,headers:cors});
 if(request.method==='OPTIONS')return allowed.includes(origin)?new Response(null,{status:204,headers:cors}):json({error:'Origin denied'},403);
 if(request.method==='GET'&&/^\/images\/[0-9a-f-]{36}\/[0-9a-f-]{36}\/(original\.(jpg|png|webp)|thumbnail.webp)$/.test(url.pathname)){const object=await env.IMAGES.get(url.pathname.slice(8));if(!object)return new Response('Not found',{status:404});return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff'}});}
 if(request.method==='POST'&&url.pathname==='/admin/usage')return usageResponse(request,env,json,allowed.includes(origin));
 if(request.method!=='POST'||url.pathname!=='/upload')return json({error:'Not found'},404);if(!allowed.includes(origin))return json({error:'Origin denied'},403);const auth=request.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({error:'سجّل الدخول'},401);if(Number(request.headers.get('Content-Length'))>2000000)return json({error:'الصورة كبيرة جدًا'},413);
 try{const headers={apikey:env.SUPABASE_ANON_KEY,Authorization:auth};const user=await fetch(env.SUPABASE_URL+'/auth/v1/user',{headers});if(!user.ok)return json({error:'سجّل الدخول مجددًا'},401);const form=await request.formData(),sid=form.get('store_id');if(!UUID.test(sid))return json({error:'متجر غير صالح'},400);const access=await fetch(env.SUPABASE_URL+'/rest/v1/rpc/manages_store',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({sid})});if(!access.ok||await access.json()!==true)return json({error:'ليس لديك صلاحية لهذا المحل'},403);
 const files=[form.get('photo'),form.get('thumbnail')],limits=[1572864,65536],types=[];for(let i=0;i<2;i++){const file=files[i];if(!file||typeof file.arrayBuffer!=='function'||!file.size||file.size>limits[i])return json({error:'حجم الصورة غير صالح'},400);const type=imageType(new Uint8Array(await file.arrayBuffer()));if(!type||type!==file.type||(i===1&&type!=='image/webp'))return json({error:'صيغة الصورة غير صالحة'},400);types.push(type);}const root=sid+'/'+crypto.randomUUID(),ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[types[0]],keys=[root+'/original.'+ext,root+'/thumbnail.webp'];try{for(let i=0;i<2;i++)await env.IMAGES.put(keys[i],files[i].stream(),{httpMetadata:{contentType:types[i]}});}catch(err){await env.IMAGES.delete(keys);throw err;}return json({url:url.origin+'/images/'+keys[0]},201);
 }catch{return json({error:'تعذر رفع الصورة. حاول مرة أخرى.'},500);}
}};

let usageCache=null;
export async function measureBucket(bucket){let bytes=0,objects=0,cursor;for(let page=0;page<20;page++){const list=await bucket.list({limit:1000,...(cursor?{cursor}:{})});for(const object of list.objects){bytes+=object.size;objects++;}if(!list.truncated)return {bytes,objects,complete:true};if(!list.cursor)throw Error('Invalid pagination');cursor=list.cursor;}return {bytes,objects,complete:false};}
export function operationClasses(rows){const a=new Set(['listbuckets','putbucket','listobjects','putobject','copyobject','createmultipartupload','uploadpart','uploadpartcopy','completemultipartupload','putbucketcors','putbucketlifecycleconfiguration','putbucketencryption','lifecyclestoragetiertransition','listmultipartuploads','listparts']),b=new Set(['headbucket','headobject','getobject','usagesummary','getbucketlocation','getbucketcors','getbucketlifecycleconfiguration','getbucketencryption']);let classA=0,classB=0,unclassified=0;for(const row of rows){const action=String(row.dimensions?.actionType||'').toLowerCase().replace(/[^a-z]/g,''),count=Number(row.sum?.requests||0);if(a.has(action))classA+=count;else if(b.has(action))classB+=count;else if(!['deleteobject','deletebucket','abortmultipartupload'].includes(action))unclassified+=count;}return {classA,classB,unclassified};}
async function analytics(env,query,variables){const response=await fetch('https://api.cloudflare.com/client/v4/graphql',{method:'POST',headers:{Authorization:'Bearer '+env.CF_ANALYTICS_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({query,variables}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok||result.errors?.length)throw Error('Analytics unavailable');const account=result.data?.viewer?.accounts?.[0];if(!account)throw Error('Account unavailable');return account;}
export async function usageResponse(request,env,json,originAllowed){
 if(!originAllowed)return json({error:'Origin denied'},403);const auth=request.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({error:'سجّل الدخول'},401);
 try{
  const headers={apikey:env.SUPABASE_ANON_KEY,Authorization:auth,'Content-Type':'application/json'};
  const access=await fetch(env.SUPABASE_URL+'/rest/v1/rpc/is_admin',{method:'POST',headers,body:'{}',signal:AbortSignal.timeout(10000)});if(!access.ok||await access.json()!==true)return json({error:'للإدارة فقط'},403);
  if(usageCache&&usageCache.account===env.CF_ACCOUNT_ID&&Date.now()-usageCache.time<300000)return json({...usageCache.data,cached:true});
  const data={measured_at:new Date().toISOString(),r2:null,workers:null,operations:null,errors:{}};
  try{data.r2=await measureBucket(env.IMAGES);}catch{data.errors.r2='تعذر قراءة ملفات R2';}
  if(env.CF_ANALYTICS_TOKEN&&env.CF_ACCOUNT_ID){
   const now=new Date(),day=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())).toISOString(),month=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString(),variables={account:env.CF_ACCOUNT_ID,day,month,end:now.toISOString()};
   const results=await Promise.allSettled([
    analytics(env,'query($account: string!, $day: Time!, $month: Time!, $end: Time!){viewer{accounts(filter:{accountTag:$account}){today:workersInvocationsAdaptive(limit:1,filter:{datetime_geq:$day,datetime_leq:$end}){sum{requests}} month:workersInvocationsAdaptive(limit:1,filter:{datetime_geq:$month,datetime_leq:$end}){sum{requests}}}}}',variables),
    analytics(env,'query($account: string!, $month: Time!, $end: Time!){viewer{accounts(filter:{accountTag:$account}){r2OperationsAdaptiveGroups(limit:1000,filter:{datetime_geq:$month,datetime_leq:$end}){sum{requests} dimensions{actionType}}}}}',{account:variables.account,month,end:variables.end})
   ]);
   if(results[0].status==='fulfilled'){const a=results[0].value;data.workers={today:a.today.reduce((n,r)=>n+Number(r.sum.requests),0),month:a.month.reduce((n,r)=>n+Number(r.sum.requests),0),scope:'account',source:'analytics'};}else data.errors.workers='تعذر قراءة إحصاءات Worker؛ تحقق من صلاحيات المفتاح';
   if(results[1].status==='fulfilled'){const rows=results[1].value.r2OperationsAdaptiveGroups;data.operations={...operationClasses(rows),scope:'account',period_start:month,complete:rows.length<1000};}else data.errors.operations='تعذر قراءة عمليات R2؛ تحقق من صلاحيات المفتاح';
  }else{data.errors.workers='إحصاءات الحساب غير مربوطة بعد';data.errors.operations='إحصاءات الحساب غير مربوطة بعد';}
  usageCache={account:env.CF_ACCOUNT_ID,time:Date.now(),data};return json(data);
 }catch{return json({error:'تعذر الاتصال بخدمة الاستهلاك'},503);}
}
